Update Interpreter.cpp to enable stack trace
FreeCAD/FreeCAD pull request #11216
Opened 2023-10-27 21:52 UTC by edwilliams16

This enables python debuggers to stack trace after an exception. See https://forum.freecad.org/viewtopic.php?p=714349#p714349
This is authored by @bdieterm I'm just submitting it.

2023-10-27 23:10 UTC, edwilliams16 commented
Looks like the 'fix' breaks some of the internal exception processing. eg   testing matrix inverse in the Spreadsheet tests
Beyond my ability...

2023-10-28 16:13 UTC, bdieterm requested changes

2023-10-28 16:13 UTC, bdieterm commented on src/Base/Interpreter.cpp
>      PP_Fetch_Error_Text();    /* fetch (and clear) exception */
This change will make both the post-mortem debugging as well as the unit tests work:
```suggestion
    PP_Fetch_Error_Text();    /* fetch (and clear) exception */

    // restore and print the exception with set_sys_last_vars to make post-mortem debugging work
    // PyErr_Restore will take ownership of the three passed objects
    PyErr_Restore(PP_last_exception_type, PP_PyDict_Object, PP_last_traceback);
    PP_last_exception_type = nullptr;
    PP_PyDict_Object = nullptr;
    PP_last_traceback = nullptr;
    PyErr_PrintEx(1);
```

2023-10-30 11:51 UTC, wwmayer commented
This change causes several problems:
* Exceptions are always reported and it's not possible any more to suppress them when needed
* In most cases exceptions are reported twice (if the Python redirection is enabled)
* It breaks PyException::setPyException and PyException::raiseException

A much less problematic way is modify PyException::ReportExsception():
```
void PyException::ReportException () const
{
    if (!_isReported) {
        _isReported = true;
        // set sys.last_vars to make post-mortem debugging work
        PySys_SetObject("last_traceback", PP_last_traceback);
        Base::Console().DeveloperError("pyException","%s%s: %s\n",
            _stackTrace.c_str(), _errorType.c_str(), what());
    }
}
```

2023-10-30 19:15 UTC, bdieterm commented
Thank you very much @wwmayer for both, the correct code and the analysis!
I just tested this and post-mortem debugging works great -- even when executing a FCMacro in the FreeCAD macro editor.
Really impressive and elegant -- and actually just a single line of code.

@edwilliams16: Could you please also update the title of this pull request to something like
"Base: set sys.last_vars to make post-mortem debugging work"

2023-10-31 08:40 UTC, merged