Update HLRBRep_AlgoPy.xml
FreeCAD/FreeCAD pull request #11233
Opened 2023-10-30 15:11 UTC by RohanMishra315

#10728

Updated the API documentation of HLRBRep_AlgoPy.xml.

2023-11-06 15:47 UTC, pieterhijma commented
As mentioned in #10728, there are other files that lack documentation as well.

2023-11-06 20:48 UTC, chennes requested changes
As with your other PR, the characters `<` and `>` are not legal in XML, so must be replaced with either their encoded equivalents `&lt;` and `&gt;`, or simply use a different character to indicate your parameter name (I've chosen to use a single quote mark in my suggestions).

2023-11-06 20:48 UTC, chennes commented on src/Mod/Part/App/HLRBRep/HLRBRep_AlgoPy.xml
> +  return 0 if the Shape <S> is not found.</UserDocu>
```suggestion
            <UserDocu>return  the index  of  the  Shape 'S'  and
  return 0 if the Shape 'S' is not found.</UserDocu>
```

2023-11-06 20:48 UTC, chennes commented on src/Mod/Part/App/HLRBRep/HLRBRep_AlgoPy.xml
> +            <UserDocu>hide the Shape <S> by itself.
```suggestion
            <UserDocu>hide the Shape 'S' by itself.
```

2023-11-06 20:48 UTC, chennes commented on src/Mod/Part/App/HLRBRep/HLRBRep_AlgoPy.xml
> +            <UserDocu>set to  hide all the  edges of the  Shape <S>.
```suggestion
            <UserDocu>set to  hide all the  edges of the  Shape 'S'.
```

2023-11-06 20:48 UTC, chennes commented on src/Mod/Part/App/HLRBRep/HLRBRep_AlgoPy.xml
> +            <UserDocu>select only the edges of the Shape <S>
```suggestion
            <UserDocu>select only the edges of the Shape 'S'
```

2023-11-06 20:48 UTC, chennes commented on src/Mod/Part/App/HLRBRep/HLRBRep_AlgoPy.xml
> +            <UserDocu>select only the faces of the Shape <S>.
```suggestion
            <UserDocu>select only the faces of the Shape 'S'.
```

2023-11-15 09:53 UTC, pieterhijma commented
@luzpaz, @chennes: As promised in https://github.com/FreeCAD/FreeCAD/issues/10728#issuecomment-1795184655, I've worked on this pull request. It is in [branch 'missing-api-doc-py-hlr' on my fork](https://github.com/pieterhijma/FreeCAD/tree/missing-api-doc-py-hlr). Since I didn't initiate this PR, I cannot contribute to this one. I think there are two viable courses of action:
- I create a new pull request and we close this one
- A maintainer takes my commits and forces them onto RohanMishra315:patch-5

My preference is the first option, since I improved on RohanMishra's single commit considerably. By the way, my series of commits builds on RohanMishra commit, so merging the new PR without squashing keeps his work attributed. @RohanMishra315: thanks for starting this work!

For the second option, please note that I rebased my branch on master (including RohanMishra's commit). Please let me know your preference.

2023-11-15 10:03 UTC, pieterhijma commented
Commenting on the work that has been done in [branch 'missing-api-doc-py-hlr' on my fork](https://github.com/pieterhijma/FreeCAD/tree/missing-api-doc-py-hlr):

- Since OCCT has a C++ interface, the Python interface needs to be adapted. I carefully checked the types of the Python bindings and matched the documentation accordingly.
- OCCT has lots of missing documentation. I tried to fill in missing pieces as much as possible. As a result, the HLR documentation in FreeCAD's Python interface is now better than OCCT's! (As an example [rg1LineVCompound() in the **poly** algorithm](https://dev.opencascade.org/doc/refman/html/class_h_l_r_b_rep___poly_h_l_r_to_shape.html#a8e64459b306d4d8684766663519f4132) is documented in OCCT but not in the [**non-poly** one](https://dev.opencascade.org/doc/refman/html/class_h_l_r_b_rep___h_l_r_to_shape.html#af39dec75708c85474cdeaf8eac452523). However, they do the same thing, so I took the documentation from the poly algo and reused it in the non-poly algo.)
- Some functions have no documentation. I put a comment in the XML noting that the cause is that OCCT has no documentation.
- I tried to adhere to the standards of types and return values.
- I did the formattting such that it is pleasant in FreeCAD's GUI console.

2023-11-21 16:29 UTC, pieterhijma commented
@chennes, ok, thank you, the new PR is #11478.

2023-11-22 01:11 UTC, chennes commented
Closing now that #11478 is in.

2023-11-22 01:11 UTC, closed without merging