Added Path PostProcessor for old WEDM machines
FreeCAD/FreeCAD pull request #11248
Opened 2023-11-01 02:00 UTC by alromh87

Added Path PostProcessor for old WEDM machines configurable for different machines:

	G91 incremental coordinates
		--relative					(Dissabled by default)
	Specific comment character
		--comments-character		(None by default)
	Specific space character, use "" to ommit spaces
		--command-space				(" " by default)
	Add character before newline
		--endline-character			(None by default)
	Multiplier for machines that use not standard dimensions like micrometers (1000)
		--scale						(1 by default)
	Define decimal points
		--precision					(3 for mm, for inch by default)
	Add trailing 0s
		--fixed-length				(0 (disabled) by default)
	G0 rapid moves disabled by default, replaced with G1
		--use-rapids				(Set flag to enable G0)
	Disable setting units on output code G20/21
		--omit-units				(Set flag to avoid setting units)
	Force two digit codes G01 insted of G1
		--two-digit-codes			(Set flag to enable)
	Add + sign to positive coordinates
		--force-sign				(Set flag to enable)
	Ignore unsuported operations, use Labels and separate with ','
		--ignore-operations			(Empty by default)

#FreeCAD/6049

2023-11-01 12:36 UTC, luzpaz commented
@alromh87 thank you for the contribution. Would you mind fixing the whitespace in the postprocessor output
![Screenshot_20231101_083412](https://github.com/FreeCAD/FreeCAD/assets/4140247/3aebabab-dabf-4406-b83b-268b62a7ebe0)

2023-11-01 12:40 UTC, luzpaz commented
Please fix typos as well
```
Warning: src/Mod/Path/Path/Post/scripts/wedm_post.py:553: unneded ==> unneeded
Warning: src/Mod/Path/Path/Post/scripts/wedm_post.py:553: aplying ==> applying
Warning: src/Mod/Path/Path/Post/scripts/wedm_post.py:605: writen ==> written
```

2023-11-01 13:36 UTC, Syres916 commented
This PR is not complete, as src/Mod/Path/CMakeLists.txt requires modifying, as an example see https://github.com/FreeCAD/FreeCAD/commit/b9537089956d01afb5c376a9d8c6d899c99ef71c

2023-11-01 18:17 UTC, alromh87 commented
@luzpaz I fixed typos and used rebase to change the log message, hope that's the right way to do it.
@Syres916 Added a line to CMakeLists.txt if I understood correctly the PR should be right now

2023-11-01 18:57 UTC, luzpaz commented
This PR needs to be rebased. @alromh87 do you know how to do it?

2023-11-01 19:30 UTC, alromh87 commented
Should I rebase it to latest main?

I think I can do it directly from GitHub web interface.
Otherwise I think it think I can rebase from cli and then force push, please correct me if I'm wrong

2023-11-02 10:43 UTC, luzpaz commented
Github interface sucks when it comes to rebasing...unless you use the github codespace functionality. Looks like you figured it out. Thanks!

2023-11-02 11:12 UTC, luzpaz requested changes

2023-11-02 11:12 UTC, luzpaz commented on src/Mod/Path/Path/Post/scripts/wedm_post.py
> +                                    continue;
Remove semicolon

2023-11-02 11:12 UTC, luzpaz commented on src/Mod/Path/Path/Post/scripts/wedm_post.py
> +            if not coolantMode == "None":
What about `if coolantMode is not "None":`

2023-11-02 11:14 UTC, luzpaz commented
There are more linting warnings in https://github.com/FreeCAD/FreeCAD/actions/runs/6724416304/job/18296194303?pr=11248#step:7:93

2023-11-06 17:20 UTC, merged

2023-11-07 02:22 UTC, luzpaz commented
No lint fixes ?