[Sketcher] Enable customization of edges pattern and width by type. WIP
FreeCAD/FreeCAD pull request #11996
Opened 2024-01-15 17:42 UTC by PaddleStroke

Enable customization of edges pattern and width by type. WIP

ie adds preferences for curve pattern and width for : normal / construction / internal / external geometries.

The main goal is to enable dashed lines for construction curves, which is a long standing request.

The way to do it is to introduce 4 coin layers for each user layers (Abdullah started to implement multi user-layers management even if it is almost unused).

It is currently crashing a lot and debugging does not help me much. WIP.
If someone wants to check it out with a debugger to try to find the bugs it would be awesome. :)

2024-01-16 08:21 UTC, PaddleStroke commented
Huge thanks to @kadet1090 who found the crash that held me the whole day poking in the dark !
It is now almost ready, we just need to discuss the default first.

2024-01-18 12:18 UTC, obelisk79 commented
My proposal for defaults are as follows, along with some feedback regarding the spinboxes you've added:
https://media.discordapp.net/attachments/1162044910535450665/1197513543797448744/image.png

Which results in an appearance as seen here:
https://media.discordapp.net/attachments/1162044910535450665/1197514028126326915/image.png

2024-01-18 22:35 UTC, pierreporte commented
The preference page should be renamed since it’s not only about colors anymore. I suggest “appearance”.

2024-01-18 22:58 UTC, kadet1090 requested changes

2024-01-18 22:58 UTC, kadet1090 commented on src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h
> +    /* //Debug function.
should be deleted

2024-01-18 22:58 UTC, kadet1090 commented on src/Mod/Sketcher/Gui/EditModeCoinManagerParameters.h
> +    std::vector<std::vector<std::vector<int>>>
It is not a change for this PR, but this is getting way too complex. In that point we probably should introduce some proper structures for the layers with proper names, methods etc which would be easier to follow later. 

API could look something like that (just a concept):
```
layer(0).type(SubLayer::External).curveToGeo(curveIndex)
```

Now we have to deal with 3-level deep structures which are not easy to read and remember, stuff like `swcs[l * 4 + t]`.

2024-01-18 22:58 UTC, kadet1090 commented on src/Mod/Sketcher/Gui/EditModeGeometryCoinManager.cpp
> +            swsc[l * 4 + t] = enabled;
`4` should be replaced with `getSubLayerCount()`

2024-01-19 11:44 UTC, PaddleStroke commented
Changed name of pref page to appearance

2024-01-19 16:07 UTC, kadet1090 approved these changes

2024-01-19 23:34 UTC, chennes requested changes
Overall this looks good, thanks! The only issue I see right now is the excessive width of the Appearance tab -- can you tighten up the four lines that have the line style setting on them? On a Mac with the "Classic" theme selected the dialog is quite a bit too wide, requiring a horizontal scroll bar at the default width.

2024-01-20 06:19 UTC, PaddleStroke commented
@chennes width of the dialog is fixed, everything fit in : 
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/c6fbedfb-b8c4-48d2-8f55-ceff7ff2e5ae)

2024-01-20 16:03 UTC, chennes commented
You've still got the horizontal scrollbar there -- something is still amiss with the column widths, there is plenty of space for the widgets so I don't know why Qt wants to add it.

2024-01-22 14:49 UTC, PaddleStroke commented
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/66d83d92-bc93-4bdf-867a-d79f85844d21)

Width fixed so that we don't have the horizontal bar anymore.

2024-01-22 17:12 UTC, merged