[WIP] fix Freeze
FreeCAD/FreeCAD pull request #12856
Opened 2024-03-10 23:05 UTC by FlachyJoe

Fix #12829 

Ping @maxwxyz 

- [x] Frozen state does not persist on save and opening a file. If I freeze an object, alter it and save it, the alteration is not displayed. When reopening, the modified object is visible and the object is not frozen anymore (recompute at opening). The last modification before closing is now irreversible and lost, although the object was frozen and shouln't be altered.
**a 'freezed' object now prevent the document to be saved.**
- [x] If a PartDesign body is frozen, all nested features can be changed and alter the frozen body.
**linked objects are 'freezed' / 'unfreezed' when the state changes**
- [x] A frozen body can be chamfered in the PartWB. After that it cannot be unfrozen again.
**Part_Chamfer create a new ('unfreezed') object, the nested Body is still 'freezed' and 'unfreezable'**
- [ ] A frozen sketch can be activated but is displayed empty in the Sketcher WB
- [ ] The visibility eye icon does not change its state when clicked but the visibillity in the 3D view is toggled (reproduced with a nested sketch in a PartDesign Pad feature)
Also reproduceable with nested object which are frozen inside of a group (e.g. walls in an arch group)
- [ ] Frozen command does not register with undo/redo
**It acts on the object state not on a property. The object is not modified. Not sure it's needed**
- [ ] If you use a part of a frozen object to create a new feature it throws an error (tried to pad a face of the frozen feature: Index out of bound)
**Can not reproduce**
- [ ] If you undo and redo and the body is frozen, all redone features are now outside of the body and cannot be moved inside of the body
- [ ] You can edit frozen features (e.g. draft objects). They wont change but the edit is permanent. On unfreezing, the edit will be applied.
- [ ] Transform commands move the object, even when frozen. When using Draft WB move, they don't move
- [ ] Placement command moves the frozen object.
- [ ] Non-reversable operations could be applied to frozen objects (e.g. smooth a frozen mesh). If this is done by accident it is not noticed, as there is no feedback to the user. If the mesh is later unfrozen, the smoothed, decimated shape is visible.
- [x] The freeze icon is not optimal. It covers the entire icon of the feature, body or object. It is not clear if you want to unfreeze something if this is a body or part container, a spreadsheet or PartDesign features. Maybe it can also be combined with the eye icon as the appearance of the object is frozen
**Fixed** 
![image](https://github.com/FreeCAD/FreeCAD/assets/10371513/256785a8-7ea0-4cca-ab63-0c7f072b4ec3)

- [ ] Could it be placed in the context menu section at the bottom, where "Mark to recompute" and "Recompute" is located, as I understand it's related to that?
- [ ] Could it be renamed? I did not figure out what this is doing and had to look through the PRs.
Proposals: Exclude from recompute, Lock current state,
- [ ] Could it have a checkbox like "Active body" (at the top of the context menu), like: [ x ] Locked to see the current state in the context menu

2024-03-13 20:18 UTC, maxwxyz requested changes

2024-03-13 20:18 UTC, maxwxyz commented on src/Gui/CommandFeat.cpp
>  void StdCmdToggleFreeze::activated(int iMsg)
line 134 above has a typo:
+ QT_TR_NOOP("Toggles freeze **sate** of the selected objects. A freezed object is not recomputed when its parents change.")

should be **state**

2024-03-15 16:43 UTC, maxwxyz commented
@FlachyJoe another approach which was brought up by @obelisk79 was to remove the additional snowflake icon and instead desaturate the original icon of the object and color it slightly blue/icy. Maybe the label text of the object could be greyed out as well.

2024-03-15 17:22 UTC, FlachyJoe commented
@maxwxyz I've currently no idea how to do this but if no one is in a hurry, I'll learn.

2024-03-16 20:30 UTC, maxwxyz commented
@FlachyJoe did you change something else with the context menu? It renders always on the top edge of the screen, not on mouse location. Only in PD (own context menu) its at the cursor location.

2024-05-15 18:40 UTC, maxwxyz commented
@FlachyJoe also here the heads up for the upcoming feature freeze. As there are a lot of open points, are you considering this a post 1.0 PR?

2024-05-15 19:29 UTC, FlachyJoe commented
@maxwxyz this is a bug fix not concerned by feature freeze but should be done before release, right?

2024-05-16 03:58 UTC, maxwxyz commented
Yes

2024-06-29 12:29 UTC, FEA-eng commented
@FlachyJoe Will some of those fixes make it 1.0? It would be good to have the Freeze option available in Part Design, for instance.

2024-06-29 14:02 UTC, FlachyJoe commented
I'm not available to end this before release date. The current state with partial fix can be merged.

2024-06-29 14:25 UTC, FEA-eng commented
> I'm not available to end this before release date. The current state with partial fix can be merged.

Sure, no need to fix all the issues at once. If this PR is good to go and fixes some of the issues, please undraft it so that it can be merged.

2024-06-30 11:27 UTC, maxwxyz approved these changes

2024-06-30 15:02 UTC, chennes approved these changes
Linter cleanup (no need to manually make these changes, I will merge them into the PR).

2024-06-30 15:02 UTC, chennes commented on src/Gui/CommandFeat.cpp
> +            for (auto parent: obj->getOutListRecursive())
```suggestion
            for (auto parent : obj->getOutListRecursive())
```

2024-06-30 15:02 UTC, chennes commented on src/App/DocumentObject.cpp
> +        throw Base::AbortException("At least one object is frozen, unable to save.");
```suggestion
    if (this->isFreezed()) {
        throw Base::AbortException("At least one object is frozen, unable to save.");
    }
```

2024-06-30 15:02 UTC, chennes commented on src/App/DocumentObject.cpp
>          return;
```suggestion
    if (isFreezed() && prop != &Visibility) {
        return;
    }
```

2024-06-30 15:02 UTC, chennes commented on src/App/DocumentObject.cpp
> +        return;
```suggestion
    if (isFreezed() && prop != &Visibility) {
        return;
    }
```

2024-06-30 15:02 UTC, chennes commented on src/App/DocumentObject.cpp
> +        return;
```suggestion
    if (isFreezed() && prop != &Visibility) {
        return;
    }
```

2024-11-11 18:11 UTC, adrianinsaval commented
@chennes this is good to merge now right?

2024-11-13 12:35 UTC, adrianinsaval commented
ok to squash this?

2024-11-19 16:29 UTC, FlachyJoe commented
Squashed and rebased

2024-11-20 12:21 UTC, luzpaz commented
![Screenshot_20241120_071813](https://github.com/user-attachments/assets/d900904e-d92f-485c-94cc-797e9b447af6)

Can the commit subject and body be re-edited. They are very generic, don't mention which ticket it addresses. This is important for folks writing the Release Notes and documentation. TIA

2024-11-26 12:02 UTC, maxwxyz commented
@FlachyJoe unfortunately another conflict due to the large queue of PRs

2024-11-30 20:57 UTC, maxwxyz commented
@FlachyJoe ping for conflict

2024-12-06 16:56 UTC, merged

2025-10-01 17:31 UTC, Roy-043 commented
This PR changes the behavior of the Std_Placement command. Before this PR multiple objects could be selected. Now only a single object can be selected. Reported on the forum (https://forum.freecad.org/viewtopic.php?t=99693).