TechDraw: Insert View : Enable handling of spreadsheet and arch objects
FreeCAD/FreeCAD pull request #13219
Opened 2024-03-29 16:03 UTC by PaddleStroke

- Enable the 'Insert View' tool to create spreadsheet views and Arch views. (you can select geos and i spreadsheets and j arch objects at the same time).
- Update the icon to show the insert is more capable.
- Remove the Insert spreadsheet and insert arch tools from toolbar.

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/0ac83eeb-12d4-483d-a75a-10521a64e94e)

Fixes #13140

2024-03-29 16:51 UTC, maxwxyz requested changes
You can use this if you like, I've made the dashes more uniform
![TechDraw_View](https://github.com/FreeCAD/FreeCAD/assets/6246609/11320046-9bb6-4ca3-a271-9a949a9cde66)

2024-03-29 17:03 UTC, maxwxyz commented
Could this be merged with the insert projection view or is this to much?

2024-03-29 17:05 UTC, PaddleStroke commented
We could go further because the Insert View tool is not defined when selection is a View. So we could define that so that Insert View trigger 'Insert View details' when a view is selected. But maybe that goes too far. Thoughts?

2024-03-29 17:06 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Command.cpp
> +    sToolTipText = QT_TR_NOOP("Insert a View in current page.\n"
Insert a view in current page.
Selected objects, spreadsheets or Arch WB section planes will be added with the current camera orientation.
Without a selection, a file browser lets you select a SVG or image file.

2024-03-29 17:07 UTC, maxwxyz commented
> We could go further because the Insert View tool is not defined when selection is a View. So we could define that so that Insert View trigger 'Insert View details' when a view is selected. But maybe that goes too far. Thoughts?

That would be nice, but could it be possible also to do it with the first step? Set projection views and distance, if a 3D object is selected (not spreadsheet or section view from Arch)

2024-03-29 17:08 UTC, PaddleStroke commented
@maxwxyz what do you call projection view? Is it projection group? If so I don't think we can because input is the same.
Or is it 'project shape'? In which case I do not understand what this tool is about.

2024-03-29 17:09 UTC, maxwxyz commented
@PaddleStroke yes, projection group. Could be called when a shape is selected, default without other views and the result on the page is the same as insert view (but the view is in a projection group)

2024-03-29 17:11 UTC, PaddleStroke commented
That makes sense. We can even create a normal view (instead of a proj group) if the user only select the front view.

2024-03-29 17:12 UTC, maxwxyz commented
> That makes sense. We can even create a normal view (instead of a proj group) if the user only select the front view.

as long as the  user can create a projection from this normal view later on?

2024-03-30 07:48 UTC, PaddleStroke commented
So I have merged projection group as well and it's great.
Now using Insert View on a shape will open the proj-group task panel BUT will still create a normal view until you click on one secondary view. At which point it will replace the normal view by a proj group.

- Normal view now have a taskbox, letting you set scale and direction.
- Double clicking view in the tree now open the task to let you edit.
- Remove one tool from toolbar, simplifying ui.

![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/9092229b-fe8b-409e-861b-f887610539a3)

2024-03-30 07:53 UTC, maxwxyz commented
@PaddleStroke great! And you also had some suggestion for default or standard views as option for that dialog.

2024-03-31 07:15 UTC, PaddleStroke commented
@WandererFan I'm trying to tackle https://github.com/FreeCAD/FreeCAD/issues/5821 at the same time.
It appears to me that the Direction + DirectionX actually defines a placement if I'm not mistaken. So I think it could be good to use the Placement dialog for that. So I turned the middle lineEdit into a button and clicking it opens the placement dialog.
![image](https://github.com/FreeCAD/FreeCAD/assets/19984177/53907bbc-a2e8-4540-9d36-1bbd65d83400)

What do you think about this? Also is there already built in function to turn Direction/DirectionX into placement?

2024-03-31 07:18 UTC, PaddleStroke commented
Edit: Direction/DirectionX seem to rather define a rotation than a placement.

2024-03-31 07:31 UTC, maxwxyz commented
@PaddleStroke few things I've noticed, some might not be related to the changes:
1. If possible, switch to the Page view when a body is selected and you click insert view. Then you directly see the results. 
2. I like the behavior of the combined tool but think new users will find it hard to create a view as it is not directly clear that they need a pre-selection and doing so while the sheet is not visible. Maybe a dialog could pop up before showing the file browser if the user wants that or if the user wants to create a view from existing objects?
3. The page currently does not auto expand in the tree view, not sure if this was the same before
4. Maybe a double click on the view in on the page can also open the dialog as with a double click on the tree view
5. When you insert a single view and start creating dimensions and then double click and set a secondary view, all dimensions are gone. Same with section view. Basically all things which are depending of the first view are deleted or get broken when you double click it and create a projection group out of it. Maybe it should always create a projection view?

2024-03-31 19:00 UTC, PaddleStroke commented
1. Yes, I usually select in the tree so I have not come accross this yet but it sounds reasonable. This is not something that is modified by my PR though and I'm not sure how to switch to the page. But I can probably find easily. Ah yes it must happen when doubleclicked().
2. Here can you please clarify? Are you talking about the tool -> selection workflow? ie when user trigger the tool before selecting?
3. I don't think I changed that.
4. Sounds reasonable. But I'm not sure know how to do this properly. Let's perhaps keep that for later as to not overload this PR.
5. Ah yes as it deletes the normal view and creates a new one. Always a proj group would definitely solve this and would be much simpler (basically most of my PR goes away), but that kind of bloat the tree if you want a simple view. But maybe it's still better.
6. I do not know how the activeView works. I will look into it.
7. I'm not sure how to handle the draft tool because it takes the same input as normal view. So there's no clear way how to differentiate them.

Btw do you have any idea of icon that could replace the camera icon I put in the button for the 'camera direction' ?

2024-04-01 08:50 UTC, maxwxyz commented
> 
>     2. Here can you please clarify? Are you talking about the tool -> selection workflow? ie when user trigger the tool before selecting?

The tool is working fine, but I am not sure that new users get along. Currently, with the separated tools, there is a warning when the user wants to insert a view from a 3D shape but has no selection. In the new combined tool, without a selection just the file dialog opens. I think many new users who want to insert a 3D view do not know that you need to go the 3D view (page is not visible), select your objects, and then click the insert view icon. 
Maybe there could be a warning like today or a hint when no selection is present: You have no selection to insert a view from. Do you want to open a file browser to insert an image file) Yes/No


> 
> Btw do you have any idea of icon that could replace the camera icon I put in the button for the 'camera direction' ?

Currently not, but I think it is clear.

2024-04-01 14:02 UTC, WandererFan commented
> Edit: Direction/DirectionX seem to rather define a rotation than a placement.

DirectionX can rotate the view, and it can also reverse (mirror) it.  In general, the user should never need to touch DirectionX.

2024-04-01 17:16 UTC, PaddleStroke commented
@WandererFan from what I understand the view can be defined by Direction + an angle (that is modified by the rotate 90 buttons)
I was thinking that the angle is defined by the DirectionX, but I'm not sure this is correct.

2024-04-02 12:14 UTC, PaddleStroke commented
@maxwxyz 
1. Done
2. First time you trigger the insert tool without a selection you get a message with a 'do not show again' checkbox
5. I have added a parameter 'InsertAsProjGroup' for testing purposes. If enable the insert tool will create projection group directly. If not enabled it will create simple views. Which can later be turned into proj group at the cost of loosing dimensions / cosmetic etc.

2024-04-02 12:30 UTC, PaddleStroke commented
@WandererFan could you please check the following video presenting the point 5. raised by Max. And let me know what you think is best?
https://github.com/FreeCAD/FreeCAD/assets/19984177/6e0cd51f-3242-4497-898a-0e1ab0e7b4ab

- Is there any usecase where the user want a 'DrawViewPart' instead of a projection group with only front?
- What option do you think is best between the tool creating directly a proj group or a DrawViewPart ?

2024-04-03 13:32 UTC, PaddleStroke commented
Technically they seems to behave the same. But I understand that it's not as neat having a projection group instead of just a view object.

Perhaps then @maxwxyz we just keep as I made initially, and we add a warning when **editing** a simple view and the user try to add a secondary view, we show a message saying "If you turn your view in a projection group you will loose existing cosmetic and dimensions".

2024-04-03 13:34 UTC, maxwxyz commented
That should be in the first attempt already. As then the user needs to chose another angle from the beginning to get the projection group. Otherwise it will be lost.

2024-04-04 16:48 UTC, PaddleStroke commented
I found the better solution. The command now creates DrawProjGroupItem which is a subclass of DrawViewPart, and so when the user wants to add secondary projection, we just move the DrawProjGroupItem into the projection group.
Required a bit of changes to DrawProjGroupItem so that it acts as a DrawViewPart when not in a proj group but that's now working well.
I'm even going to implement the other way around, if you unselect secondary views it will go back to a simple DrawProjGroupItem .

2024-04-06 06:42 UTC, maxwxyz requested changes
Works very good! I've added one remark on the wording for the dialog.
I've played around a bit and switched between single view and projection group and now, somehow I am not able to move the base view of the projection view anymore. Not sure if related to this PR.
Here is the file:
[test.zip](https://github.com/FreeCAD/FreeCAD/files/14892701/test.zip)

It seems to be reproducible if I create first a standard view without secondary views and then switch it to a projection group. The initial first view becomes unmovable, even via the X/Y values in the property editor (not editable). 

There is also sometimes an issue when switching between projection methods (first/third angle) when I have multiple projections already activated: Sometimes there are 2 checkmarks in the dialog but only one view visible on the sheet. Sometimes when clicking off an on a secondary projection, it appears directly on top of the first view. Also, when switching on/off secondary projections (changing checkmarks in the task dialog), the bottom part vanishes and I cannot set projection method or the spacing: 
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/9b045786-557e-40fc-8838-c1370187e150)

Otherwise great!

2024-04-06 06:42 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Command.cpp
> +                msgBox.setText(msgBox.tr("Note: If you want to insert a shape you need to select it before starting the tool, else it opens a file browser to insert SVG or Images."));
Maybe: 
"If you want to insert a view from existing objects, please select them before evoking this tool. Without a selection, a file browser will open, to insert a SVG or image file."

As it's not only shapes but also spreadsheets, arch, 2D faces,...
also just image, multi selection is not possible in the file browser on my side.

Is it possible to have a "go back" button as well, if a user mistakenly did not have a selection and just wants to abort and select something? Currently there is only OK and then the file browser opens.

2024-04-08 15:59 UTC, PaddleStroke commented
@yorikvanhavre do you mean we just remove draft and Arch views from TD toolbar completely?

2024-04-09 07:42 UTC, yorikvanhavre commented
@PaddleStroke in fact yes, they could probably be removed (only the BIM command would exist), but i guess people will complain. I would maybe keep an unified version.

The arch view command is easy to unify with another, because it works only if the selection is an arch sectioneplane or an arch buildingpart.

The draft view is more complicated because it works on groups too and the user needs to decide if they prefer to use the draft view or the normal TD view.

i would say either arch and draft are joined together like in BIM, or arch is unified with the others like you propose, and draft stays standalone. i have no real preference... the first one would have the advantage of being coherent with BIM

2024-04-09 08:19 UTC, PaddleStroke commented
Currently I have done exactly as you said: arch view is in the unified tool because it's easy (specific selection type) but the draft view is difficult because it's actually not specific to one kind of selection. You can for example create a PartDesign Body and use it to make a draft view.

So I do not know what to do with this. So for now I have left it as a separate tool. But it's annoying me :)

I was thinking that we could detect draft objects in the selection, and if detected prompt the user : 
"Draft objects detected, do you want to make a draft view or a normal view?"
My issue is that I don't know which objects should be considered and how to detect them. As I have little knowledge about draft it's hard to say what is the usecase of the Draft View, and so to determine which objects should be detected.

Perhaps if you can tell me for what objects we should offer the draft view ?

Otherwise the draft view tool could be moved to Draft workbench. But I don't know if this is a good idea.

2024-04-09 08:20 UTC, PaddleStroke commented
@maxwxyz thanks for your comment, sorry I could not fix those yet as I'm on assembly fixing some annoying things.

2024-04-09 08:32 UTC, FEA-eng commented
> but i guess people will complain

Yes, I would complain ;-) I use Draft view in TD as a workaround to not being able to manually modify the TD views. I would appreciate a unified tool as proposed in this PR though.

2024-04-09 08:51 UTC, yorikvanhavre commented
> Currently I have done exactly as you said: arch view is in the unified tool because it's easy (specific selection type) but the draft view is difficult because it's actually not specific to one kind of selection. You can for example create a PartDesign Body and use it to make a draft view.

Yes I think that's the best solution for now. The problem is as @FEA-eng says sometimes people want to use the draft view even with non-draft content. So it's hard to make it work "automatically", so I have no better idea at the moment..

2024-04-09 09:01 UTC, PaddleStroke commented
@FEA-eng what do you mean by 'modifying' by the way?

2024-04-09 09:08 UTC, FEA-eng commented
> @FEA-eng what do you mean by 'modifying' by the way?

Mainly using sketching tools to add lines to the view but also removing some lines, replacing them with others and so on. Basically, working on the TD view as if it was a sketch. This is possible in other software like SolidWorks. In FreeCAD, you basically have to use the [Draft Shape2DView](https://wiki.freecad.org/Draft_Shape2DView) tool for that and then create a view of the sketch or draft. An example is presented here: https://forum.freecad.org/viewtopic.php?t=68924

2024-04-09 09:12 UTC, FEA-eng commented
> The problem is as @FEA-eng says sometimes people want to use the draft view even with non-draft content.

To make it clear, I'm thinking about the workflow described in the reply to Paddle - using the Draft Shape2DView tool to create an editable replacement for TD view and then creating an actual TD view of this draft or sketch. But Draft and Arch views in TD could be useful in other cases too.

2024-04-10 13:34 UTC, PaddleStroke commented
@maxwxyz I have fixed all the problems you mentioned. And updated the text as you offered.

2024-04-19 03:25 UTC, chennes commented on src/Mod/TechDraw/Gui/Command.cpp
> +                msgBox.setText(msgBox.tr("If you want to insert a view from existing objects, please select them before evoking this tool. Without a selection, a file browser will open, to insert a S
"Evoking" made me chuckle... you mean "invoking" here....
```suggestion
                msgBox.setText(msgBox.tr("If you want to insert a view from existing objects, please select them before invoking this tool. Without a selection, a file browser will open, to insert a SVG or image file."));
```

2024-04-19 03:31 UTC, chennes approved these changes
I gave the unified insert tool a try tonight and I like it very much -- nice work, @PaddleStroke.

2024-04-22 07:56 UTC, maxwxyz approved these changes

2024-04-23 13:05 UTC, WandererFan commented
Can these commits be squashed, or do we need to keep them as is?

2024-04-23 15:47 UTC, PaddleStroke commented
@WandererFan as you prefer. I tried to make commits that make sense, so perhaps it is best to keep them separate.

2024-04-24 12:24 UTC, WandererFan commented
This needs some wiki changes.

2024-04-24 12:24 UTC, merged