[Icons]Revision of TechDraw Icons
FreeCAD/FreeCAD pull request #14145
Opened 2024-05-18 21:44 UTC by Reqrefusion

I go over all the icons one by one. It is currently in the draft stage. If you have an opinion please let me know.

2024-05-20 06:27 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
The text in red is important, you need to incorporate it somehow

2024-05-20 06:35 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
maybe just the arc length symbol, maybe in yellow like the dimension arrows

2024-05-20 06:38 UTC, maxwxyz requested changes

2024-05-20 06:38 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
I'm not a fan of this one. Maybe it can better reflect that you changes the visual properties of a line

2024-05-20 06:38 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
That's not ideal with the gradient. The tool ads center lines (the yellow ones  in the new one / red in the old icon) to a selected circle.

2024-05-20 11:41 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
@kadet1090 Yes, it looks empty like this, but giving it in written form is very incomprehensible. You need to think of something different there. But it shouldn't be the same as before. I'm open to suggestions.
@maxwxyz Let me try similar things.

2024-05-20 11:42 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
It's not about being empty or not - this symbol has very specific meaning (it says that you are describing the length of an arc) and so it is absolutely crucial to be included.

2024-05-20 11:43 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
I know we don't like the circular gradient. This came to my mind at that moment. Sometimes it happens. It would probably be better to put the different lines used.

2024-05-20 11:44 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
When I saw the circle, it suddenly occurred to me to make a circular gradient. Other than that, if there is no problem, it's fine.

2024-05-20 18:23 UTC, maxwxyz requested changes

2024-05-20 18:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
maybe this should not reflect an arc or quarter of a circle but an arbitrary area?
Also, this is the only icon without the dark line in the grey lines.

2024-05-20 18:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeHorizDimension.svg
What's the meaning of the second pair of yellow lines on these with the last commit?

2024-05-20 18:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateHorizChainDimension.svg
is it on purpose that these are not evenly spaced?

2024-05-20 18:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateHorizChamferDimension.svg
The dimension lines can be seen underneath the grey line and extend too far down. I would put them on top and end on the corners.

2024-05-20 18:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/preferences-techdraw.svg
you can also change these icons for new page and new from template (folder icon)

2024-05-20 18:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
I'd delete the fill of this circle and instead make another outline on the centerlines. The yellow part is the important one here.

2024-05-20 18:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
not sure if this makes the tool clear. With this tool you  don't select or define the style (there's the tool for it next to it), you just apply the last defined style to the line.

2024-05-20 18:34 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeHorizDimension.svg
The = sign is probably not good, I need to think a little more, but since the line thickness has to be 2, it is difficult to place it in between.

2024-05-20 18:35 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
I can remove the other lines and leave only the last line, it will give a better result.

2024-05-20 18:37 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
Is the circle important here? I mention the center line because it is important. I use the color of the group to indicate important icons and the color of the group for less important parts.

2024-05-20 18:40 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateHorizChainDimension.svg
Personally, I don't know. I draw all the icons on top of the previous icons as much as possible. That's why I refer to the works as revisions, not remakes. If you think it would be better if they were equal, I would make them equal, and it would even be easier for me.

2024-05-20 18:41 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateHorizChamferDimension.svg
Yes, it can be extended, and I will add a gray dot to the parts where they intersect.

2024-05-20 18:42 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/preferences-techdraw.svg
Of course, I will come to them too.

2024-05-20 18:45 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
Yes, this is the only place where the lines enter because this icon is related to the field. This is something I thought about deliberately and I think is a very good idea. I use color for emphasis. But yes, the shale used is really complicated and I guess it doesn't have any special meaning. It would make sense to change it.

2024-05-20 18:47 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_DiameterDimension.svg
I tried to preserve the curved arrowhead because I thought it was part of the style of the person who made these before. Definitely straight ends would be better.

2024-05-20 18:50 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
I actually played it, but I consider the circle secondary to this tool. That's why I took the thing that can be interacted with in other icons as a secondary item. It's more of an interpretive error.

2024-05-20 19:04 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
Yes, the circle is secondary, that's why I would not fill it. Just delete the grey fill and maybe another outline on the yellow marks.

2024-05-20 19:26 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
This still is less functional then previous icon - it is hard to tell that this symbol actually represents the dimension annotation as it is contextually not placed correctly i.e. without the underlying line. We should not make icons less functional.

2024-05-20 19:30 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
In that case you also omitted the feature that is known from the actual technical drawing standards, this is not a good thing to do.

2024-05-20 19:40 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_3PtAngleDimension.svg
I'm not sure about that icon either. From what I understand this tool is used to annotate angle between 3 arbitrary points, that do not have to be connected by lines - this is what semi-transparent line meant. This icon looses this meaning. Maybe we should try with dotted line to suggest that the line is not actually there?

2024-05-20 19:47 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeHorizDimension.svg
I will probably have to go with red because the area is not suitable for highlighting and I think I can only overcome this with red.

2024-05-20 19:55 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_3PtAngleDimension.svg
I can only imagine the situation where this tool would be needed. Yes, actually, I used this entry line for this purpose in the beginning, but later it became to show secondary elements. We need to think of something for this situation. Of course, jagged lines are the first thing that comes to mind; they may increase the confusion of meaning in general. The thin line is also compatible with the technical drawing.

2024-05-21 18:20 UTC, maxwxyz requested changes
other changes are good. Few icons missing for all TD ones :)

2024-05-21 18:20 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
now just make the yellow centerlines like these
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/d8e1eee5-5cd5-4143-baff-60b95668f457)
or 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/382de6c1-b849-434e-8c91-dbc36578a7a4)

2024-05-21 18:20 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
still not sure about this, but I have no great idea.
@marcuspollio maybe you? This just assigns the predefined style to a selected line.

2024-05-21 18:44 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
I hadn't thought of this. Even though I've been struggling so much with these apartments. Let's see how it goes.

2024-05-21 18:49 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
@maxwxyz In fact, we can get rid of the idea here altogether. Or only the pen remains. The left of the pen tip is a solid line and the right is a dotted line. Thus, it is shown that he changed it.

2024-05-21 18:50 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateHorizChamferDimension.svg
Oh, there's a misunderstanding, I thought you told me to add more lines last time. I'm removing it.

2024-05-21 19:43 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDecreaseDecimal.svg
the yellow line inside is too thin, could they be bold.
not sure about that icon itself: is the arrow meaning you shift the decimal point to the right, increasing the value?
@kadet1090 FYI

2024-05-21 19:44 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
I'd skip the entire grey part.

2024-05-21 19:46 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
Now they just appear switched 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/aa44bf0f-f79b-4178-8a34-500e6703da3f)

2024-05-21 19:55 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDecreaseDecimal.svg
This format is used in Excel.

2024-05-21 19:56 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
Is this a problem? I don't understand.

2024-05-21 19:57 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDecreaseDecimal.svg
Yes, it is easy to understand and familiar from other software so should be fine but I agree that the border on zeroes is a bit much and probably would be better to have some more yellow there

2024-05-21 19:57 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
That's a good idea. It would be best to just keep the pencil and line.

2024-05-21 19:58 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
it's to small and barely noticeable. It should be a fat yellow line like the icons above.

2024-05-27 15:56 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg
this seems to be the wrong icon

2024-05-27 17:32 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg
How wrong icon? What exactly do you understand from this icon? It may be weak in giving meaning, but I don't think it is wrong.

2024-05-27 18:58 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg
Like it is way different than it was and has nothing to do with line that is in the name. Are you sure that this is what you meant?

2024-05-27 22:32 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg
Oh my bad. I understood the vehicle's spec as only center lines. In the beginning, I did it in accordance with all the situations, but I was trying in vain. Simply extend /--—--/ shorten --/—/-- it will look like this. Actually, the problem here was probably that I thought it wouldn't be that simple.

2024-05-29 18:01 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateLengthArc.svg
the inner yellow stroce on the arc is too thin and not really legible, should be the same size as the other arc icon.

2024-05-29 18:02 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_DecorateLine.svg
not sure what the grey rectangle should mean, I think the new icon is more confusing than the old one.

2024-05-29 18:03 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CosmeticCircle.svg
is there a reason why there is a dot in the circle now?

2024-05-30 19:14 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
The arc was removed in order not to raise any questions about the use of the tool. This tool can be used for anything area related. This makes it necessary to use a broader representation of the area. You are right about the regulation of the dimensions.

2024-05-30 19:17 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmCircle.svg
I use dots that are a tone darker in the middle to show the center points.

2024-05-30 19:21 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AngleDimension.svg
I guess you've mixed it up with this icon src/Mod/TechDraw/Gui/Resources/icons/TechDraw_3PtAngleDimension.svg but I've commented here on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AngleDimension.svg

2024-05-30 19:22 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionSelectLineAttributes.svg
It should represent selecting a line type. TechDraw_DecorateLine has the same icon. Actually, this icon is another version of that icon divided into two parts. Here you select the line and replace it with the other tool. Changing the line weights may help, or a gear may be placed to indicate that the adjustment has been made.

2024-05-30 19:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
But why do you use an circle segment in the other area tool? src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg

You contradict yourself here. It should be consistent.

2024-05-30 20:01 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
Because that tool can only be used in areas created with arc.

2024-05-30 20:07 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AngleDimension.svg
Sorry, it was used this way before. So I continued this. Maybe we should convert other icons to this shape. This is a question that needs to be asked in terms of style.

2024-05-31 06:34 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
Not sure where you get your knowledge from but this is wrong:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/2d487755-60e3-49a5-9089-b2ca3d7ddf73)

2024-06-10 10:23 UTC, FEA-eng commented
@Reqrefusion Are you still working on this? The Smart Dimension tool cursor icon definitely needs to be changed for 1.0. Maybe it should be submitted in a separate PR as it fixes an annoying issue (#14203) and could be merged before this general overhaul is finished.

2024-06-10 17:41 UTC, Reqrefusion commented
> @Reqrefusion Are you still working on this? The Smart Dimension tool cursor icon definitely needs to be changed for 1.0. Maybe it should be submitted in a separate PR as it fixes an annoying issue (#14203) and could be merged before this general overhaul is finished.

I've made a lot of progress in the overall revision. I'm committed to finishing it before the UI Freeze. I have full faith that they will all be included in 1.0.

2024-06-15 11:09 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_DecorateLine.svg
So what was the old icon doing? When you press this tool, a panel opens and you change the selected line. It does not draw new lines. The old icon gives this. It's not the icon that's confusing.

2024-06-15 11:13 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
Since it is independent of the shape, the square, which is the most basic geometry that gives the area symbols, is used.

2024-06-15 12:47 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg
![image](https://github.com/FreeCAD/FreeCAD/assets/747404/d7bfa419-e688-4dea-b402-7d0e5210f00e)
I feel that we talked about this icon extensively and finally landed on this design?

2024-06-15 12:48 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateObliqueCoordDimension.svg
@Reqrefusion why are you marking comments as resolved, when they clearly are not? This is still valid comment.

2024-06-15 13:01 UTC, kadet1090 requested changes

2024-06-15 13:01 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_VerticalDimension.svg
Is there a reason to making  the lines so wide? Now it looks more like measuring between two horizontal lines rather than limiting bars of dimensioning annotation.

2024-06-15 15:04 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
This is consistent. This was also used in other icons.

2024-06-15 15:06 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateObliqueCoordDimension.svg
The mentioned problem has been solved for this icon. @kadet1090

2024-06-15 15:07 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertCoordDimension.svg
Sorry, I missed it.

2024-06-15 15:08 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmCircle.svg
The added line can be changed optionally. This makes it more accurate to be the most general line.

2024-06-15 15:10 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionPosHorizChainDimension.svg
FreeCad generally does not use low opacity. Anything can be used for special occasions as long as it doesn't violate the rules.

2024-06-15 15:13 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_VerticalDimension.svg
I don't quite understand what you are trying to say. Can you explain a little more? If you want, here or on discord.

2024-06-15 15:15 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CosmeticCircle.svg
Consistency

2024-06-15 15:24 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmArc.svg
I use dots that are a tone darker in the middle to show the center points.

2024-06-15 22:27 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionHoleCircle.svg
I think there is a problem with posture. I will consider this icon again.

2024-06-16 00:06 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_DecorateLine.svg
By the way, how can the new icon be more confusing than the old icon? 90% same.

2024-06-16 07:14 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmArc.svg
not sure, it just adds inconsistency and has no further meaning.

2024-06-16 07:16 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLockUnlockView.svg
The stroke variations on this is crazy. Why are the colors (fill and stroke) on the arrowhead reversed but not on the lines? The inside strokes on the keyhole are destroying legibility here.

2024-06-16 07:19 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CosmeticCircle.svg
but there is no dot drawn with this tool. And why is the point blue?

2024-06-16 07:31 UTC, maxwxyz requested changes
And please do not just click resolve on the mentioned issues without commenting or making any changes.

2024-06-16 07:31 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_VerticalDimension.svg
The line width (top and bottom) and the arrow are way thicker than all the other icons. You should keep them all consistent across the WB icons.
I've taken a closer look at this icon but I am sure there are also the same problems in the other icons.:
- is there a reason why you have so many hidden layers in the svg? Delete the ones which are not visible:
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/6c12df87-1df0-4fc3-a739-b06ce926ffc0)
- your strokes are not even: the top one is thinner than the one on the side, making your corners not evenly round and strokes not aligned to the pixel grid: 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/f8cccd66-38ad-4088-822b-55d5de2c356b)
- your stroke is wider than 2 px and not aligned to the grid and weirdly skewed: 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/dd0a2337-9105-4063-8491-7fe072b4690c)
- elements are not aligned to the pixel grid: 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/609c8841-10fb-4902-b52b-d33765471395)


Currently I'm wondering if you are doing this on purpose to keep us busy as we've mentioned these issues over and over since at least a month and you make new icons ignoring all input even making them worse. Meanwhile you talk about scaling issues on other icons but cannot deliver in your PR.

2024-06-16 11:12 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
Here there is a reference to a special line in the technical drawing. This was chosen because it is relevant to the topic. So the lines here are correct.

2024-06-16 11:18 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
The gray circle was compared to other icons. And the lines were made to pop out. There is a dot in the middle because this is used in all icons. Dots were also used in the previous icon.

2024-06-16 11:20 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCircleCenterLines.svg
there is no dot in the result and also not in the old icon so a cross in the center would be suitable.

2024-06-16 11:20 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateObliqueChainDimension.svg
I don't understand why you opened this again, I fixed this problem and closed it. All point sizes in this group are the same.

2024-06-16 11:20 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
it is about the outlines: why don't use a stroke for the blue line with a darker outline as on the other icons? Why do the colors flip in the icon? It is not consistent at all.

2024-06-16 11:21 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmArc.svg
It has the meaning of center. And I'm sure.

2024-06-16 11:23 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertCoordDimension.svg
This icon is wrong. Please look at the wiki what this icon does or try the tool: https://wiki.freecad.org/TechDraw_ExtensionCreateVertCoordDimension

It created vertical dimensions. So what are the grey lines supposed to represent? In the other icons grey is used for geometry but then the icon would be wrong.

2024-06-16 11:25 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateObliqueChainDimension.svg
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/53c693f4-c2bf-4381-ab83-a23d0bc7c972)
they are still different on my side for all the dimension icons

2024-06-16 11:26 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
the shape is still blocking the important part of the tool

2024-06-16 11:27 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeVertDimension.svg
Same on this. What are the grey lines?
Also line width is different between the Oblique icon and should be similar.

2024-06-16 11:32 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CosmeticCircle.svg
I use dots that are a tone darker in the middle to show the center points.

2024-06-16 11:34 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_VerticalDimension.svg
Please state clearly if you are accusing me of vandalism. @maxwxyz

2024-06-16 11:41 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
The important part of the tool is the writing. And there is no shape under the text.

2024-06-16 11:43 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
Because the relevant tool does this. What the tool does is change. Also, these lines are thin lines in the technical drawing.

2024-06-16 11:47 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertCoordDimension.svg
What's wrong? It's exactly the same shape as the old icon.

2024-06-16 12:17 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
Can you provide me with example of existing icon in FreeCAD that has lighter stroke on the outside and darker inside?

2024-06-16 12:20 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionPosHorizChainDimension.svg
I haven't said anything about opacity - simply that inverting colors in that way does not happen in FreeCAD. Looking at the icon the reason for inverting the color is unclear, less readable and seems very odd because it is not found in any other place in FreeCAD.

2024-06-16 12:26 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
Now the shape depicted is very small, and area marked in yellow is basically the size of a vertex. Using shape with arc you have way more place for the icon and it looked fine. I don't see any benefit on using square instead of slice of the circle.

2024-06-16 12:51 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertCoordDimension.svg
What is meant with the grey lines?

2024-06-16 14:05 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
The square is a more general shape than the quadrant for indicating area. When a person sees the square, he is absolutely sure that it is the area. But what exactly does the quadrant represent?

2024-06-16 14:06 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
I used it in other icons in this workbench. But as I mentioned on Discord, there is no time left to argue.

2024-06-16 14:12 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertCoordDimension.svg
I think there is a general misunderstanding. And the old icons are responsible for this. I will work on it.

2024-06-16 17:59 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCreateVertCoordDimension.svg
I redid it based on how the icon works.

2024-06-16 23:56 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLockUnlockView.svg
Yes a little bit. I got a little experimental here. I showed that it unlocks by inverting the colors.

2024-06-16 23:57 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionPosHorizChainDimension.svg
It was made similar to the icon you gave as an example.

2024-06-17 14:20 UTC, Reqrefusion commented
There is a very comprehensive study here. It's normal that it's not exactly right, I'm trying to ensure that. However, it is obvious that it is more accurate than before. A similarity is provided for almost all icons and this is tried to be the case for all of them. I request that you try to be more constructive when criticizing. I'm not a vandal. I don't waste my time breaking things. I'm not making it worse. If you think it has gotten worse, write clearly why or make it better and let me know. I never said that I wanted to do this work completely alone, unfortunately things turned out that way.

Please criticize knowing that I am human and even though I have done similar things before, I don't do something like this every day.

2024-06-17 14:21 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_VerticalDimension.svg
Done

2024-06-19 15:55 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_CosmeticCircle.svg
I fix

2024-06-19 17:20 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageDefault.svg
This icon could be a blank page without any stuff and the PageTemplate then could be this one - this should clearly indicate that this is blank and the next one is template that contains something.

2024-06-19 17:21 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Quadrants.svg
That should probably have 3 point in the middle dividing the arc into 4 equal sections? At least looking at the tool description.

2024-06-19 17:23 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_HorizontalExtentDimension.svg
This should be rotated 90 deg

2024-06-19 19:01 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_HorizontalExtentDimension.svg
I'll replace it with the other one, okay.

2024-06-19 19:07 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Quadrants.svg
Yes I tried it and it works the same for every arc. So 3 points 4 sections.

2024-06-19 19:09 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Quadrants.svg
Yes, so the icon should not mislead that it only produces 2 sections.

2024-06-20 00:13 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
I guess this problem is no longer valid because we have moved in another direction to improve readability.

2024-06-20 09:49 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_HorizontalExtentDimension.svg
Replaced

2024-06-20 09:51 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Quadrants.svg
Will you take a look now? Yes, it shows the working logic of the vehicle, but I don't know exactly.

2024-06-20 09:51 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageDefault.svg
It's done, now it's more understandable. Probably.

2024-06-20 20:14 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionHoleCircle.svg
Look again

2024-06-20 20:16 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLockUnlockView.svg
It would be better if we talked about this, I think it gives its meaning very well. But if it needs to be replaced, why not? But I think this is a style issue.

2024-06-20 20:17 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeVertDimension.svg
This was before which fix. Would you look again? I think I fixed it?

2024-06-20 20:28 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Quadrants.svg
now looks good!

2024-06-22 07:28 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
the new icon with the grey background is weird and does not fit in with the rest of the icons.

2024-06-22 07:29 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCascadeVertDimension.svg
it's good

2024-06-22 07:30 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/7e7526d9-3b97-441e-be3d-bfb4c17eb82c)
why do blue and black flip position from left to right?Better would be the blue line with a black outline on both sides (all around)

2024-06-22 07:34 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmArc.svg
I would keep all points the same color for consistency. Also this is not the center of the arc in your icons. To be the center the arc would need to be tangent horizontally on the top point and tangent vertically at the left point.

2024-06-22 07:35 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionDrawCosmCircle.svg
also here the point on the circle is lighter than the other point. should be consistent IMO.
Why is the center color the same as the outer stroke color?

2024-06-22 07:36 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionExtendLine.svg
IMO this icon is not clear. It could also mean move something, mirror something, swap the views. It has no connection to the line.
Also this is too fat in comparison to the other icons appearance.

2024-06-22 07:38 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionHoleCircle.svg
not good. the centerlines should be aligned horizontally and vertically as it is on the. technical drawing. also the dashed stroke makes it look like a egg shape not a circle. The fine centerlines will not be visible with a dark theme. @kadet1090 FYI

2024-06-22 07:40 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg
Same here: IMO this icon is not clear. It could also mean move something, mirror something, swap the views. It has no connection to the line.
Also this is too fat in comparison to the other icons appearance.
@kadet1090 FYI

2024-06-22 08:04 UTC, maxwxyz requested changes
Github seemed to have messed up the review, will add some coments on the individual icons 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/62bc40f8-e11b-4e62-970d-732f617a3ead)
is there a reason you use different stroke sizes and colors on these icons. IMO they should be more consistent. You sometimes have the lighter stroke on the outside, sometimes on the inside.
@kadet1090 FYI

2024-06-22 08:04 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
there should be a slight gap between the dotted square and the line

2024-06-22 08:04 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreeMulti.svg
you should use evenly aligned dashes here too

2024-06-22 08:04 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreePageTemplate.svg
use the page icon here too, not a rectangle

2024-06-22 08:04 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreePageSync.svg
you can use the main GUI icon for refresh and recolor it to be consistent

2024-06-22 08:06 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Dimension_Pointer.svg
@PaddleStroke @obelisk79 is this new icon ok to be recolored by preferences? Using a theme the cross is overlayed with a different color (dark grey on my side) so it currently is visible. If the new icon is not capable of being recolored I might have difficulties to use this new cursor icon on a white page as the outline is so thin.

2024-06-22 08:22 UTC, maxwxyz requested changes
Hopefully GitHub did not comment twice on some icons now

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg
this icon could mean mirror, flip, swap views and has no reference to a line not it's length.
Also it is too fat in comparison to the other icons

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLockUnlockView.svg
the strokes and color choices makes this icon not legible

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionSelectLineAttributes.svg
I'm still worried about this one. Why are the lines on a dark grey square, what does this grey square mean besides making it hard to even see the blue lines?

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionThreadBoltBottom.svg
stroke width and color not consistent with the ones below

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionThreadBoltSide.svg
stroke width and color not consistent with the ones below

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionThreadHoleBottom.svg
stroke width and color not consistent with the ones below

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionThreadHoleSide.svg
stroke width and color not consistent with the ones below

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionVertexAtIntersection.svg
this icon is using a point which is massive in comparison with the other icons

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Lock.svg
the small strokes / widths and the color choices makes the new icon not legible

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_RadiusDimension.svg
why is there an emphasis on the dark dot when it is about the radius?

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreeMulti.svg
the stroke here should be evenly aligned as well

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreePageTemplate.svg
you should use the page icon not a generic rectangle

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreePageUnsync.svg
you can use the main GUI icon for refresh here too and recolor it to be consistent

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreeSection.svg
dashed lines should be aligned evenly here

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_2LineCenterline.svg
the dashes are too small. You can use 3-4 dashes with a consistent outline and larger spacing in between.
The outline should be all around each dash, no full line behind the center and not just on the left and right side as now

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_2PointCenterline.svg
the dashes are too small. You can use 3-4 dashes with a consistent outline and larger spacing in between.
The outline should be all around each dash, no full line behind the center and not just on the left and right side as now

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ActiveView.svg
is this the same as your GUI icon refresh PR? You could use the same here

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_AddOffsetVertex.svg
the points are huge and the lines so small in comparison

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ArchView.svg
why did you change to a B in the new icon?

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ClipGroup.svg
dashed stroke should be aligned evenly here

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ComplexSection.svg
IMO not clear. You should use a simple complex section line, e.g. like the example on the wiki

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_DecorateLine.svg
again the issue with the dark grey rectangle

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ExportPageSVG.svg
export arrow should go to the side as the main GUI icons for document export.
You could also use the page icon here

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_FaceCenterLine.svg
dashes not visible on smaller size, try 3-4 dashes with longer dashes and more spacing. And a stroke around each individual dash

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_FaceDecor.svg
there is no reference to a face

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_FillTemplateFields.svg
you should use the page icon here instead off this generic rounded rectangle

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_GeometricHatch.svg
.pat seems to be a text here. On my side it is not legible. Also there is almost no difference now between the PAT and hatch icon now

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_LeaderLine.svg
you can draw lines with multiple points and no arrowhead so not sure about this

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Multiview.svg
evenly distributed dashes on the stroke also needed on this icon

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageTemplate.svg
this icon looks like "new group" or "new folder" where it should indicate "new page from a chosen template"

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_RedrawPage.svg
use the page icon instead of the rounded rectangle.
use the refresh icon from main GUI here,

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_RichTextAnnotation.svg
blue on dark grey has too little contrast. You can check contrast in greyscale view in Inkscape too

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_SectionView.svg
maybe add a part which is cut here to be more clear. otherwise this could also be a leaderline or something else

2024-06-22 08:22 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_SpreadsheetView.svg
the crease on the page should be at the bottom right as in your other icons to be consistent

2024-06-22 09:50 UTC, obelisk79 commented
This PR has become a nightmare to follow.

2024-06-22 09:52 UTC, maxwxyz commented
> This PR has become a nightmare to follow.

yes we tried without success to discuss the icons on Discord before committing but as you see some "fixes" made other stuff worse again.

2024-06-22 09:54 UTC, obelisk79 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Dimension_Pointer.svg
I didn't like how this deviates from the style from the equivalent icon in sketcher which we revised several months ago. The use of the gray seems like a poor approach for the cross hair and reduces contrast with the added stroke.

2024-06-22 12:44 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Dimension_Pointer.svg
You were also present in the relevant discussion. This change resolves the related issue. I'm going to increase the contrast a little more. The solution in Sketcher is different. This will do the trick until a bigger change is made.

2024-06-22 12:52 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionChangeLineAttributes.svg
This is more precise, explains the topic better and is more relevant to technical drawing. It is boring to be asked the same questions every time after the 4-5 explanations I have given in the past. Your request is not correct. But I'll do it anyway. Because I see that my opinion doesn't matter much.

2024-06-22 13:12 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionExtendLine.svg
However, this is the most visible

2024-06-22 13:16 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionHoleCircle.svg
![400px-TechDraw_ExtensionHoleCircleExample](https://github.com/FreeCAD/FreeCAD/assets/39885728/899e8a43-73ac-40e3-9bac-f8bf5197ef93)
The picture given as an example is like this. There is not much to do for the centerlines inside, they look pointless if they are made thicker. But maybe I can use a more intermediate color.

2024-06-22 13:23 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionShortenLine.svg
However, this is the most visible

2024-06-22 13:27 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionVertexAtIntersection.svg
Because it has to be that way. It's also the same size as a regular vertex insert.

2024-06-22 13:34 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_RadiusDimension.svg
Highlighting is being done. When highlighting other parts, it fills completely.

2024-06-22 13:57 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ActiveView.svg
Yes, Probably

2024-06-22 13:59 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_AddOffsetVertex.svg
This is about adding vertex. That's why the vertices are larger.

2024-06-22 14:00 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ArchView.svg
Isn't its new name BIM?

2024-06-22 14:02 UTC, obelisk79 commented
At this point my frustration level with these changes is high. There are many deviations from the established artwork guidelines and the constant pushback on them from the author is exasperating. 

I try not to engage too much with icons because I do not like the guidelines as they exist today. However until replaced, they must be adhered to.

2024-06-22 14:04 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ComplexSection.svg
Approximately the same as the old icon. Only unnecessary 3D objects were removed.

2024-06-22 14:15 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_FaceDecor.svg
Yes, it could be, but the existing icon is already complicated and adding something would confuse it even more.

2024-06-22 14:23 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_GeometricHatch.svg
Yes, because they are both hatches. But someone does it with a pat file. At first the "significant difference" in the icons was confusing.

2024-06-22 14:30 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageTemplate.svg
So I don't have an idea that would make it extraordinarily clear what this symbol does. That's why I kept the previous icon. At least there is familiarity.

2024-06-22 14:47 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLockUnlockView.svg
I think it's the opposite, but like I said, my opinion doesn't matter.

2024-06-22 14:56 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_DecorateLine.svg
When you use the tool, a panel opens and you select the line from there. That rectangle shows that panel.

2024-06-22 14:58 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_FaceDecor.svg
It wasn't there before, I just fixed some problems with the icon.

2024-06-22 15:00 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_LeaderLine.svg
![TechDraw_LeaderLine_sample](https://github.com/FreeCAD/FreeCAD/assets/39885728/835c5be5-43ba-4ec5-9cb3-0d8fadf07398)
The sample picture is like this.

2024-06-22 15:01 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageTemplate.svg
I don't have a great idea for this, this icon is a retouched version of the old icon. It wasn't redone.

2024-06-22 15:05 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_SectionView.svg
In other programs, there are only lines like this.

2024-06-22 15:25 UTC, Reqrefusion commented
Due to the problems on GitHub, I did not answer all the questions one by one. However, I believe I have made the appropriate changes regarding all of them. It is clear that my "infuriating" attitude makes the existing icons 10 times more suitable for the guide. If you say the old icons guide is more suitable, I respect that.

Little steps at a time. I'm now taking PR out of drafting. I don't think I can overcome the disappointments, but I'm sure I'll be less disappointing than the old icons.

2024-06-22 15:34 UTC, Reqrefusion commented
I apologize in advance to everyone I have upset or hurt while doing this work. My goal has never been to disturb people or upset them. Even if that was their goal. I would like to thank everyone who wants to help with the study. This study will probably never be accepted, considering all the debate and the magnitude of the study. And it won't do any good. The changes I make and the ideas put forward will always remain in the air. Because the nature of this study shows this. Of course, this will not happen directly, this process will work somehow as long as I stand in charge. I hope we get a happy ending. No matter what, thank you everyone.

2024-06-23 17:26 UTC, Reqrefusion commented
Github went crazy, so I made a split version of this work. It was divided into 24 different parts. It looks like spam, but it's definitely not. I think I'll close this PR too. However, since I find it more logical to replace them all at once, it will remain open as long as there is no problem.

2024-06-24 16:54 UTC, closed without merging

2024-06-24 17:55 UTC, maxwxyz commented
please add the open comments to the new icons so we don't loose them.

2024-06-24 18:32 UTC, Reqrefusion commented
> please add the open comments to the new icons so we don't loose them.

I had to do this because Github went crazy. Unfortunately I can barely even see the comments.