[Icons]Core Icon Revision
FreeCAD/FreeCAD pull request #14154
Opened 2024-05-19 19:51 UTC by Reqrefusion

#13840

2024-05-20 16:41 UTC, maxwxyz commented
IMO the wireframe and hidden line icon is still too similar.
Maybe the hidden line icon should indicate the triangulation?

2024-05-20 17:19 UTC, Reqrefusion commented
> IMO the wireframe and hidden line icon is still too similar. Maybe the hidden line icon should indicate the triangulation?

It probably mixes it up more. I think changing the perfect made it much, much easier to understand. Also I don't understand this idea. Also, I looked at other programs and it usually happens like this in all of them.

2024-05-20 18:24 UTC, maxwxyz commented
So you say this makes it easier to understand but you don't understand it? The hidden lines display the triangulated state as the geometry is rendered with Coin3D. IMO not very useful for working with solids but it's the great for meshes.

2024-05-20 19:20 UTC, Reqrefusion commented
> So you say this makes it easier to understand but you don't understand it? The hidden lines display the triangulated state as the geometry is rendered with Coin3D. IMO not very useful for working with solids but it's the great for meshes.

Ok I won't lie. I never looked at this view because I thought it was similar to other CAD programs. Which I don't normally use. I've never used mesh or anything like that. Now I kneel before the greatness of FreeCad. Indeed, this appearance has turned into something useful that can be used.

2024-05-22 15:42 UTC, maxwxyz commented
I like it now. Thanks.
Please remove src/Gui/Icons/edge-selection.svg this icon from the PR as this will be deleted, otherwise this will get conflicts.
Then please squash your commits.

2024-05-25 12:42 UTC, Reqrefusion commented
Done, ready to merge.

2024-05-26 07:20 UTC, maxwxyz requested changes
The resizing broke several alignments to the pixel grid so the smaller icons appear blurry. 
I've attached some screenshots to the before/after. As mentioned, the elements and strokes should be aligned to the pixel grid to prevent aliasing and scale better.
In Inkscape you can view the grid under View -> Page grid.

src/Gui/Icons/accessories-text-editor.svg this icon is a good example how it should be, as everything is aligned.

@kadet1090 @obelisk79 FYI

2024-05-26 07:20 UTC, maxwxyz commented on src/Gui/Icons/button_add_all.svg
The lines and stroke widths are not aligned with the pixel grid, that's why it looks blurred 
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/0a54fad8-11f7-4aed-9a96-03a70623653c)

2024-05-26 07:20 UTC, maxwxyz commented on src/Gui/Icons/accessories-calculator.svg
the elements in this icon are not aligned to the pixel grid and that is the reason why it appears blurry. You can view the grid under View -> Page grid.
All elements and stroke widths should be aligned.

2024-05-26 07:20 UTC, maxwxyz commented on src/Gui/Icons/camera-photo.svg
same with this icon: 
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/cf544980-16d0-4c83-9e51-1c1b4f148ebc)

2024-05-26 07:20 UTC, maxwxyz commented on src/Gui/Icons/umf-measurement.svg
also this one is not aligned but the original wasn't too. Shall I do a version of it?

2024-05-26 07:20 UTC, maxwxyz commented on src/Gui/Icons/debug-marker.svg
Also not aligned:

original, sharp: 
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/7dbf25fc-5d5f-4c8f-975a-7e161f52cf0e)

your version, blurry:
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/293225ed-3e6d-4841-b522-b6e019bfe67b)

2024-05-26 07:20 UTC, maxwxyz commented on src/Gui/Icons/application-exit.svg
There is a gap, it seems like your paths are angled:
![image](https://github.com/FreeCAD/FreeCAD/assets/6246609/65c24bec-0c82-49e6-b640-641e2bfe9806)

Also the icon is not aligned to the pixel grid.

2024-05-26 08:00 UTC, kadet1090 commented
Yes, pixel alignment is crucial for the icons to render properly and be sharp so it must be fixed before merging.

2024-05-26 10:29 UTC, Reqrefusion commented on src/Gui/Icons/accessories-calculator.svg
Corrected.

2024-05-26 10:29 UTC, Reqrefusion commented on src/Gui/Icons/camera-photo.svg
Corrected.

2024-05-26 10:32 UTC, Reqrefusion commented on src/Gui/Icons/umf-measurement.svg
An icon that contains too many small details will break whether we want it or not. I still made corrections for the outer edges. An icon that contains too many small details will break whether we want it or not. I still made corrections for the outer edges. Besides, it was already broken before, and this is an obvious fix. Even being perfectly centered is a big plus. Icon alignment comes before pixel alignment.

2024-05-26 10:33 UTC, Reqrefusion commented on src/Gui/Icons/button_add_all.svg
Corrected

2024-05-26 10:33 UTC, Reqrefusion commented on src/Gui/Icons/debug-marker.svg
Corrected

2024-05-26 10:33 UTC, Reqrefusion commented on src/Gui/Icons/application-exit.svg
Corrected

2024-05-26 10:35 UTC, maxwxyz commented on src/Gui/Icons/umf-measurement.svg
perfectly centered is not always preferred, some things must be aligned optically.
Best demo is a triangle / play button: when it's aligned perfectly centered it looks too far to the left.

2024-05-26 10:45 UTC, Reqrefusion commented on src/Gui/Icons/umf-measurement.svg
It is absolutely necessary for the margins to be the same, this is what I mean. The distance from left to right is the same there too. I don't extend it.

2024-05-28 13:00 UTC, Reqrefusion commented on src/Gui/Icons/utilities-terminal.svg
Yes, I looked at all mentioned.

2024-06-02 12:42 UTC, Reqrefusion commented
Done, ready to merge.

2024-06-07 02:54 UTC, chennes commented
@maxwxyz could you please approve (or not, as the case may be!) the change you requested?

2024-06-07 06:53 UTC, maxwxyz commented
@kadet1090 @obelisk79 could you check as well and comment?

2024-06-10 16:32 UTC, chennes commented
@obelisk79 if you would like to comment please do so, otherwise we will merge next week.

2024-06-11 02:00 UTC, obelisk79 requested changes

2024-06-11 08:58 UTC, Reqrefusion commented
![dagViewVisible](https://github.com/FreeCAD/FreeCAD/assets/39885728/95097494-43ea-407d-8629-b14b88f89311)
I don't think this eye looks disproportionate. But I still revert the change.

2024-06-11 17:55 UTC, maxwxyz commented
The stepped line effect on the view icons is still there. Could you use the old perspective for them?

2024-06-11 18:17 UTC, Reqrefusion commented
> The stepped line effect on the view icons is still there. Could you use the old perspective for them?

I don't understand what you mean by the stepping line effect.

2024-06-11 18:21 UTC, maxwxyz commented
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/56ac5310-ad83-439e-92f2-5eb5d63d8b96)
This is on a HiDPI screen so a normal screen would look worse. IMO just keep the old ones and properly adjust sizing if necessary.

2024-06-11 18:33 UTC, maxwxyz commented
Plus the perspective is off on almost every line, so maybe it's best to keep the old ones 
![grafik](https://github.com/FreeCAD/FreeCAD/assets/6246609/1914dbc6-d744-4b36-a2d7-ae475a86001d)

2024-06-11 19:07 UTC, Reqrefusion commented
![DrawStyleAsIs](https://github.com/FreeCAD/FreeCAD/assets/39885728/0d014408-cab1-4f5c-898f-6ec51995c77f)
![DrawStyleFlatLines](https://github.com/FreeCAD/FreeCAD/assets/39885728/3984600e-027f-49ad-a13f-84cc5cdfead0)
![DrawStyleHiddenLine](https://github.com/FreeCAD/FreeCAD/assets/39885728/ec3355f4-9976-444c-b03a-7dc912bfa0c1)
![DrawStyleNoShading](https://github.com/FreeCAD/FreeCAD/assets/39885728/8a4cc39d-bdcf-4b85-bd88-d20d193e0f17)
![DrawStylePoints](https://github.com/FreeCAD/FreeCAD/assets/39885728/faf53929-0b49-4472-896c-0c237e29023f)
![DrawStyleShaded](https://github.com/FreeCAD/FreeCAD/assets/39885728/f962829f-c558-4bfb-92bd-0ec9323923d6)
![DrawStyleWireFrame](https://github.com/FreeCAD/FreeCAD/assets/39885728/9f741ced-289a-4a44-b5f2-876f306ec1a3)
I would definitely try at another time, but I'm leaving the group to return later. A change of perspective is definitely necessary. Step line effect is easy to fix, but I don't have time for the other one yet.

2024-06-16 23:33 UTC, Reqrefusion commented
If there is no objection, it means there is no problem. I have dealt with all objections. Please merge if you don't see a problem.

2024-06-17 16:28 UTC, chennes commented
@maxwxyz can you give a final look?

2024-06-17 18:59 UTC, maxwxyz commented
@chennes you can merge this

2024-06-24 15:54 UTC, merged