[Icons]Revision of TechDraw Icons(chain)
FreeCAD/FreeCAD pull request #14876
Opened 2024-06-23 16:42 UTC by Reqrefusion

#14145

2024-06-25 22:00 UTC, kadet1090 requested changes
Looks fine but needs a bit of technical work with pixel alignment.

For lines to look crisp on as many sizes as possible you must align paths to pixel grid. In order to achieve best possible results try to aim for even pixel values and use odd pixel coordinates only when it is necessary due to for example ensuring even spacing.

2024-06-26 12:16 UTC, Reqrefusion commented
It's interesting that you say this because, except for oblique, the other icons are pixel perfect. They are perfectly aligned. Oblique is not perfectly aligned because doing so reduces its similarity to other icons. However, it is also quite understandable, especially in 24x24.

2024-06-26 12:58 UTC, kadet1090 approved these changes
Oblique is impossible to align except for points. In case of other icons one of lines is not aligned correctly to even pixels but it should not matter much. In that case however I was fooled by github as it does not render icons crisply which for ones that I checked before indicated pixel alignment problems. This time I checked with inkscape - it is fine.

2024-07-01 10:59 UTC, maxwxyz approved these changes

2024-07-01 13:13 UTC, merged