[Icons]Revision of TechDraw Icons(Char)
FreeCAD/FreeCAD pull request #14878
Opened 2024-06-23 16:46 UTC by Reqrefusion

#14145

2024-06-26 16:45 UTC, Reqrefusion commented
[ExtensionCustomizeFormat.svg](https://github.com/FreeCAD/FreeCAD/pull/14878/files#diff-064afd363a693b57c281aea41ffbffc3b52a05c5ff9cece57950d691eb636c26) It contains all the signs. It doesn't just contain tolerance signs. This more inclusive icon was chosen.

2024-06-26 18:38 UTC, kadet1090 requested changes

2024-06-26 18:38 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
![image](https://github.com/FreeCAD/FreeCAD/assets/747404/08b67e94-8c0f-4520-a36f-429f9a0f08d4)

`m` needs more yellow area or better pixel alignment.  Annotation line should be thicker - please make it as thick as arrows in other dimensioning tools.

My suggestion is to remove the annotation line altogether and leave only `m2` symbol - it should be obvious enough given it is placed with other dimensioning tools. Then the other icon ("Extension" one) could be done like this (to look uniform with ExtensionArLengthAnnotation) with possibly additional Σ symbol to indicate possibility of summing up multiple areas.

2024-06-26 18:38 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
Annotation line should be thicker - please make it as thick as arrows in other dimensioning tools. The annotation line should be same thickness as the arc.

2024-06-26 18:38 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
This icon is visually out of place and also is not readable.
![image](https://github.com/FreeCAD/FreeCAD/assets/747404/f1845080-25b7-479f-a049-2b84f7441d62)

See other m2 icon for my suggestion

2024-06-26 18:38 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionRemovePrefixChar.svg
Hard to read in dark themes: 
![image](https://github.com/FreeCAD/FreeCAD/assets/747404/9f1363b1-662c-4a24-b9d3-bd6accc93613)

Please increase thickness to ensure proper readability. I'd leave only crossed out omega symbol.

2024-06-26 18:38 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionCustomizeFormat.svg
It'd be nice to add here highlight color as it is present in most icons in FreeCAD

2024-06-27 13:26 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionRemovePrefixChar.svg
That was my first thought, but it's very misleading. It only deletes the symbols in front. Not all symbols. I'm going to try underline instead of dotted square here.

2024-06-27 19:34 UTC, kadet1090 approved these changes

2024-06-27 19:34 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
I still think that this one stands out a bit:
![image](https://github.com/FreeCAD/FreeCAD/assets/747404/5e8cbf0b-132a-4358-9c5a-e522ce739955)

However it is readable and different so, I'm giving it a pass.

2024-06-27 21:27 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
Confusion stemming from Tool itself. I can't think of an option that would both maximize readability and make the difference clearer. At least that's what it comes down to. I'm curious about the fate of this tool in the next release.

2024-07-01 10:57 UTC, maxwxyz approved these changes
Minor changes needed

2024-07-01 10:57 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
Just a style choice but IMO this comic sans style font looks like a cartoon, maybe just use the default Open Sans font used on most icons or OSIfont (TD).

2024-07-01 10:57 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
the arc also has an odd shape.
https://github.com/FreeCAD/FreeCAD/issues/13544#issuecomment-2074217298
or use this character:
`◠`

2024-07-01 10:57 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionAreaAnnotation.svg
same as above + the font.

2024-07-01 17:56 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_AreaDimension.svg
I did not use a font here. Since it didn't look the way I wanted, I drew it myself. Drawings made in this way can be read much more easily compared to conversions made from fonts.

2024-07-01 19:16 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionArcLengthAnnotation.svg
Shepe corrected.

2024-07-01 19:31 UTC, Reqrefusion commented
Instead of conversion from fonts, the letters are drawn accordingly. This was done to increase readability, and it actually does. So there is no problem with fonts. Apart from this, the use of fonts really reduces readability. Because I can easily pixel correct my own drawings, which I did for all of them. This made them more readable.

2024-07-01 19:58 UTC, Reqrefusion commented
@chennes It can be merged. It needs to be merged today.

2024-07-02 04:01 UTC, merged