[Icons]Revision of TechDraw Icons(blue)
FreeCAD/FreeCAD pull request #14874
Opened 2024-06-23 16:26 UTC by Reqrefusion

#14145

2024-06-25 22:06 UTC, kadet1090 requested changes

2024-06-25 22:06 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_LeaderLine.svg
@WandererFan Is this icon ok? This is quite a big change.

2024-06-25 22:06 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLineParallel.svg
Here line that was dashed out is now presented as solid. Visually it looks OK and is readable in the UI, but I'm not sure if functionally it is fine - @WandererFan your opinion here would be very useful

2024-06-25 22:06 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Line2Points.svg
Please make sure that vertices are presented consistently with PR about vertex icons. I don't think that changing colors here is OK - white is used in the sketcher for presenting lines, probably would be good to stay consistent. It also won't be visible on dark themes.

2024-06-25 22:06 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Midpoints.svg
Concept is fine, but the same points like for `Line2Points.svg` applies - line could be white and should be a bit thicker. Please reuse line style that can be found in sketcher.

2024-06-25 22:06 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_Quadrants.svg
Same thing - please stay with the line style from sketcher (which was used in previous icon) and ensure that vertices are presented always the same (design them once and copy)

2024-06-26 16:27 UTC, kadet1090 approved these changes

2024-07-01 11:00 UTC, maxwxyz approved these changes

2024-07-01 16:04 UTC, merged