[Icons]Revision of TechDraw Icons(Hatch)
FreeCAD/FreeCAD pull request #14882
Opened 2024-06-23 16:54 UTC by Reqrefusion

#14145

2024-06-25 21:56 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_GeometricHatch.svg
@WandererFan Is this icon ok?

2024-07-01 10:51 UTC, maxwxyz requested changes
One minor change

2024-07-01 10:51 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_GeometricHatch.svg
the .pat is not visible in the toolbar for me.
What about using a different hatch style than the other icon and just write PAT in the part like in the export as SVG icon?

2024-07-01 14:47 UTC, kadet1090 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_GeometricHatch.svg
pat in the shape should work fine and as it has known background we can make it strokeless

2024-07-01 20:04 UTC, Reqrefusion commented
@chennes It can be merged. It needs to be merged today.

2024-07-01 20:05 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_GeometricHatch.svg
I followed Kadet's suggestion. I think it is a development that the important thing is to point out that it is different. I don't understand anything in the old icon.

2024-07-02 04:01 UTC, merged