[Icons]Revision of TechDraw Icons(lock)
FreeCAD/FreeCAD pull request #14886
Opened 2024-06-23 17:00 UTC by Reqrefusion

#14145

2024-06-26 17:06 UTC, Reqrefusion commented
The lock icons here are clearly different from Skecher because their functions are completely different and therefore they are displayed in different ways.

2024-06-26 18:18 UTC, kadet1090 approved these changes

2024-07-01 10:48 UTC, maxwxyz requested changes
Just one change.

2024-07-01 10:48 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_ExtensionLockUnlockView.svg
Just delete the blue stroke on the keyholes and it's good.

2024-07-01 19:40 UTC, maxwxyz approved these changes

2024-07-01 19:40 UTC, maxwxyz commented
@chennes can be merged

2024-07-02 03:59 UTC, merged