[Icons]Revision of TechDraw Icons(others)
FreeCAD/FreeCAD pull request #14887
Opened 2024-06-23 17:03 UTC by Reqrefusion

I can't include him in a specific group. Or icons for which I cannot find a group name.
#14145

2024-06-24 16:29 UTC, PaddleStroke commented
TechDraw_RefError.svg

Core already has a red cancel cross. TD should use it rather than implementing its own.

2024-06-24 18:59 UTC, maxwxyz commented
@Reqrefusion not just save the same icon as a duplicate, it should use the same icon (path)

2024-06-24 19:12 UTC, furgo16 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ArchView.svg
If this icon changes from "A" to "B" https://wiki.freecad.org/Arch_SectionPlane should be changed too for consistency. But before doing that extra work, what is the motivation for the change?

2024-06-24 19:14 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ArchView.svg
No that was just a change by mistake. He still needs to copy the old comments to the new PRs otherwise it will be all from the beginning again.

2024-06-24 19:17 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ArchView.svg
This is probably a misunderstanding due to the name Arch reverting to the name Bim. If there is no such thing, there is no problem in returning it.

2024-06-25 18:36 UTC, Reqrefusion commented
> @Reqrefusion not just save the same icon as a duplicate, it should use the same icon (path)

Another PR can also be taken care of.

2024-06-25 21:51 UTC, kadet1090 approved these changes

2024-06-28 11:28 UTC, furgo16 commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ExportPageDXF.svg
Some of the icons (this one is just an example) replace the darker tone outline (or part of the icon) by a lighter dark tone.

I'm no sure if this is particular to my setup, but the lighter tone seems to make the icons less crisp (fuzzier) at the size they are shown in the toolbars. I just thought I'd mention it for the record.

2024-06-28 12:06 UTC, Reqrefusion commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_ExportPageDXF.svg
This is because the darkest and lightest shades of the color are used instead of black or white. This provides relief for both light and dark themes. Because black and white disappear completely in these themes. In the icon here, the black parts have been replaced with the darkest shade of grey. Yes, this probably reduced the noticeability of the icon. And this is something that is desired. Because all icons must be equally noticeable, and black lines make this icon stand out from others, and we do not want this.

2024-07-01 10:48 UTC, maxwxyz requested changes
Please change the 2 mentions, otherwise good.

2024-07-01 10:48 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageDefault.svg
could we use a page with frame but without the views in it? This just inserts a new blank page and could be confused with add new view (which also has a not ideal icon). So just delete the 3 views of the part please.

2024-07-01 10:48 UTC, maxwxyz commented on src/Mod/TechDraw/Gui/Resources/icons/actions/TechDraw_PageTemplate.svg
IMO a better icon is to use the open file icon and replace the blank document with a blank page with frame as currently it is implicating that it creates a new folder or group

2024-07-01 19:41 UTC, maxwxyz approved these changes
@chennes can be merged

2024-07-01 19:59 UTC, Reqrefusion commented
@chennes It can be merged. It needs to be merged today.

2024-07-02 03:59 UTC, merged