[Icons]Revision of TechDraw Icons(Dimensions)
FreeCAD/FreeCAD pull request #14881
Opened 2024-06-23 16:53 UTC by Reqrefusion

#14145

2024-06-25 21:59 UTC, kadet1090 requested changes
Please ensure that arrows have consistent size and stroke as depending on icon we can see different size of arrow heads. Please ensure proper pixel grid alignment in all icons.

2024-06-27 19:25 UTC, kadet1090 approved these changes

2024-06-27 19:40 UTC, kadet1090 approved these changes

2024-07-01 10:52 UTC, maxwxyz approved these changes

2024-07-01 16:07 UTC, merged