[Icons]Revision of TechDraw Icons(Line lengths)
FreeCAD/FreeCAD pull request #14884
Opened 2024-06-23 16:57 UTC by Reqrefusion

#14145

2024-06-25 21:54 UTC, kadet1090 requested changes
Proportions of the arrows seems very odd, they seem scaled up in the vertical direction. Can we do them slightly smaller vertically?

2024-06-26 17:04 UTC, Reqrefusion commented
I think I found the right one this time.

2024-06-26 17:44 UTC, kadet1090 approved these changes

2024-06-26 18:25 UTC, kadet1090 approved these changes

2024-07-01 10:50 UTC, maxwxyz approved these changes

2024-07-01 16:08 UTC, merged