Added a filename sample extension in Std_Export function
FreeCAD/FreeCAD pull request #15581
Opened 2024-07-23 12:41 UTC by DeniseBryson

This avoids FileDialog::getSaveFileName() abbreviating the actual filename if no extension is given. Now exporting for the first and the second time results in the same behaviour.

This problem was described in #15203.

2024-07-31 09:57 UTC, yorikvanhavre requested changes
I fear this could make some wrong moves happen. For ex. someone would manually type "myfile.FCStd" as a filename - with this change, it will internally become "myfile.FCStd.xxx" then the last one truncated and replaced, so the final filename will become "myFile.FCStd.FCStd".

I would say it needs more tests, for ex. add .xxx only if the file does not end with .FCStd (there might be other cases that I can't think of right now that need handling)

2024-08-02 10:05 UTC, DeniseBryson commented
Thanks for the comment!

If you manually change the filename in the "File dialog" the chosen ending is always appended if the last ending is not the same as the chosen one. This appended or recognized ending is safed in lastname.suffix().  So in your example there is no change in behavior.

There is the case, that the label of the part to be exported already has the ending in itself. In this case this ending will not be cut and also added a second time within the file dialog. You would have to delete one ending manually and save it. The second time saving works fine.
In the case the ending is already in the part label, this solution makes the name handling a little more complicated. But including the export file ending in the label does not seem to be a normal use case, no?

2024-08-05 15:53 UTC, chennes commented
@FEA-eng, @adrianinsaval, and @pieterhijma are going to give this a test as well. Thanks everyone!

2024-08-05 18:46 UTC, FEA-eng commented
Looks good. I can confirm that it fixes the issue. I checked some more convoluted names mentioned here and in the issue discussion and it still works well. Maybe there are some very specific combinations that we haven't thought of but they should be unlikely enough to happen. From what I understand, this doesn't affect the File --> Save functionality but only File --> Export, right?

2024-08-08 23:48 UTC, adrianinsaval commented
Also seems to work good for me, at the very least it is an improvement over the current state. I even tried doing stuff like naming the object in freecad Body.3mf and trying to export, the name was still displayed and saved as Body.3mf.3mf even after successive attempts.

2024-08-09 00:07 UTC, adrianinsaval commented
I do wonder if this shouldn't be fixed in getSaveFileName itself

2024-08-09 10:28 UTC, pieterhijma commented
@DeniseBryson, thanks for your PR and thanks for explaining the problem and leading the way. 

I basically share the same objection as @yorikvanhavre expressed in the merge meeting that the code gets a dummy string without any meaning trying to solve a problem. I also agree with @adrianinsaval that we should perhaps look for a more fundamental solution. Based on your code, I could better understand what was going wrong and I will submit an alternative solution that has a more fundamental solution.

@DeniseBryson, it would be great if you could check that out and share your opinion.

2024-08-09 10:35 UTC, pieterhijma commented
@DeniseBryson, @chennes, @yorikvanhavre, @FEA-eng, @adrianinsaval, an alternative solution is in https://github.com/FreeCAD/FreeCAD/pull/15838. It is based on the same root branch, making it relatively easy to switch between the two implementations.

2024-08-12 15:50 UTC, chennes commented
Closing in favor of #15838 -- but thanks again for the PR, @DeniseBryson.

2024-08-12 15:50 UTC, closed without merging

2024-08-13 04:23 UTC, DeniseBryson commented
@pieterhijma I think your solution makes more sense. I did not know that it is so easy to get all possible extensions for one context. With this list it makes sense to just search the filename for those.

I am still wondering a little how the behavior described by @adrianinsaval during the second saving can be omitted. 
Due to this behavior and your solution I feel like the part of the code handling previous used extensions should entirely move to  FileDialog.cpp, but I am not sure how to do that in a nice way at the moment.

anyway thanks for letting me know about your solution! I'll close this PR