Toponaming add feature refine class
FreeCAD/FreeCAD pull request #15690
Opened 2024-07-30 12:36 UTC by bgbsww

Cannot be completed until FeatureTransform is TNP aware, which is an oversight needing correction.

2024-08-26 08:02 UTC, maxwxyz commented
@bgbsww the mentioned PR was merged, is anything else needed for this PR to be ready for review?

2024-08-26 14:12 UTC, bgbsww commented
I just need to rebase and clean.  I'll do that.  No functionality changes here, just a code cleaning refactor to remove duplication.

2024-09-14 15:56 UTC, maxwxyz commented
is this ready for review now?

2024-09-14 16:10 UTC, bgbsww commented
Yes.  Especially if someone can explain those weird CI build failures to me.  The only reason this stays in draft is the CI won't pass, and I can't understand the behavior which I cannot replicate locally.

2024-11-17 19:29 UTC, maxwxyz commented
@chennes this PR has some conflicts

2024-11-23 07:58 UTC, maxwxyz commented
@chennes still :)

2024-11-30 20:47 UTC, maxwxyz commented
@chennes ping

2024-12-05 07:12 UTC, maxwxyz commented
@chennes 🥲

2024-12-08 19:33 UTC, maxwxyz commented
waiting on @chennes

2025-01-08 07:46 UTC, maxwxyz commented
bump

2025-01-18 09:23 UTC, maxwxyz commented
@chennes are you picking this up or should we close this PR?

2025-01-24 16:07 UTC, maxwxyz commented
CI failed

2025-01-25 11:08 UTC, FlachyJoe commented
This may be the good place to include @wwmayer's remarks: https://github.com/FreeCAD/FreeCAD/pull/17008#pullrequestreview-2473612370

2025-01-25 11:30 UTC, chennes commented
Thanks for linking, I had not seen that comment. Is the 'onlyHasToRefine()' method here the one that you added in response to that comment?

2025-01-25 14:24 UTC, FlachyJoe commented
No I didn't do anything more, the PR was merged and this improvement was stuck in my todolist.
wwmayer idea is to combine `onlyHasToRefine` and the two next lines
```cpp
        TopoShape result = refineShapeIfActive(rawShape);
        Shape.setValue(result);
```

something like
```cpp
bool FeatureRefine::onlyHaveRefined(){
    if (onlyHasToRefine()){
        TopoShape result = refineShapeIfActive(rawShape);
        Shape.setValue(result);
        return true;
    }
    return false;
}
```
but it can certainly be clearer by including `onlyHasToRefine` and maybe `refineShapeIfActive` if it's not used elsewhere.

2025-02-03 17:25 UTC, chennes commented
I'll take a look at adding the suggested method.

2025-02-10 17:14 UTC, kadet1090 requested changes

2025-02-10 17:14 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +    if( ! Refine.isTouched()){
```suggestion
    if(!Refine.isTouched()){
```

2025-02-10 17:14 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +    if (onlyHasToRefine()){
```suggestion
    if (onlyHasToRefine()) {
```

2025-02-10 17:14 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +                Base::Console().Warning((std::string("Refine failed: ") + err.GetMessageString()).c_str());
Warning does not support formatting patterns by default? This should use fmt or something like that.

2025-02-10 17:14 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +    if (this->Refine.getValue()) {
I'd flip that to use early-exit.

2025-02-10 17:14 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeatureRefine.h
> +    bool onlyHaveRefined();
I've got a bit of a problem understanding difference between these two. Can we at least make comment above them to explain difference between them? Maybe then we will be able to come up with better name? Even looking at code I have problems understanding the intent.

2025-02-12 03:26 UTC, chennes commented on src/Mod/PartDesign/App/FeatureRefine.h
> +    bool onlyHaveRefined();
I've added a comment, but still couldn't come up with a better name. Basically anything sounds sort of ridiculous.

2025-02-12 03:26 UTC, chennes commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +    if (this->Refine.getValue()) {
Done.

2025-02-12 03:26 UTC, chennes commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +                Base::Console().Warning((std::string("Refine failed: ") + err.GetMessageString()).c_str());
Switched to fmt::format

2025-02-12 03:27 UTC, chennes commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +    if (onlyHasToRefine()){
Done.

2025-02-12 03:27 UTC, chennes commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +    if( ! Refine.isTouched()){
Done.

2025-02-12 10:57 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeatureRefine.h
> +    bool onlyHaveRefined();
I think that my biggest problem with the name is that first method prefixed with `only` is de facto predicate without side effects and other one is action with side effects. I know that there is `const` specifier that should tell us about side-effects (or lack of them), but `const` does not really tell us much as stuff inside properties can still be changed... 

Maybe something like `onlyHasToRefine` and `tryRefineOnly`? `try` suggest that this might fail (i.e. only refine is insufficient) and that it can have side effects. I know that `try` is often used to wrap methods that my throw exception but in that case I cannot think of better solution.

2025-02-16 08:57 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeatureRefine.h
> +    bool onlyHaveRefined();
@chennes ^ ping? Rest of PR looks good

2025-02-16 09:26 UTC, FlachyJoe requested changes

2025-02-16 09:26 UTC, FlachyJoe commented on src/Mod/PartDesign/App/FeatureRefine.cpp
> +
```suggestion
bool FeatureRefine::onlyHaveRefined()
{
    if (!Refine.isTouched()) {
        return false;
    }
    if (rawShape.isNull()) {
        return false;
    }
    std::vector<App::Property*> propList;
    getPropertyList(propList);
    for (auto prop : propList) {
        if (prop != &Refine
            /*&& prop != &SuppressedShape*/
            && prop->isTouched()) {
            return false;
        }
    }
    TopoShape result = refineShapeIfActive(rawShape);
    Shape.setValue(result);
    return true;
}
```

`onlyHasToRefine` is not used elsewhere so we can concatenate.

2025-02-16 19:52 UTC, FlachyJoe commented on src/Mod/PartDesign/App/FeatureRefine.h
> +    bool onlyHasToRefine() const;
```suggestion
```

2025-02-16 20:02 UTC, kadet1090 approved these changes

2025-02-17 16:28 UTC, merged