Material: materials-editor.ui not installed in the correct location
FreeCAD/FreeCAD pull request #15714
Opened 2024-07-31 21:33 UTC by nickoe

I tried to build freecad-git from ArchLinux AUR and noticed materials-editor.ui not installed in the correct location.

This appears to be caused by a type caused by the addition of the ui file in commit 810f34ea11dca01ee833e7c625f87feac39ae2c1

Fixes #15713

2024-08-01 00:41 UTC, davesrocketshop requested changes
THIS. WILL. BREAK. BUILDS.

You have obviously only tested this on your platform. It will not work on most others,

See also #15565

2024-08-01 05:57 UTC, nickoe commented
@davesrocketshop I only havebon platform to test on.  I am not sure I can see how it breaks builds. What platform are you on?

Can someone approve to run the workflows to test it on msvc and ubuntu?

2024-08-01 15:16 UTC, nickoe commented
@davesrocketshop How do I start the legacy editor? I can't find any reference to a "legacy gui", I also looked in https://wiki.freecad.org/Compile_on_Linux

As it stands now, the build is broken anyhow, as the ui file isnplaced in a place that I doubt is in the search path.

2024-08-05 14:21 UTC, adrianinsaval commented
how should one test if this ui file is working?

2024-08-07 22:07 UTC, nickoe commented
@davesrocketshop  Could you please re-review? I think you might be confusing my patch with @adrianinsaval 's first attempt here https://github.com/FreeCAD/FreeCAD/commit/b9a2735306461973cbb4520c1b53563e8849ec53 ?

2024-10-03 14:28 UTC, maxwxyz commented
@davesrocketshop should this PR be closed now?

2024-10-03 15:07 UTC, chennes commented
Yes -- we've merged a fix for this in the meantime, it should be working. Thanks, all!

2024-10-03 15:07 UTC, closed without merging