PartDesign: Introduce transparent previews
FreeCAD/FreeCAD pull request #17249
Opened 2024-10-14 20:01 UTC by kadet1090

This PR implements transparent preview feature found in LinkStage, code is loosely based on what is found in the LinkStage.

Implementation is done inside `PartDesign::Feature` using `PreviewShape` property that can be set by the feature to display the changed shape. Features are responsible for providing the PreviewShape, default implementation is based on topological data provided by the toponaming solution. This fully replaces preview that was implemented as part of `ViewProviderAddSub`.

To not copy the rendering code yet again I reused hack from LinkStage that allows ViewProviders to have private sub view providers via `SecondaryView` status. I don't think that this is a good solution and it is a subject to change. I'm thinking about creating `SoFCShape : SoSeparator` with all required nodes + helper class that will fill them based on the shape provided and arguments for deviation etc. This mechanism could then be reused for all other use cases like rendering solids, previews or rejected shapes inside the transform view provider. @wwmayer maybe you have some suggestions here?

Things to sort out:
- [ ] Color of preview should be dependent on kind of feature
- [ ] Preview is selectable and it shouldn't be
- [ ] Does not work well with first feature
- [ ] After edit view does not return to proper state
- [ ] Showing preview of the feature when hovering over feature in the tree

![image](https://github.com/user-attachments/assets/22e457b9-396f-4e62-9999-7fa28532b05b)
![image](https://github.com/user-attachments/assets/b7c359f7-77e0-4ba7-b7a6-a7c00a7f7a56)

Fixes: https://github.com/FreeCAD/FreeCAD/issues/11214

2024-10-15 06:17 UTC, maxwxyz commented
@kadet1090 as seen in https://github.com/FreeCAD/FreeCAD/issues/11214 it would be great to have a semi transparent body as well, to see the hidden edges:
![278737748-a53ecff6-04d1-4bfe-a48c-ba45f4868185](https://github.com/user-attachments/assets/ec30c339-7d76-413c-b56d-3c55387343fa)

2024-10-15 06:49 UTC, kadet1090 commented
This is another feature, this PR is already a bit large and we should not allow scope creep.

2024-10-17 05:39 UTC, maxwxyz commented
Some tools like Loft or Pipe already have a preview. Is this also overhauled to be consistent or will these look and behave different? Also the primitives (additive cube, sphere..) have such a semi-transparent preview today.

2024-10-17 07:45 UTC, kadet1090 commented
Old preview code is removed and replaced to be consistent.

2025-06-21 09:41 UTC, maxwxyz commented
Besides new preview it should be possible to preview the results (as currently)

2025-06-21 09:42 UTC, maxwxyz commented
New previews appear in the wrong location:
[previewtest.FCStd.zip](https://github.com/user-attachments/files/20846002/previewtest.FCStd.zip)


https://github.com/user-attachments/assets/b78913ae-ebd7-4570-be7b-bd5bc99a5bae

2025-06-21 09:44 UTC, maxwxyz commented
Camera moves when activating PD commands (e.g. pad and hole tool):

https://github.com/user-attachments/assets/a6d5a4f9-d919-4bbc-87d7-378d5fa830a9

2025-06-21 09:45 UTC, maxwxyz commented
Deleting the last PD feature does not make the previous feature active, so nothing is visible (even when the previous feature was the active one before)

2025-06-21 09:47 UTC, maxwxyz commented
Some tools display the actual computed result and the preview at the same time:

- [x] chamfer / fillet when changing values
- [x] pad/pocket with mode `two lengths` or `up to face` 
- [x] groove tool when adjusting angle
- [x] thickness when checking checkboxes
- [x] fillet
- [x] chamfer

https://github.com/user-attachments/assets/f4009c8b-720d-4d18-a5ca-3619bbe0480b


![grafik](https://github.com/user-attachments/assets/1abf9ff0-218a-4154-a647-beac4b9bd358)

![grafik](https://github.com/user-attachments/assets/8619faf2-c36a-461b-9716-5e8cc677b61a)

2025-06-21 09:47 UTC, maxwxyz commented
- Additive Pipe tool does not update preview when changing section modes
- Subtractive Pipe tool does not have preview at all

2025-06-21 09:48 UTC, maxwxyz commented
These tools are missing previews:
- hole
- boolean
- draft
- multitransform (crash)

2025-06-21 09:48 UTC, maxwxyz commented
Patterns have no preview for using the entire body as object to pattern

2025-06-21 09:50 UTC, maxwxyz commented
When a feature is not possible it still shows the last preview state. Like increase fillet size until the face would be removed: you can still increase the radius but preview does not change. Before PR it would not show the result if it cannot be done (also on other PD features)
I cannot add more edges than the preselection in Fillet if I increased the preview size to be to large, but even when decreasing fillet size I cannot add more edges

2025-06-21 09:56 UTC, maxwxyz commented
Selection color is currently the same as preview so when adding edges (default mode in fillet tool) it looks as if the selection is in the preview:
![grafik](https://github.com/user-attachments/assets/b8eb93c6-eb30-4cfc-850d-d60480a11604)

vs

![grafik](https://github.com/user-attachments/assets/491e52c5-f81b-40ad-82a6-8debc05bce28)

2025-06-21 11:57 UTC, maxwxyz commented on src/Gui/Inventor/So3DAnnotation.cpp
>  #include <Inventor/elements/SoCacheElement.h>
Preview is off when placement is changed (either body or feature):

https://github.com/user-attachments/assets/3b487c86-0ae6-4128-a5be-07596b42628f


https://github.com/user-attachments/assets/13d39ae0-b53d-4a2e-820b-f0c521126bb1

2025-06-21 13:32 UTC, maxwxyz commented on src/Gui/Inventor/So3DAnnotation.cpp
>  #include <Inventor/elements/SoCacheElement.h>
You should not be able to select previews, You can by clicking on them twice or by selecting the feature in the tree view:

https://github.com/user-attachments/assets/915984c8-eb79-402f-9260-2ce8bf822e7c


https://github.com/user-attachments/assets/ec965cb0-1590-4cc2-96ea-ec22a51c3b4a

2025-07-12 19:35 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
Previews do not take draw style of the object or overwrite drawstyle into account:
<img width="890" height="685" alt="grafik" src="https://github.com/user-attachments/assets/af6cfaec-25b5-4050-a0ed-2ee180af125a" />

2025-07-12 19:36 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
Pattern preview does not match the final result:

https://github.com/user-attachments/assets/5ce4aff7-f7e0-4ee2-b596-c63249a5695e

2025-07-12 19:39 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
Do we still need the update view checkbox? If unchecked there is no update on either preview or result
you could simply uncheck both checkboxes to have temporary no preview for e.g. threads.

If it has to stay, maybe move it in the preview section?


<img width="455" height="208" alt="grafik" src="https://github.com/user-attachments/assets/077bc71b-6c4b-414a-9ea9-fc50aeef3e94" />

2025-07-12 19:48 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
Real preview transforms the object and does not show the real result:

https://github.com/user-attachments/assets/e20cf788-cbd0-4387-84fe-88490b39f8d4

2025-07-12 19:51 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
Subtractive preview is not correct. Arbitrary material is shown darker but not everywhere where it is removed:

https://github.com/user-attachments/assets/fbc38d85-27fc-4f40-ac2a-47b063b53752

Even with real preview:

<img width="644" height="469" alt="Bildschirmfoto 2025-07-12 um 21 51 30" src="https://github.com/user-attachments/assets/1347bbc8-4dc1-4558-89b9-f3467e62c385" />

2025-07-12 19:58 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
The entire body becomes the preview when changing modes, e.g. to `up to face`:

https://github.com/user-attachments/assets/8da7ef28-fc37-49be-9e9b-3a58902d57be

2025-07-12 22:14 UTC, kadet1090 commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
Feature, not a bug imho - to be discussed later. I'm not sure why they should take into account as they pretty much have their own style.

2025-07-12 22:15 UTC, kadet1090 commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
I'm not sure to be honest - "Update view" is basically "Recompute automatically after changes" - so it has some utility as you can disable it for larger models to not trigger recomputes. It does not belong in the PReview section imho, but probably should be renamed simply?

2025-07-13 07:44 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
@FreeCAD/design-working-group any feedback on this?
I'm still not sure if we need it as it appears to be the same result if both new checkboxes are unchecked (you can argue you can have the latest state overlayed as preview with the additional checkbox).
If kept, renaming would be good but I also would still move it in the preview section as it recomputes either preview or result, both of which is toggled in the preview tab.

2025-07-13 09:20 UTC, MisterMakerNL commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
For Patterns it's very useful and should probably be replaced by a button, as doing a simple typo in the pattern numbers can crash Freecad. (as I experienced lately.. :) )
For simple features like extrude I am not so sure. You must be doing something really weird when you need this. 
Pipe, helix and loft features this is also very useful. I'd leave it there and change it with another PR.

2025-07-19 18:21 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
@kadet1090 this is still happening

2025-07-19 18:22 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
fixed

2025-07-19 18:24 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
fixed

2025-07-19 18:24 UTC, maxwxyz commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
It now throws a lot of errors

https://github.com/user-attachments/assets/2f126e49-f8ed-4380-8da2-c672279fa0e9

2025-07-19 20:48 UTC, kadet1090 commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
I think that it is outside of scope for that PR. That preview is actually surprisingly correct as the preview shows the same shape, that will be then used for the patterns. In that case it really is that the whole shape is regenerated:

<img width="1961" height="1061" alt="image" src="https://github.com/user-attachments/assets/41cf1250-0734-4612-9bd5-f40526301043" />

I do understand that this is stupid, but not because of this PR - it simply shows that there is an error in other place. IMHO issue for that should be filled and when the shape for patterns will be correct preview will be too.

2025-07-19 20:51 UTC, kadet1090 commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
> I'm still not sure if we need it as it appears to be the same result if both new checkboxes are unchecked (you can argue you can have the latest state overlayed as preview with the additional checkbox).
> If kept, renaming would be good but I also would still move it in the preview section as it recomputes either preview or result, both of which is toggled in the preview tab.

Fact that you don't see the result does not mean that it is not computed. It will still freeze FreeCAD while recomputing. One can argue that it does not make sense to recompute it after input if user does not see it, but I'm not so sure that there are no valid use cases for such feature. It also is not related to preview in any way.

2025-07-20 22:10 UTC, kadet1090 commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
I changed it to "Recompute on change" - let's think about it later.

2025-07-20 22:11 UTC, kadet1090 commented on src/Mod/Part/App/AppPart.cpp
>  #include "GeometryIntExtensionPy.h"
Now it still will generate warning, but more useful:

<img width="935" height="182" alt="image" src="https://github.com/user-attachments/assets/12345e5c-a442-4077-b7d8-51ddcf166983" />

2025-07-27 11:31 UTC, tritao commented on src/Mod/Part/App/AppPart.cpp
> +    Part::PreviewExtension      ::init();
Nit: this could be moved up so its in lexicographic order.

2025-07-27 11:34 UTC, tritao commented on src/Mod/Part/App/PreviewExtension.h
> +#ifndef PREVIEWEXTENSION_H
```suggestion
#ifndef PART_APP_PREVIEWEXTENSION_H
```

or

```suggestion
#ifndef PART_PREVIEWEXTENSION_H
```

2025-07-27 11:35 UTC, tritao commented on src/Mod/Part/App/PreviewExtension.h
> +    /// Constructor
Nit: dunno if we have any recommendation for this but
```suggestion
```

2025-07-27 11:35 UTC, tritao commented on src/Mod/Part/App/PreviewExtension.h
> +#endif  // PREVIEWEXTENSION_H
Rename to match suggestion above.

2025-07-27 11:39 UTC, tritao commented on src/Mod/Part/App/Tools.h
> +     * \brief Determines whether the given TopoDS_Shape is empty.
```suggestion
     * \brief Determines whether the given \ref TopoDS_Shape is empty.

```

2025-07-27 13:47 UTC, tritao commented
Can you maybe explain the rationale for having a `PreviewExtension` and not doing it inside `Feature` itself?

2025-07-27 13:49 UTC, kadet1090 commented
> Can you maybe explain the rationale for having a `PreviewExtension` and not doing it inside `Feature` itself?

Sure. For now it is used only in Part Design - but I plan to extend the scope to other workbenches like Part or BIM. Hence it is created as extension (not every feature will have it) and in Part not PartDesign.

2025-07-27 14:56 UTC, tritao commented on src/Mod/Part/Gui/ViewProviderExt.cpp
> +    Bnd_Box bounds;
I know this is pre-existing code, but a local helper function (or two) would be nice here.

2025-07-27 15:00 UTC, tritao commented on src/Mod/Part/Gui/ViewProviderExt.cpp
> +    Base::Console().log("Shape tria info: Faces:%d Edges:%d Nodes:%d Triangles:%d IdxVec:%d\n",numFaces,numEdges,numNodes,numTriangles,numLines);
```suggestion
    Base::Console().log("Shape mesh info: Faces:%d Edges:%d Nodes:%d Triangles:%d IdxVec:%d\n",numFaces,numEdges,numNodes,numTriangles,numLines);

```

2025-07-27 15:00 UTC, tritao commented on src/Mod/Part/Gui/ViewProviderExt.cpp
> +    // printing some information
```suggestion
```

2025-07-27 17:03 UTC, tritao commented on src/Mod/PartDesign/Gui/ViewProviderHole.cpp
> +TaskDlgFeatureParameters* ViewProviderHole::getEditDialog()
Newline can be added here.

2025-07-27 17:06 UTC, tritao commented on src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp
> -    return std::string("PartDesign_") + featureName();
Super nit, but I would keep the original code here because `fmt` is a lot more code-bloat heavy and doesn't really seem to add much value here.

2025-07-27 17:08 UTC, tritao commented on src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp
> +        // ignore
Why ignore and not report the exception here in the console?

2025-07-27 17:09 UTC, tritao commented on src/Mod/PartDesign/Gui/ViewProviderTransformed.h
>      bool setEdit(int ModNum) override;
On the other view providers, you deleted all the `setEdit` methods, but not this one.

Can you explain why that is the case, or the overall idea for these?

2025-07-27 17:14 UTC, tritao commented on src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
> +    const QString text{ tr("Confirm Selection") };
Should we rename `btnPreview` too?

2025-07-27 19:23 UTC, kadet1090 commented on src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp
> -    return std::string("PartDesign_") + featureName();
Not sure about that, I agree that it does not add too much of value but string concatenation always seems smelly to me. 

@FreeCAD/code-quality-working-group any opinion?

2025-07-27 19:24 UTC, kadet1090 commented on src/Mod/PartDesign/Gui/TaskDressUpParameters.cpp
> +    const QString text{ tr("Confirm Selection") };
We probably simply should get rid of that method.

2025-07-27 19:29 UTC, kadet1090 commented on src/Mod/PartDesign/Gui/ViewProviderTransformed.h
>      bool setEdit(int ModNum) override;
That method in a lot of feature was simply copied and pasted so I could remove it and rely on the default implementation. Transformed however contains additional `recomputeFeature(false)` call that was there previously. To be honest - I don't know why it is there, my guess is that it should not be - but I don't want to change too much.

2025-07-27 19:31 UTC, kadet1090 commented on src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp
> +        // ignore
Really good question! Frankly, I don't remember so the comment is pretty shitty because if there was a reason to simple ignore it I should write it explicitly. I'll add reporting and either leave it or update the comment to explain why it is safe to ignore in that context.

2025-07-27 20:32 UTC, kadet1090 commented on src/Mod/Part/Gui/ViewProviderExt.cpp
> +    Bnd_Box bounds;
I did a bit of cleanup of that method: https://github.com/FreeCAD/FreeCAD/pull/17249/commits/ede34da384c6e3bec03043fb5e896fc0c20b320c, although I feel like I don't have enough of understanding to do more. To split it well I'd need to come up with good names for methods, and I simply cannot find good pieces of code to extract and label properly. The code is quite well separated with comments that give a good hint, but I still don't feel good with it.

2025-07-27 22:01 UTC, hyarion commented on src/Gui/ViewProviderDragger.cpp
> +}
```suggestion
App::PropertyPlacement* ViewProviderDragger::getPlacementProperty() const
{
    auto* object = getObject();
    auto* linkExtension = object->getExtensionByType<App::LinkBaseExtension>();
    if (!linkExtension) { 
        return getObject()->getPropertyByName<App::PropertyPlacement>("Placement");
    }

    auto* linkPlacementProp = linkExtension->getLinkPlacementProperty()
    if (!linkPlacementProp) {
        return linkExtension->getPlacementProperty();
    }

    return linkPlacementProp;
}
```

2025-07-27 22:01 UTC, hyarion commented on src/Mod/Part/App/Tools.cpp
> +    return result;
Why create a custom bounding box structure instead of using OCCT's Bnd_Box directly?

2025-07-27 22:01 UTC, hyarion commented on src/Mod/Part/Gui/ViewProviderPreviewExtension.h
> +#ifndef VIEWPROVIDERPREVIEWEXTENSION_H
Shouldn't this be prefixed with PARTGUI_?

2025-07-27 22:01 UTC, hyarion commented on src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp
> -    return std::string("PartDesign_") + featureName();
I think both ways works in this particular case.

If I had written it I would probably have used fmt too, but I don't have any argument for it either than:
* it's closer to how I create strings in Python and
* concatenation of strings can be problematic if we have different types, so it's easier to always use fmt.

But I'm really fine with both ways here.

2025-07-27 22:12 UTC, kadet1090 commented on src/Mod/Part/App/Tools.cpp
> +    return result;
It does not expose the required properties - you need to use the Get method to obtain all of them. If you are only interrupting in say xMin and xMax you still need to define useless variables.

2025-07-27 22:14 UTC, kadet1090 commented on src/Gui/ViewProviderDragger.cpp
> +}
Not sure about that one. The main execution path should be the least indented one - object being a link is exception so it is in the indented code path. Your version makes the link placement in the least indented path which my brain interprets as it being the usual happy path.

2025-07-27 22:17 UTC, kadet1090 commented on src/Mod/PartDesign/Gui/ViewProviderTransformed.cpp
> -    return std::string("PartDesign_") + featureName();
Let's stick with fmt here, we should optimize for code readability and intent rather than worrying about compile time complexity of basic tools.

2025-07-28 05:46 UTC, hyarion commented on src/Mod/Part/App/Tools.cpp
> +    return result;
You can access that like this:

auto minX = bounds.CornerMin().X();
auto maxX = bounds.CornerMax().X();

2025-07-28 07:48 UTC, kadet1090 commented on src/Mod/Part/App/Tools.cpp
> +    return result;
Oh I missed that API. Thanks, I'll remove redundant struct then.

2025-07-31 06:19 UTC, pieterhijma requested changes
Wow, I made it through... Looks really good. Have some comments but they're pretty minor (I've already forgotten my comments). This was only a code review by the way.

2025-07-31 06:19 UTC, pieterhijma commented on src/Mod/Part/App/Tools.cpp
> +        for (TopoDS_Iterator it(shape); it.More(); it.Next()) {
The level of indentation is a bit deep here. I'm actually ok here, but perhaps we can extract it to an `isCompoundShapeEmpty()` function. I would have a slight preference for that.

2025-07-31 06:19 UTC, pieterhijma commented on src/Mod/Part/App/Tools.h
> +     * \copydoc Part::Tools::isShapeEmpty(const TopoDS_Shape&)
Nice documentation. I would prefer `@` syntax instead of `\` (more prevalent in the rest of the code).

2025-07-31 06:19 UTC, pieterhijma commented on src/Mod/Part/Gui/ViewProviderExt.cpp
> +    saction.apply(this->faceset);
I got confused by these names and tried to understand why only `action` was given a generic name. I would prefer to have clear separate names without some sense of hierarchy. I would propose `updateVBOAction`, `clearSelectionAction`, and `clearHighlightAction`. With these names, the comments can be removed as well.

2025-07-31 06:19 UTC, pieterhijma commented on src/Mod/Part/Gui/ViewProviderExt.cpp
> +void ViewProviderPartExt::setupCoinGeometry(TopoDS_Shape shape,
I would also like to see this shorter, but I understand from earlier comments that you want to keep it like this. Perhaps we can create PRs that indicate targets for refactoring?

2025-07-31 06:19 UTC, pieterhijma commented on src/Mod/PartDesign/App/Feature.cpp
> +            for (auto &edge : face.getSubShapes(TopAbs_EDGE)) {
This is two levels of for loops and the code of the two inner loops is virtually the same. I would prefer calling a new function that is parameterized over the differences between these two loops for 1) remove repetition, 2) improve nested loops.

2025-07-31 06:19 UTC, pieterhijma commented on src/Mod/PartDesign/App/FeaturePrimitive.cpp
> +        this->recompute();
Why is the change from touch to recompute necessary?

2025-07-31 06:19 UTC, pieterhijma commented on src/Mod/PartDesign/App/FeatureTransformed.cpp
> +            BRep_Builder builder;
To keep the control flow more readable, I would prefer to extract the logic into a separate function similar to `getBaseShape()`.

2025-07-31 06:19 UTC, pieterhijma commented on src/Mod/PartDesign/Gui/ViewProvider.cpp
> +        const Base::Color green(0.0F, 1.0F, 0.6F);
Why such a specific green? I'm now wondering if this constant shouldn't be declared at a more global scope as it may be reused in other parts of the code.

2025-07-31 20:49 UTC, kadet1090 commented on src/Mod/Part/Gui/ViewProviderExt.cpp
> +void ViewProviderPartExt::setupCoinGeometry(TopoDS_Shape shape,
I don't think that it would be beneficial to create issues - if someone wants to give it a try to refactor it - they should be able to decide how to do it based on the process.

2025-07-31 20:49 UTC, kadet1090 commented on src/Mod/Part/App/Tools.h
> +     * \copydoc Part::Tools::isShapeEmpty(const TopoDS_Shape&)
Agreed, but that file uses `\` for the docs, keeping local consistency is more important and I don't want to pollute this already big PR with random documentation changes.

2025-07-31 20:51 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeaturePrimitive.cpp
> +        this->recompute();
Almost all property changes do trigger recompute of the result, but that was not the case for the position of primitives. For example if you had subtracting box and changed the length - the final preview got updated. If you changed position - the preview changed but final preview did not. It was inconsistent. There is no need to make that comment in file however, because triggering recompute is the normal behavior for most properties.

2025-07-31 20:52 UTC, kadet1090 commented on src/Mod/PartDesign/Gui/ViewProvider.cpp
> +        const Base::Color green(0.0F, 1.0F, 0.6F);
Let's leave it as-is - this is just random pick that looks good. It should be configurable via design token system but I first need to come up with a good set of tokens for that - feature scope imho.

2025-07-31 21:14 UTC, kadet1090 commented on src/Mod/Part/App/Tools.cpp
> +        for (TopoDS_Iterator it(shape); it.More(); it.Next()) {
Would it be actually beneficial? Such function would need to be private because you as developer really should never care about if shape is compound or not - the function should support both. From my perspective

```
    if (shape.ShapeType() == TopAbs_COMPOUND) {
        return isCompoundShapeEmpty(shape);
    }
```

does not give me any more information. It basically reads that the compound shape is empty, if compound shape is empty. I need to click into that function and read to see when compound is considered empty. While it is often beneficial to do it anyway - that is if the logic is complicated, but it is not the case - it is relatively small for loop.

I do however see a bit of value in making it into local lambda with `isEveryShapeInCompoundEmpty` name - that way it would be actually easier to follow. Because the condition is then

```
    if (shape.ShapeType() == TopAbs_COMPOUND) {
        return isEveryShapeInCompoundEmpty(shape);
    }
```

which actually is easier to parse - compound shape is considered empty if every shape in compound is empty - that actually can prevent me from reading that for loop and trying to understand it.

2025-07-31 21:15 UTC, kadet1090 commented on src/Mod/Part/Gui/ViewProviderExt.cpp
> +    saction.apply(this->faceset);
That code was there - let's not change it into "Refactor ViewProviderExt" PR.

2025-07-31 21:31 UTC, kadet1090 commented on src/Mod/PartDesign/App/FeatureTransformed.cpp
> +            BRep_Builder builder;
Agreed! I've moved it into local lambda, but if you think that private function would be better I'm fine with that too.

2025-07-31 21:31 UTC, kadet1090 commented on src/Mod/PartDesign/App/Feature.cpp
> +            for (auto &edge : face.getSubShapes(TopAbs_EDGE)) {
Totally!

2025-08-01 10:02 UTC, kadet1090 commented
@pieterhijma thanks for the comments! I've gone through them and where it was in scope of that PR I introduced some changes - take a look at what changed and if its ok because I did it sometimes a bit differently than you asked but don't have a strong opinion on most of that so I'll be happy to change.

2025-08-01 12:42 UTC, pieterhijma commented on src/Mod/Part/App/Tools.cpp
> +        for (TopoDS_Iterator it(shape); it.More(); it.Next()) {
Yep, sounds good.

2025-08-01 12:43 UTC, pieterhijma commented on src/Mod/PartDesign/App/FeatureTransformed.cpp
> +            BRep_Builder builder;
No strong preference.

2025-08-01 12:44 UTC, pieterhijma commented on src/Mod/PartDesign/Gui/ViewProvider.cpp
> +        const Base::Color green(0.0F, 1.0F, 0.6F);
Ok

2025-08-01 12:47 UTC, pieterhijma approved these changes
Thanks, looks great! Please note  that this approval is based on a code review. I haven't actually tested the code. Please let me know if that is necessary as well.

2025-08-01 13:01 UTC, kadet1090 commented
> I haven't actually tested the code. Please let me know if that is necessary as well.

Would be great - Max however did already test quite a lot so there is no strict need to.

2025-08-01 13:16 UTC, maxwxyz commented
Is there a need to test again? The 4 issues above are still present.
I would not close https://github.com/FreeCAD/FreeCAD/issues/11214 with this PR as not all tools are showing previews with this PR. I could adjust which ones are missing in the issue.

2025-08-01 13:19 UTC, kadet1090 commented
> Is there a need to test again? The 4 issues above are still present.

Don't think so - we need to reduce scope creep in that one. 

> Is there a need to test again? The 4 issues above are still present. I would not close #11214 with this PR as not all tools are showing previews with this PR. I could adjust which ones are missing in the issue.

Agreed - maybe we should change that Issue into sort of epic that would track remaining issues? We could then create issues for the 4 remaining problems and add it to that issue as sub-issues?

2025-08-01 13:21 UTC, maxwxyz commented
will do when merged

2025-08-01 14:48 UTC, chennes commented on src/Mod/Part/App/PreviewExtension.cpp
> +#include "PreCompiled.h"
This has to be the first include or MSVC will complain.

2025-08-01 14:59 UTC, kadet1090 commented on src/Mod/Part/App/PreviewExtension.cpp
> +#include "PreCompiled.h"
Dang it! Do you know why it passes CI?

2025-08-07 20:33 UTC, merged

2025-08-07 20:35 UTC, pierreporte commented
Congrats @kadet1090!

2025-08-07 20:38 UTC, sclebo05 commented
Just a casual watching commit logs, but this transparency stuff is really cool. Many thanks to @kadet1090 !

2025-08-07 21:08 UTC, kaiwas commented
Cool!

2025-08-09 15:42 UTC, sylanc3 commented
Thanks for bringing in such features!

2025-08-09 20:48 UTC, MisterMakerNL commented
This is really nice! Feels like a feature that always should have been part op Freecad.

2025-08-10 15:16 UTC, maxwxyz commented
Issue was adjusted for the missing implementation https://github.com/FreeCAD/FreeCAD/issues/11214

2026-03-25 09:58 UTC, luzpaz commented
cc @kadet1090 Is there API documentation for this feature so 3rd party workbenches can utilize it ?  
* ref: https://github.com/shaise/FreeCAD_SheetMetal/issues/566

2026-04-17 11:37 UTC, luzpaz commented
Where is the Transparent Preview documentation for developers ? Does it exist ?