[Gui] Make start buttons always rely on style sheet
FreeCAD/FreeCAD pull request #17347
Opened 2024-10-19 18:33 UTC by benj5378

Fixes #15756. There is no need having a function setting backup colors, as these will always be set by the stylesheet.

2024-10-19 18:42 UTC, benj5378 commented
It might seem like a lazy quickfix for money, but I believe, that it's the right and best one.

The filecardstyle function seems to be made, to have colors to fall back on, even though no style sheet were set. However, if no style sheet is set, it will in any case just use FreeCAD classic style. Classic, dark and light were all set to ignore the fallback using `<FCBool Name="FileCardUseStyleSheet" Value="0"/>`.

In other words, filecardstyle function had no practical use. So deprecating the filecardstyle function for fallback colors, will not change the appearence of the start page. It was only there to cause issues when switching style sheets.

The only case, where the fallback of filecardstyle function would ever be used, was when 1) there is no stylesheet and 2) `FileCardUseStyleSheet` parameter would be true (which it isn't any of shipped preferences).

So this could only, and only be in a external preference pack without any stylesheet, that wanted to switch to specific colors defined in filecardstyle. In this case, the colors should instead be set using a stylesheet. For that case, I can add the following code, so the start buttons are specifically customizable, if anyone wants it:

```
newEmptyFile->setObjectName("startNewFileButton"); 
openFile->setObjectName("startNewFileButton"); 
partDesign->setObjectName("startNewFileButton"); 
assembly->setObjectName("startNewFileButton"); 
draft->setObjectName("startNewFileButton"); 
arch->setObjectName("startNewFileButton"); 
```

Let me know, if I got something wrong here, and it is the case, that one should be able to make a preference back, that defines colors of buttons, without using a stylesheet, only a .cfg config file.

2024-10-19 19:48 UTC, Reqrefusion commented
It's always exciting to see a bug fixed by simply deleting a line.

2024-10-19 20:01 UTC, MisterMakerNL commented
Lol you git 500$ for deletimg a broken useless function? 
The use of preferences for setting these colors is in my opinion not a good idea. So I'm very happy if it gets removed.

2024-10-19 22:02 UTC, wwmayer commented
> for deleting a broken useless function?

So, is it? This function is supposed to be used if no application-wide style sheet is used!

2024-10-19 22:20 UTC, wwmayer requested changes
I don't mind if the user parameter is removed. But removing the function `fileCardStyle()` is not an option because it makes the top buttons to look bad and inconsistent compared to the thumbnail buttons.

The method `fileCardStyle()` returns an empty string if an application-wide style sheet is set. So, it should be fine to set the style sheet to these buttons if the returned string is not empty.
```
QString style = fileCardStyle();
if (!style.isEmpty()) {
    newEmptyFile->setStyleSheet(style);
    openFile->setStyleSheet(style);
    partDesign->setStyleSheet(style);
    assembly->setStyleSheet(style);
    draft->setStyleSheet(style);
    arch->setStyleSheet(style);
}
```

2024-10-20 05:45 UTC, MisterMakerNL commented
> > for deleting a broken useless function?
> 
> So, is it? This function is supposed to be used if no application-wide style sheet is used!

So is it necessary if a linux stylesheet is used or is it possible that it takes the colors from there just like the rest of the ui?

2024-10-20 07:42 UTC, benj5378 commented
> because it makes the top buttons to look bad and inconsistent compared to the thumbnail buttons.

@wwmayer , when does it? Because it doesn't in Classic, Dark og Light. Even deleting the stylesheets, thumbnail and file buttons are similar.

Please give steps to reproduce.

2024-10-20 09:00 UTC, benj5378 commented
> > because it makes the top buttons to look bad and inconsistent compared to the thumbnail buttons.
> 
> @wwmayer , when does it? Because it doesn't in Classic, Dark og Light. Even deleting the stylesheets, thumbnail and file buttons are similar.

You are correct, thumbnail buttons and new file buttons actually are different in FreeCAD Classic. But it was that even before this PR, so no regression here. Only on first startup, the buttons would be similar - after first restart, the buttons would be different.

2024-10-20 09:55 UTC, hyarion commented
I tested this last night, and on a fresh install (simulated using the non-merged safe mode) on macOS with dark mode selected in the welcome screen.

This is how it looks before I apply the fix:
![image](https://github.com/user-attachments/assets/2ca51166-63c3-4308-8ee0-0ea21e979cf0)

And this is after applying the fix:
![image](https://github.com/user-attachments/assets/49ab0d80-4860-4a45-8269-63e2aaa677d9)

So visually, for me at least, it solves the issue in darkmode :)

2024-10-20 09:59 UTC, Syres916 commented
What's wrong with changing:

```
    if (!qApp->styleSheet().isEmpty()) {
        return {};
    }
```

to:

```
    auto hGrpView = App::GetApplication().GetParameterGroupByPath(
        "User parameter:BaseApp/Preferences/MainWindow");
    auto qssFile = hGrpView->GetASCII("StyleSheet", "");
    if (!qssFile.empty()) {
        return {};
    }
```

?

2024-10-20 10:29 UTC, benj5378 commented
@Syres916, there is not anything wrong with this specific change. It just doesn't solve the issue. If we still keep the function (no matter internals), then we have to:

> * save all the buttons as state (member variable)
> * create an update function in StartView.cpp
> * call the update function when changing preferences in DlgSettingsGeneral.cpp

Causing spagthetti code. And we will still have styles defined multiple places. We can do this, but then I find it better to just not use this function, causing more hurtles, than it solves.

2024-10-20 12:13 UTC, MisterMakerNL commented
Preferences should only be used for stuff a stylesheet cannot do.

2024-10-20 14:06 UTC, obelisk79 commented
I'll do some testing later, but removing the preference seems like the smart thing to do. The fact that we are arguing about workarounds to make these buttons look correct implies that there is an inherent implementation problem. Implement these buttons in such a way that they respect style like the rest of the widgets in FreeCAD. This whole debate is rather shocking to me.

2024-10-21 16:09 UTC, adrianinsaval commented
> I don't mind if the user parameter is removed. But removing the function `fileCardStyle()` is not an option because it makes the top buttons to look bad and inconsistent compared to the thumbnail buttons.

in what situation does this happen? But at the very least is should not be setting any colors. No stylesheet does not mean light theme and even if it is a light theme the color might not be a good match.

2024-10-23 03:40 UTC, adrianinsaval commented
I believe there is no question about the removal of the preferences, they are unwanted. The remaining question is just if there should be a fallback stylesheet for the buttons.

2024-10-23 06:01 UTC, hyarion commented
To highlight a tangential issue, hard coded color values are an issue in FreeCAD when using dark mode in the os. It will generate black text on dark backgrounds and white text on light backgrounds.

By doing as @bofdahof suggests, it would be possible to create a classic light mode style sheet and a dark mode counterpart. Then FreeCAD can switch between these to match the os mode.

The issue can be seen in this draft pull request https://github.com/FreeCAD/FreeCAD/pull/17410

2024-10-23 07:58 UTC, MisterMakerNL commented
> > the removal of the preferences
> 
> ThemeAccentColor1 ThemeAccentColor2 ThemeAccentColor3 FileCardSpacing NewFileIconSize FileCardLabelWith FileCardBackgroundColor FileCardBorderColor FileCardSelectionColor FileCardUseStyleSheet
> 
> ... are IMO all style elements, not prefs, and should be in stylesheet(s).
> 
> IMO there must be at least a default application stylesheet. (like a reset sheet in CSS).
> 
> The main stylesheet(s) is/are the place for generic style data, perhaps incorporating themes.
> 
> Ideally the unique features of the buttons and widgets (and the ones here are unique) should be in a tiny local stylesheet located with or in that widget, perhaps passed in as a setup parameter.
> 
> But, can a local sheet set unique local features whilst allowing generic eg color setting to inherit from main sheet (I recall a forum discussion that said this common CSS concept is broken in Qt/QSS)?
> 
> If it does work then the solution is simple. Else, well I hope it can.

ThemeAccentColor1
ThemeAccentColor2
ThemeAccentColor3
Are actually dynamically linked with variables in stylesheet, and are there to give users to option to choose different colors.

2024-10-25 03:27 UTC, chennes commented
Just for the record: with Qt6 on Windows 11, this PR makes the Start screen look fine in both Windows Light and Windows Dark themes, regardless of which FreeCAD theme is chosen. (With the caveat that Classic is unusable in Windows Dark in the *rest* of FreeCAD 😁 -- *Start* is fine.).

I'm not sure what the right path forward here is if @wwmayer wants us to keep around `fileCardStyle()` -- the @FreeCAD/design-working-group has basically come to the consensus that function needs to go (if I am understanding correctly). We can discuss this on Monday morning, but please feel free to leave comments here (particularly if you cannot attend the PR Review Meeting).

2024-10-26 15:11 UTC, chennes commented
You're giving me too much credit (or blame 😁). Werner added the `fileCardStyle()` stuff, I was only responsible for the underlying widget structure. I originally designed it as an experiment in using QtQuick/QML within FreeCAD, and when that failed due to our need to support both Qt 5.12 and Qt 6, I fell back to pure C++ to get something working. @wwmayer came along after me and made it look presentable.

2024-10-28 15:49 UTC, yorikvanhavre commented
Obsoleted by the merge of #17376

2024-10-28 15:49 UTC, closed without merging