Animation of Results
FreeCAD/FreeCAD pull request #18496
Opened 2024-12-14 11:09 UTC by mac-the-bike

2024-12-14 13:50 UTC, Reqrefusion commented
Great work, I wish you could explain a little more what you are doing. Also if you've made any changes to the interface a screenshot or something like that would be great.

2024-12-16 00:08 UTC, luzpaz commented on src/Mod/Fem/CreateLabels.py
> +        return self.translation
Probably worth using the python docstring approach:
```python
def get_position(self):
    """Get position of label."""
    return self.translation
```

And doing it for the the rest of the file

2024-12-16 00:09 UTC, luzpaz commented on src/Mod/Fem/Gui/Resources/ui/ResultShow.ui
> +          <string>number of steps per cycle</string>
Capitalize 'N' in 'Number'

2024-12-16 00:11 UTC, luzpaz commented on src/Mod/Fem/CreateLabels.py
> +#  \brief create labels
Maybe a little more elaboration here?

2024-12-16 00:16 UTC, luzpaz commented
Also, please prepend `FEM:` to the the commit title so it looks like:  
"FEM: Animation of Results"

This helps us to populate the documentation easier by knowing what the code in this commit touches within FreeCAD.

2024-12-16 12:59 UTC, FEA-eng requested changes
Animations seem to work but I agree with @luzpaz that animation controls may need some adjustments - capitalizing, maybe adding colons. I'm not sure if we need the "number of cycles" setting - maybe it should just run until it's stopped by the user.

Also, when I start the animation, quit the task panel, go back and so on, the button's "start/stop" status is not updated and I get some errors:

```
13:57:47  Traceback (most recent call last):
13:57:47    File "/home/ubuntu/Documents/freecad_animate_fem/freecad-source/build/Mod/Fem/femtaskpanels/task_result_mechanical.py", line 164, in <lambda>
13:57:47      lambda dummy="", name="startButton": self.value_changed(self, dummy, name),
13:57:47    File "/home/ubuntu/Documents/freecad_animate_fem/freecad-source/build/Mod/Fem/femtaskpanels/task_result_mechanical.py", line 793, in value_changed
13:57:47      self.animate_displacement()
13:57:47    File "/home/ubuntu/Documents/freecad_animate_fem/freecad-source/build/Mod/Fem/femtaskpanels/task_result_mechanical.py", line 784, in animate_displacement
13:57:47      self.result_widget.startButton.setText("Start Animation")
13:57:47  RuntimeError: Internal C++ object (PySide2.QtWidgets.QPushButton) already deleted.
```

2024-12-20 06:39 UTC, maxwxyz commented
@mac-the-bike ping for feedback

2024-12-20 13:00 UTC, mac-the-bike commented
Fri 20 Dec 12:07:53 GMT 2024

Thanks, I think.


Starting at the top:

Reqrefusion : I will try to update the Result Show documentation.

Formatting: I am going to leave the code as is.

ResultShow.ui: I will have a go at capitalising.

FEA-eng:
I am going to leave the number of cycles as is.
The error messages you are getting are caused by pressing "Close" before the animation has stopped. I have put a "try/except" around the problems, hopefully.

I have no great knowledge of doing things in github, can you advise me of how I can change the code that I have pushed? 

Do I just do another push with the new code and if so how?

2024-12-20 13:42 UTC, maxwxyz commented
Just do another push to this branch on your fork. It'll update here.

2024-12-22 07:48 UTC, maxwxyz commented
waiting for an update

2024-12-28 13:22 UTC, mac-the-bike commented
maxwxyz 
At last. I hope that I have changed things. (It took some experimenting!)
_The changed files:_
task_result_mechanical.py
CreateLabels.py
ResultShow.ui

_New files:_
user_guide_animate.txt   - a help for the new panel, I don't know how to change the current panel.
results.png - a picture of the new interface.

2025-01-02 13:45 UTC, FEA-eng commented
I don't see the errors anymore but what still bothers me is that after closing the task panel when the animation is active and then reopening it, its button and settings are reset and it's still running with no way to stop it before it completes the initially specified number of cycles (not the default 4):

![animation_issue](https://github.com/user-attachments/assets/51a19839-1e8b-4350-b44b-51302e000a34)

Is there no easy way to abort the animation and reset its state when closing the task panel?

2025-01-06 10:22 UTC, maxwxyz commented
@mac-the-bike any feedback on how to stop the animation?

2025-01-10 12:56 UTC, luzpaz commented
This is an aside of the above discussion, I don't want to create too much of digression but my intention is to possibly provide you a better experience working with `git` in the future.

>  At last. I hope that I have changed things. (It took some experimenting!)

@mac-the-bike thanks for braving git and github. I work with `git` in a very handicapped version of it because I've messed PRs up before due to it's non-intuitive ways.

It's easy to see from the git history that you're shoehorning git to work for you. I do it as well, but to a lesser extent.

![Screenshot_20250110_070154](https://github.com/user-attachments/assets/e588368c-7e38-4911-bd3f-07c17f9b0b8c)

#### Breakdown
In the screenshot is your commit history of this PR. Reading the history from the top down (in the order you started to make changes to the PR) it's possible to see that right after your made the PR, the pre-commit hook process altered it  for linting purposes. Then you made 2 tidy commits. Then the pre-commit hook linted your work again. 2 more commits were made and then we suddenly see a different branch merged. This is where things escalated. 

#### Pain point diagnosis
You're not rebasing (incorporating) the alterations that were made to your remote branch **back** into the local git repository you're working in. The pre-commit bot (if you will) makes changes to your PR. You need to pull those changes back into your local and rebase or else your just overwriting the changes each time. 

You can simply do this running:   
`git rebase origin/mac-the-bike:branch_2`  
Note: `origin` here is `https://github.com/mac-the-bike/`  
and `mac-the-bike:branch_2` is https://github.com/mac-the-bike/animate/tree/branch_2

Important point: you need to `git rebase` before you make changes to your local code or else what you get is a conflict. Your downstream code is now out of sync with your remote `origin` code. That's why `git` will start to complain about merge conflicts and then bring up that horribly unintuitive merge resolver. And that's what probably happened to you and why the next thing happened:

Commit https://github.com/FreeCAD/FreeCAD/pull/18496/commits/edf6c431b7248213925085d8580cfb52753ff688 looks like you created a new branch and merged it in order to overcome the mess that was created.

But it looks like you recovered and persevered. 

Something I learned about `git` is that the commands like `git merge` (or another example `git pull`) don't mean exactly what they literally mean. That is why I totally stay away from `git merge` (I've never really comprehended its utility for my workflow, so I just don't touch it.). If I want to make changes to a PR, I use `git commit` for each change. And then I will use `git rebase -i HEAD~x` where x is the number of commits preceding HEAD I'd like to incorporate in to the rebase. Check this [tutorial](https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d) out to get a very comprehensive understanding of it. 

> New files:
`user_guide_animate.txt` - a help for the new panel, I don't know how to change the current panel.
`results.png` - a picture of the new interface.

Next time you can easily just drag/drop the `result.png` from your file manager into the Github textbox and the image will automagically upload and attach itself (I simulated this in https://github.com/FreeCAD/FreeCAD/pull/18496#issue-2739783111). The contents of `user_guide_animate.txt` was also added as you can see. 

Now you have these 2 files, `user_guide_animate.txt` & `results.png` part of the PR. They need to be reverted. This is super easy to do but not very straightforward. This is another unintuitive part of `git` (and there's probably a better way to do this that I haven't learned yet). 

`git revert commit_hash` will undo the commit you specified and automatically commit the changes in to an new commit. This is problematic when you only want to partially change a previous commit. The solution is to use `git commit -n commit_hash` the `-n` flag tells git not to auto-commit but instead stage the reverted changes for you to inspect. Then I move all the files from a 'staged' status to unstage. Next, i locate the specific changes that I want reverted and stage them. Then after I've made sure all the changes I want will be reverted, I `git commit` those changes. This now reverts those changes. Then I need to `git push --force-with-lease` to push those changes back up to `origin`.

2025-01-15 12:35 UTC, luzpaz commented
@mac-the-bike did that help at all ? :point_up_2:

2025-01-15 13:07 UTC, mac-the-bike commented
Yes -  I am trying to change: task_result_mechanical.py but I am having problems with pull/push and unstaged changes.
 Is there any way of removing everything I have tried and start again  from a clean sheet?

2025-01-15 14:13 UTC, luzpaz commented
Yes, there is a way to do it using `git reset` but you need to know what commit you want to reset it back to. Which one from this list ? https://github.com/FreeCAD/FreeCAD/pull/18496/commits

Also if you have unstaged changes and that is blocking you from committing or rebasing or whatever..you can temporarily 'stash them. Using `git stash` will literally stash the changes and clear your unstaged changes list. Then when the time comes when you want to reveal them again you can use `git stash pop`. `git stash list` will show you different stashes. `git stash show` allows you to see what's in a specific stash without popping it.

2025-01-15 15:17 UTC, luzpaz commented
@mac-the-bike i know what you're experiencing. It's annoying. But once you understand the quirks, it's easier to navigate. Sort of like FreeCAD, lol

2025-01-27 09:27 UTC, maxwxyz commented
waiting for change

2025-01-27 14:04 UTC, mac-the-bike commented
[maxwxyz](https://github.com/maxwxyz)       

 "results.png & user_guide_animate.txt need to be removed from the commit"

I can't find these files - am I missing something? 

As I am unable, don't know how, to change the Help for results: https://wiki.freecad.org/FEM_ResultShow
I put those files in the commit so that they could be merged into the Help.

[luzpaz](https://github.com/luzpaz) you have done exactly what I would have done, many thanks!!.

2025-01-27 16:48 UTC, maxwxyz commented
user guide txt is at root level, you can check out the files here: https://github.com/FreeCAD/FreeCAD/pull/18496/files

2025-01-27 22:47 UTC, luzpaz commented
@mac-the-bike (notice I preceded your github nick with an `@`, this is how you signal someone on github)

> I can't find these files - am I missing something?

![Screenshot_20250127_174347](https://github.com/user-attachments/assets/3daf9be2-8ddf-4099-b704-c93b791f6829)

As max pointed out, they are in the top directory of your submitted patch.

>  I put those files in the commit so that they could be merged into the Help.

If you look at the first post of this PR, I added those files to it by drag/dropping them in to Github instead of adding documentation to the PR itself. The FreeCAD wiki is the place where documentation is updated.

2025-01-28 12:43 UTC, mac-the-bike commented
[luzpaz](https://github.com/luzpaz), [maxwx](https://github.com/maxwxyz), [FEA-eng](https://github.com/FEA-eng)

 Thanks help in persevering with my desperate efforts with GIT. I have learned a lot about GIT which I will no doubt forget when it comes to doing another commit.

lupaz: that long explanation about GIT, which is:
_This is an aside of the above discussion, I don't want to create too much of digression but my intention is to possibly provide you a better experience working with git in the future._

Is it worth putting this into the FreeCAD Forum?

2025-01-28 13:42 UTC, luzpaz requested changes

2025-01-28 13:42 UTC, luzpaz commented on src/Mod/Fem/Gui/Resources/ui/ResultShow.ui
> +          <string>  Number of Steps per Cycle</string>
There is whitespace preceding 'Number'

2025-01-28 13:42 UTC, luzpaz commented on src/Mod/Fem/Gui/Resources/ui/ResultShow.ui
> +          <string>  Number of Cycles</string>
There is whitespace preceding 'Number'

2025-01-28 13:51 UTC, mac-the-bike commented
The blanks are there for aesthetic reasons.
I have left False so that the change I have made can be seen.

2025-01-28 14:15 UTC, luzpaz commented
> The blanks are there for aesthetic reasons.  

Does that also scale for hidpi monitors etc... ?

2025-01-29 12:22 UTC, luzpaz commented
@hasecilu hi, can you weigh-in on your experience with translators and is there a way to encode the whitespace outside of the translation string in the .ui ? (see recent review comments above)

2025-01-30 03:08 UTC, hasecilu commented
Hi, on the UI file you could add a comment in the _disambiguation_ entry (just below the text), saying "Do not remove leading spaces" (recently I did that on a patch). Both Qt Linguist and CrowdIn warn you of different format of the string in case of missing spaces.

If you really want to separate you would need to assign the text on the Python code.

2025-01-30 14:33 UTC, luzpaz commented
@hasecilu can you give an example of a disambiguation entry ?

2025-01-30 16:33 UTC, hasecilu commented
You need to select the label and on the Properties editor, label section, below the text you can add the disambiguation.

![image](https://github.com/user-attachments/assets/64bcbde6-51b5-4287-be67-6b5ce1687380)

2025-01-31 13:58 UTC, luzpaz commented
@mac-the-bike do you mind adding these warnings to translators in the disambiguation field ?

2025-02-01 19:39 UTC, chennes commented
No, don't do that: this not a good strategy. The inter-widget spacing is controlled by the stylesheets, and if there's a problem with it we should resolve it globally, not by randomly inserting spaces in individual controls.

2025-02-03 17:07 UTC, chennes commented
(Not really quite approved, from me anyway... the widget's spacing needs to get fixed and the string's extra spaces removed)

2025-02-08 13:09 UTC, maxwxyz commented
@mac-the-bike could you please address the proposed changes?

2025-02-13 13:05 UTC, FEA-eng commented
> I don't really fell like implementing those features, if you wish to have a go then you can. The files of interest are:

Yeah, it was just a note with some potential ideas for the future improvement.

It seems that you closed this PR by accident.

2025-02-13 13:29 UTC, mac-the-bike commented
I was not intending to close the PR.
How do I reopen it?

2025-02-13 13:30 UTC, mac-the-bike commented
I seem to have answered my own question.

2025-02-17 16:24 UTC, merged