[Toponaming] Import code releted to _ElementMapVersion from LS3
FreeCAD/FreeCAD pull request #18791
Opened 2024-12-29 13:48 UTC by CalligaroV

This PR imports code related to `GeoFeature::_ElementMapVersion` from LS3.

The imported code helps improving the compatibility for models designed with pre v1.0 (pre Toponaming) versions of FreeCAD.

according to https://github.com/FreeCAD/FreeCAD/issues/17124#issuecomment-2517662019 this fixes #17124 (the files [Issue_examples.zip](https://github.com/user-attachments/files/17301745/Issue_examples.zip) in the OP as well as [Example3.zip](https://github.com/user-attachments/files/17358935/Example3.zip) in https://github.com/FreeCAD/FreeCAD/issues/17124#issuecomment-2409852508)

2024-12-29 14:26 UTC, kadet1090 approved these changes
LGTM

2024-12-30 09:36 UTC, luzpaz requested changes

2024-12-30 09:36 UTC, luzpaz commented on src/Mod/Part/App/PropertyTopoShape.cpp
> +    // In LS3 the following statement is exectuted right before shape.Hasher = hasher;
`executed`

2025-01-10 15:12 UTC, maxwxyz commented
@luzpaz is this good now?

2025-01-18 16:01 UTC, chennes commented on src/Mod/Part/App/TopoShapeExpansion.cpp
> +        if ((OCC_VERSION_HEX & 0xFF0000) == 0x070000) {
Could you add a comment explaining why this is necessary?

2025-01-18 16:02 UTC, chennes commented on tests/src/Mod/PartDesign/App/BackwardCompatibility.cpp
> +    std::string _testPath;          // NOLINT Can't be private in a test framework
The two NOLINTs are unnecessary since they ARE private here 😁

2025-01-27 17:11 UTC, yorikvanhavre commented
Waiting for review of @cheenes comments

2025-02-03 14:45 UTC, maxwxyz commented
@CalligaroV friendly reminder

2025-02-12 20:14 UTC, chennes commented on src/Mod/Part/App/TopoShapeExpansion.cpp
> +        if ((OCC_VERSION_HEX & 0xFF0000) == 0x070000) {
```suggestion
        // Stabilize the reported OCCT version: for any version of OpenCASCADE in the 7.x series,
        // report 7.2.0 as the version so that we aren't constantly inadvertently reporting differing
        // versions. This is retained for cross-compatibility with LinkStage3.
        if ((OCC_VERSION_HEX & 0xFF0000) == 0x070000) {
```

2025-02-12 20:22 UTC, chennes commented on tests/src/Mod/PartDesign/App/BackwardCompatibility.cpp
> +    std::string _testPath;          // NOLINT Can't be private in a test framework
```suggestion
    App::Document* _doc = nullptr;
    std::string _testPath;
```

2025-02-12 20:26 UTC, chennes commented on src/Mod/Part/App/TopoShapeExpansion.cpp
> +        }
```suggestion
        // Stabilize the reported OCCT version: report 7.2.0 as the version so that we aren't 
        // constantly inadvertently reporting differing versions. This is retained for 
        // cross-compatibility with LinkStage3 (which retains supporting code for OCCT 6.x,
        // removed here).
        unsigned occ_ver {0x070200};
```

2025-02-13 03:42 UTC, chennes commented on src/Mod/Part/App/TopoShape.h
> +    virtual std::string getElementMapVersion() const;
```suggestion
    std::string getElementMapVersion() const override;
```

2025-02-13 03:42 UTC, chennes commented on src/Mod/Part/App/TopoShapeExpansion.cpp
> +        // Stabilize the reported OCCT version: report 7.2.0 as the version so that we aren't
```suggestion
        // Stabilize the reported OCCT version: report 7.2.0 as the version so that we aren't
```

2025-02-13 03:42 UTC, chennes commented on src/Mod/Part/App/TopoShapeExpansion.cpp
> +        // constantly inadvertently reporting differing versions. This is retained for
```suggestion
        // constantly inadvertently reporting differing versions. This is retained for
```

2025-02-14 16:54 UTC, merged