AddonManager: Consolidate preference in user.cfg from Plugins to  Addons
FreeCAD/FreeCAD pull request #2625
Opened 2019-10-15 23:44 UTC by luzpaz

Currently when a user first uses the Addon Manager a dialog popup prompts them about how FC is not liable for the code plugin authors provide. It stores the binary response in a `readWarning` boolean  within the user.cfg file.  

This commit changes the location of said boolean from `User parameter:Plugins` to `User parameter:Addons`

In other words changing:  
```
    <FCParamGroup Name="Plugins">
      <FCParamGroup Name="addonsRepository">
        <FCBool Name="readWarning" Value="1"/>
      </FCParamGroup>
    </FCParamGroup>
``` 
to:   

```
        <FCParamGroup Name="Addons">
          <FCParamGroup Name="addonsRepository">
            <FCBool Name="readWarning" Value="1"/>
          </FCParamGroup>
        </FCParamGroup>
```

2019-10-16 00:43 UTC, luzpaz commented
This has been test on the latest AppImage:  
> OS: Manjaro Linux (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18522 (Git) AppImage
Build type: Release
Branch: master
Hash: e0bb5701f6cb3936501afe59527cbce03017beda
Python version: 3.7.3
Qt version: 5.12.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

2019-10-17 20:40 UTC, yorikvanhavre commented
This will make the popup appear again for everybody... Do you really think it's worth the hassle...

2019-10-17 22:35 UTC, luzpaz commented
@yorikvanhavre just once and then it will be done (harmless :smile: ) I think it's worth it because we're keeping the user.cfg organized from here on out. It also helps my effort over in this [gist](https://gist.github.com/luzpaz/1f1ad4b78c20465c43d6721f11966acc), and keeps the user.cfg intuitive.

2019-10-20 14:08 UTC, luzpaz commented
Rebasing due to travisci error that I'm not certain about.

2019-10-28 12:51 UTC, yorikvanhavre commented
I think if we do this we should then also 1) detect if the old prop is there and 2) delete it otherwise we are just polluting the parameters tree more...

2019-10-29 09:32 UTC, luzpaz commented
@yorikvanhavre  
What's the best way to detect it and then remove it. I've been struggling with making this happen.

2019-10-29 13:43 UTC, yorikvanhavre commented
```
oldpar = FreeCAD.ParamGet('User parameter:Plugins/addonsRepository')
if 'readWarning' in oldpar.GetBools():
    # do the migration, create the new bool and fill it with the value of the old one
    # ...
    oldpar.RemBool('readWarning')
```
That way the migration is fully transparent to the user

2019-12-10 13:31 UTC, luzpaz commented
Still working on this. I'm thinking out loud here if there may be an issue with the ability for FC to run 2 different versions in parallel (like 0.18 and 0.19). 

In that usecase I'm not sure what the behavior of FC will be in regards to the user.cfg file.  

If you open FC v0.18 then it will look in the user.cfg for 
```xml
    <FCParamGroup Name="Plugins">
      <FCParamGroup Name="addonsRepository">
```

and if you run in 0.19 it will modify the config file by moving to:
```xml
        <FCParamGroup Name="Addons">
          <FCParamGroup Name="addonsRepository">
```
and then remove the old configs. 

Haven't tested yet to see what happens.

2019-12-20 18:16 UTC, luzpaz commented
please add `on hold` label to this PR

2020-02-06 14:46 UTC, luzpaz commented
@yorikvanhavre :point_up:

2021-03-11 23:17 UTC, hyarion commented
There are two options to handle old versions as I see it:

1. Migrate the setting if the new one isn’t set, but don’t remove the old parameter. (A dead parameter will linger in the config file but is this really that bad?)
2. Using separate config files for each freecad version: If no 0.20 config file, migrate a copy of the 0.19 config file.

There are pros and cons with both these solutions. The 2:nd will be a more flexible option but the 1:st would be quicker to implement and might be a better fit for this specific usecase.
I think I would go with the 1:st of these two options.

2021-03-12 15:19 UTC, luzpaz commented
@hyarion  why would the dead parameter linger? We could remove it as well right ?

2021-03-12 16:32 UTC, luzpaz commented
@hyarion do you want to tackle this?

2021-03-12 18:25 UTC, hyarion commented
@luzpaz what I mean is that in order to be compatible with older freecad versions we need to keep the old parameter.
For users who upgrade but don't use an old version the old parameter will live on in their configuration file. This because they could install an old version at a later point.

2021-03-12 19:29 UTC, hyarion commented
Here's what I meant in (untested) might be a good implementation: https://github.com/FreeCAD/FreeCAD/commit/3afd544ed609c3d0f1839e3f8d5697ab4b113736 (I've modified @luzpaz commit slightly)

2021-03-12 22:04 UTC, luzpaz commented
@yorikvanhavre what say you?

2021-08-20 04:09 UTC, chennes commented
I think this migration makes sense -- @hyarion's code looks great to me. @luzpaz can you tweak your PR to match?

2021-08-20 11:54 UTC, luzpaz commented
Tweaked. Thanks @hyarion and @chennes!  
@yorikvanhavre ready for your review

2021-08-20 14:34 UTC, chennes commented on src/Mod/AddonManager/AddonManager.py
> +        readWarning |= FreeCAD.ParamGet('User parameter:Plugins/addonsRepository', False)
Sorry, I didn't look at this closely enough before. Line 77 should really be two lines, one to fetch the new storage location, and a second line to access the specific stored variable (I haven't tested this yet, though):
```suggestion
        newReadWarningParameter = FreeCAD.ParamGet("User parameter:Plugins/addonsRepository")
        readWarning |= newReadWarningParameter.GetBool("readWarning", False)
```

2021-08-20 14:41 UTC, chennes requested changes
One change needed...

2021-08-20 15:05 UTC, luzpaz commented
Added @chennes's commit and squashed. Ready for review

2021-08-21 13:48 UTC, luzpaz commented
@yorikvanhavre ready for review

2021-08-23 11:03 UTC, yorikvanhavre commented
That looks perfect! Thanks people!

2021-08-23 11:03 UTC, merged