grbl_post: correct G83 retract and return speeds
FreeCAD/FreeCAD pull request #3725
Opened 2020-07-22 19:58 UTC by J-Dunn

correct grbl post processor G83 expansion use rapid instead of tool speeds for  retract and return.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [x ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

2020-07-22 20:03 UTC, J-Dunn commented
Forgot to add to description that I have translated code comments  in drill_translate() to English. I have no problem reading french comments but others may not be polyglot. The code base probably wants to be consistent.

2020-08-09 12:27 UTC, luzpaz commented
* Is there a Forum thread associate with this PR?
* Sorry to be a nag again, but please for uniformity sake, correct the markdown in the initial post for the checkboxes. Thank you.

2020-10-01 09:58 UTC, J-Dunn commented
Here is the discussion thread, hopefully this can get merged.  The current drilling of air makes these canned cycles so slow as the be nearly worthless. The time drilling air ends up being most of the job's machine time :(

https://forum.freecadweb.org/viewtopic.php?f=15&t=25604&p=435639#p435639

2020-10-01 11:24 UTC, luzpaz requested changes

2020-10-01 11:24 UTC, luzpaz commented on src/Mod/Path/PathScripts/post/grbl_post.py
> +      trBuff += linenumber() + "G90" + "\n"  # force absolute coordonates during cycles
`s/coordonates/coordinates/`

2020-10-01 11:24 UTC, luzpaz commented on src/Mod/Path/PathScripts/post/grbl_post.py
> +    # get the other parametres
`s/parametres/parameters/`

2020-10-01 14:11 UTC, J-Dunn commented
Thanks for picking up those two typos. Can that be corrected when merging?  A new PR is a lot of effort for two letters in comments.

2020-10-02 11:48 UTC, luzpaz commented
New PR? That would be silly and defeats the purpose of using git.  
Do you not use git? I could make a PR to your repo and fix said typos, then all you have to do is push those changes to this PR. Would you be OK with that?

2020-10-02 17:13 UTC, J-Dunn commented
If the typos are important to you, go for it. 
I never managed to get git to connect from my Fedora box, so I use git to keep up to date with FC and then need to fork on github. Since github is pretty 'challenged' that's rather annoying.

2020-10-03 12:28 UTC, luzpaz commented
offtopic, Yea, I totally get it. I use a git GUI that made more sense to me. If you're interested checkout https://wiki.freecadweb.org/Developing_FreeCAD_with_GitKraken

2020-10-03 14:12 UTC, J-Dunn commented
thanks for the suggestion but I prefer to avoid closed source s/w. Besides that, GitKraken is based on electron , which while OSS is not managed by my distro. That means I need to monitor and anticipate things like this in one of the libraries electron includes:

https://www.npmjs.com/advisories/737

Since I don't have time to run my own distro , I have to trust someone else to vet stuff and stick to it :(

2020-10-04 02:04 UTC, luzpaz commented
As you wish. Just offering perspective on how to make your submission process easier.

2020-10-04 07:24 UTC, J-Dunn commented
I appreciate the helpful suggestion. 

Now is there anything apart from trivial typos in comments holding up a merge on this PR?

2020-10-04 13:10 UTC, luzpaz commented
> Now is there anything apart from trivial typos in comments holding up a merge on this PR?

ping @sliptonic @mlampert

2020-10-05 22:01 UTC, sliptonic commented
Looks ok to me.  Not sure why checks haven't finished but I'll merge as soon as they do.  @J-Dunn regarding the earlier type discussion that I missed.  You can always revise your own branch that the PR is based on and push it to github.  When the branch is updated, the PR is updated as well.   As long as no one is basing work on your PR branch, you can even push/force it.

2020-10-05 23:01 UTC, J-Dunn commented
Well if the checks are done by now I would not hold my breath. This PR is months old already.  Travis seems to be having a bit of a gender crisis recently so may not be working as well as "they" might be. 

I'll do a fresh PR with the typos fixed just to satisfy my OCD .

2020-10-06 00:27 UTC, J-Dunn commented
https://github.com/FreeCAD/FreeCAD/pull/3934

2020-10-06 00:47 UTC, J-Dunn commented
Closing this PR in favour of #3934

2020-10-06 00:47 UTC, closed without merging