[PartDesign] Hole countersink for metric
FreeCAD/FreeCAD pull request #3990
Opened 2020-10-22 14:07 UTC by berberic2

fix a problem with counterbore and countersink in PartDesign Hole feature.

It was not possible to custom define counterbores or countersinks if a
metric thread hole was selected.

Handle the cut-types None, Counterbore and Countersink euqal
regardless of type of thread and let the user customize:
None:        none
Counterbore: diameter and depth
Countersink: diameter and angle

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

2020-10-22 14:11 UTC, berberic2 commented
This replaces pull-request #3953 who was sitting around for 11 days, overhauld multiply times and finaly destroyed by #3988…

2020-10-23 00:03 UTC, donovaly requested changes
> It was not possible to custom define counterbores or countersinks if a
> metric thread hole was selected.

This PR would revert the fixes I just made today.
I thought the hole feature works now correctly:

* if no profile: you can customize everything
* if an ISO profile you can change the diameter if you have a countersink, but not the depth
* if an ISO profile you can change the depth if you have a counterbote, but not the diameter
* if you have an UTS profile you can also change the diemater for counterbores and depth for countersinks

I had a look yesterday and the ISO norms allow you to sink deeper less deep, while the other parameters are well defined.
If you need e.g. a different countersink angle, you must not use an ISO profile. Personally, I create derived holes by first selecting an ISO profile, select my size and cut, the switch to None profile and adjust e.g. the countersink angle. I think this is the right way since if the angle is not 90°, the hole is no ISO hole anymore.

> Handle the cut-types None, Counterbore and Countersink equal
> regardless of type of thread and let the user customize:

This would contradict the norms. The norms define certain values for good reason. If you are not following the norms, you are free to use the profile "None" to create everything you want.

2020-10-23 06:05 UTC, berberic2 commented
Hello,

you are aware that there are a lot of Screws defined in ISO that can
be sunk and all have different diameters and depths. There is no such
thing as a ISO-counterbore.

None means neither counterbore nore countersink.
Counterbores and Countersinks are universal and should be user-defineable
Cut-profile for a specific screw-type should be defineabel.

I see no reason to handle these three differently for different
threads-types.

MfG
bmg

Am Donnerstag, den 22. Oktober schrieb Uwe:
> @donovaly requested changes on this pull request.
> 
> > It was not possible to custom define counterbores or countersinks if a
> > metric thread hole was selected.
> 
> This PR would revert the fixes I just made today.
> I thought the hole feature works now correctly:
> 
> * if no profile: you can customize everything
> * if an ISO profile you can change the diameter if you have a countersink, but not the depth
> * if an ISO profile you can change the depth if you have a counterbote, but not the diameter
> * if you have an UTS profile you can also change the diemater for counterbores and depth for countersinks
> 
> I had a look yesterday and the ISO norms allow you to sink deeper less deep, while the other parameters are well defined.
> If you need e.g. a different countersink angle, you must not use an ISO profile. Personally, I create derived holes by first selecting an ISO profile, select my size and cut, the switch to None profile and adjust e.g. the countersink angle. I think this is the right way since if the angle is not 90°, the hole is no ISO hole anymore.
> 
> > Handle the cut-types None, Counterbore and Countersink equal
> > regardless of type of thread and let the user customize:
> 
> This would contradict the norms. The norms define certain values for good reason. If you are not following the norms, you are free to use the profile "None" to create everything you want.
> 
> > @@ -389,7 +389,7 @@ const char* Hole::ThreadSize_ISOmetricfine_Enums[]   = {
>      "M45x1.5",     "M45x2.0",     "M45x3.0",     "M45x4.0",
>      "M48x1.5",     "M48x2.0",     "M48x3.0",     "M48x4.0",
>      "M50x1.5",     "M50x2.0",     "M50x3.0",     "M52x1.5",
> -    "M52x2.0",     "M52x3.0",     "M52x4.0",     "M55x1.5",
> +    "M52x2.0",     "M52x3.0",     "M52x4.0",     "M55x1.5",
> 
> 
> Why this change?
> 


	MfG
	bmg

-- 
„Des is völlig wurscht, was heut beschlos- | M G Berberich
 sen wird: I bin sowieso dagegn!“          | mail@m-berberich.de
(SPD-Stadtrat Kurt Schindler; Regensburg)  |

2020-10-23 10:52 UTC, wwmayer commented on src/Mod/PartDesign/App/FeatureHole.cpp
> +    "M52x2.0",     "M52x3.0",     "M52x4.0",     "M55x1.5",
Seems like the editor added this. In many (command line) editors on Linux Windows line-endings are represented this way but that it really writes ^M into the file is strange.

2020-10-23 11:16 UTC, donovaly commented
> you are aware that there are a lot of Screws defined in ISO that can be sunk and all have different diameters and depths. There is no such thing as a ISO-counterbore.

I think we have a misunderstanding. There are different sizes defined, but when I'll need e.g. a hole for a M3 countersink screw, this hole is well defined. If I use another diameter than the defined one, it is no longer following the ISO norm.

Maybe I have not the correct norm he. I send you a private message in the forum so that you can send it to me if necessaqry.

> None means neither counterbore nore countersink.

You misunderstood me. With "None" I refer to the profile. This option allows you to change every parameter of a hole. The idea of the  profile is to follow as strict as possible the different norms.

> -- „Des is völlig wurscht, was heut beschlos- | M G Berberich sen wird: I bin sowieso dagegn!“

Why is this your motto? Dagegen sein ist immer einfach. Man bewegt nur etwas, wenn man FÜR etwas ist.

2020-10-23 11:20 UTC, berberic2 commented
Hello,,

Am Freitag, den 23. Oktober schrieb wwmayer:
> @wwmayer commented on this pull request.
> 
> 
> 
> > @@ -389,7 +389,7 @@ const char* Hole::ThreadSize_ISOmetricfine_Enums[]   = {
>      "M45x1.5",     "M45x2.0",     "M45x3.0",     "M45x4.0",
>      "M48x1.5",     "M48x2.0",     "M48x3.0",     "M48x4.0",
>      "M50x1.5",     "M50x2.0",     "M50x3.0",     "M52x1.5",
> -    "M52x2.0",     "M52x3.0",     "M52x4.0",     "M55x1.5",
> +    "M52x2.0",     "M52x3.0",     "M52x4.0",     "M55x1.5",
> 
> 
> Seems like the editor added this. In many (command line) editors on
> Linux Windows line-endings are represented this way but that it
> really writes ^M into the file is strange.

Yes. This was unintentional. Fixed it.

	MfG
	bmg

-- 
„Des is völlig wurscht, was heut beschlos- | M G Berberich
 sen wird: I bin sowieso dagegn!“          | mail@m-berberich.de
(SPD-Stadtrat Kurt Schindler; Regensburg)  |

2020-10-23 11:32 UTC, berberic2 commented
Am Freitag, den 23. Oktober schrieb Uwe:
> > you are aware that there are a lot of Screws defined in ISO that can be sunk and all have different diameters and depths. There is no such thing as a ISO-counterbore.
> 
> I think we have a misunderstanding. There are different sizes
> defined, but when I'll need e.g. a hole for a M3 countersink screw,
> this hole is well defined. If I use another diameter than the
> defined one, it is no longer following the ISO norm.

P.e.

There are two Torx countersunk screws defined in ISO:

ISO 14581: Hexalobular socket countersunk flat head screws
ISO 14582: Hexalobular socket countersunk head screws, high head

with different head diameters.

For M6 the head diameter is 13.2 mm for ISO 14582 and 12.6 mm for ISO
14581.

There are a lot of other countersunk-screws in ISO / EN / DIN some
with identical diameters, some with different ones.

> Maybe I have not the correct norm he. I send you a private message
> in the forum so that you can send it to me if necessaqry.
> 
> > None means neither counterbore nore countersink.
> 
> You misunderstood me. With "None" I refer to the profile. This
> option allows you to change every parameter of a hole. The idea of
> the profile is to follow as strict as possible the different norms.
> 
> > -- „Des is völlig wurscht, was heut beschlos- | M G Berberich sen wird: I bin sowieso dagegn!“
> 
> Why is this your motto? Dagegen sein ist immer einfach. Man bewegt
> nur etwas, wenn man FÜR etwas ist.

It isn’t. This is a quote from SPD-Stadtrat Kurt Schindler.

	MfG
	bmg

-- 
„Des is völlig wurscht, was heut beschlos- | M G Berberich
 sen wird: I bin sowieso dagegn!“          | mail@m-berberich.de
(SPD-Stadtrat Kurt Schindler; Regensburg)  |

2020-10-23 11:42 UTC, berberic2 commented
Am Freitag, den 23. Oktober schrieb Uwe:

> You misunderstood me. With "None" I refer to the profile.

Sorry 

> This option allows you to change every parameter of a hole. The idea
> of the profile is to follow as strict as possible the different
> norms.

It makes a lot of sense to be able to define countersink or
counterbore for a threaded hole.

Example:

With a None thread profile a Iso metric M3 unthreaded hole with close
fit and a countersink becomes a 3.3 mm hole with a countersink.

A lot of information is lost: It could be a threaded M4 hole or
unthreaded M3 hole. Maybe it’s not even meant for a screw at all.

	MfG
	bmg

-- 
„Des is völlig wurscht, was heut beschlos- | M G Berberich
 sen wird: I bin sowieso dagegn!“          | mail@m-berberich.de
(SPD-Stadtrat Kurt Schindler; Regensburg)  |

2020-10-24 00:46 UTC, donovaly commented
> For M6 the head diameter is 13.2 mm for ISO 14582 and 12.6 mm for ISO
14581.

Thanks! I did not now this. So the diameter must be changeable also for the ISO profiles.
What about the countersink angle. (Currently the hole feature allows to change it for the UTS profiles but not for the ISO profiles.)

Just to clarify, I am not the author of the hole feature, I only tried to fix it because I had to work with it recently and saw a lot if issues with it.

2020-10-24 08:46 UTC, berberic2 commented
I think the cut-types in Hole-Feature should offer:

· None
· Counterbore: fully customizabel by user, so he can create whatever counterbore he needs.
· Countersink: same as above

These three generic cut-types should work with all thread-types and no thread.

Then there should be settings for specific screwtypes, that create countersinks and -bores for standard screws. I would not hardcode these but read them from json-files¹.

I don’t think the “Cheesehead”, “Countersink socket screw” and “Cap Screw” types that are hardcoded into the hole feature and set the diameter and depth to some multiples of the hole-diameter are usefull at all. Personally, I would like to remove them, but are afraid this would cause backwards-compatibility problems.
__________
¹ https://forum.freecadweb.org/viewtopic.php?p=441911

2020-10-24 09:52 UTC, donovaly commented
> For M6 the head diameter is 13.2 mm for ISO 14582 and 12.6 mm for ISO 14581

Well, you confused me. Changing the diameter for countersinks is already possible, also for the ISO profiles. I implemented this this week,
As it is only the diameter is changeable, not the depth but the diameter changes the depth automatically. However for practical reasons, one wants to sink e.g. 0.5 mm deeper (which is of course allowed).
So changing the depth should alas be possible.

> I’m not aware of any DIN/EN/ISO screw with a angle different from 90°.

OK, then this should not be changeable if you use an ISO profile.

> https://forum.freecadweb.org/viewtopic.php?p=441911

Good, let's continue there. Is rynn your forum username?

2020-10-24 13:33 UTC, donovaly commented
> Good, let's continue there. Is rynn your forum username?

I opened a new thread: https://forum.freecadweb.org/viewtopic.php?f=19&t=51491 to discuss your intentions of this PR.

2020-10-25 21:57 UTC, donovaly commented
We found now out that editing all cut parameters should always be possible. This what your PR here does and it should go in.

On top of this are our further changes. Therefore I think to keep the overview this PR should go in first.

2020-10-31 13:41 UTC, berberic2 commented
included

2020-10-31 13:41 UTC, closed without merging

2020-10-31 23:44 UTC, donovaly commented
For information: I found a further typo in the hole diameter size list and made a PR that also updates to your diameter changes: #4010