Fixed bug: Importing IFC in Console raises error because it linked with FreeeCADGui module.
FreeCAD/FreeCAD pull request #4076
Opened 2020-11-23 12:50 UTC by amrit3701

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

2020-11-24 08:57 UTC, berndhahnebach commented
Have you tried just deleting the import of FreeCADGui? 

FreeCADGui is imported at the module beginning already. See https://github.com/FreeCAD/FreeCAD/blob/517f14b90e5352add4073db5ac0d095e532b97c6/src/Mod/Arch/ArchCommands.py#L27

I have no idea why it is imported multiple times in this module?

2020-11-24 09:47 UTC, amrit3701 commented
> Have you tried just deleting the import of FreeCADGui?
> 
> FreeCADGui is imported at the module beginning already. See
> 
> https://github.com/FreeCAD/FreeCAD/blob/517f14b90e5352add4073db5ac0d095e532b97c6/src/Mod/Arch/ArchCommands.py#L27
> 
> I have no idea why it is imported multiple times in this module?

@berndhahnebach Yes, you are right. There is no need to import FreeCADGui multiple time. Actually, during fixing this bug I haven't looked at the whole file. 

Fixed here: https://github.com/FreeCAD/FreeCAD/pull/4076/commits/4ddade87dd10f43042b091f4baafece60b52b786

2020-11-24 11:27 UTC, berndhahnebach commented
Would you update the PR branch? The merge would be very easy than.

2020-11-24 12:17 UTC, amrit3701 commented
> Would you update the PR branch? The merge would be very easy than.

Yes, I already pushed my commit in this PR. 


![image](https://user-images.githubusercontent.com/10414959/100093094-0b482800-2e7d-11eb-9398-b8076df9f7b4.png)

2020-11-24 20:10 UTC, luzpaz commented
@amrit3701 Can you amend the title fo the commit 517f14b90e5352add4073db5ac0d095e532b97c6
`s/FreeeCADGui/FreeCADGui/`

2020-11-28 15:04 UTC, amrit3701 commented
@yorikvanhavre @berndhahnebach I think now this PR is ready for merging. If any changes require please let me know, I will adopt suggestions.

2020-11-28 15:13 UTC, luzpaz commented
@amrit3701  ![image](https://user-images.githubusercontent.com/4140247/100518862-59ea1080-3162-11eb-8c4b-24c7a023ae98.png)

2020-12-01 14:01 UTC, yorikvanhavre requested changes

2020-12-01 14:02 UTC, yorikvanhavre commented on src/Mod/Arch/ArchCommands.py
> +    if not objects and FreeCAD.GuiUp:
(sorry for the "red flag", just experimenting with the review system ;) )

2020-12-01 14:51 UTC, amrit3701 commented on src/Mod/Arch/ArchCommands.py
> +    if not objects and FreeCAD.GuiUp:
@yorikvanhavre hi, no need to import `FreeCADGui` module here because it already imported at the top of this file.

2020-12-01 14:53 UTC, amrit3701 commented on src/Mod/Arch/ArchCommands.py
> +    if not objects and FreeCAD.GuiUp:
@yorikvanhavre see @berndhahnebach suggestion https://github.com/FreeCAD/FreeCAD/pull/4076#issuecomment-732753816

2020-12-01 15:00 UTC, yorikvanhavre commented on src/Mod/Arch/ArchCommands.py
> +    if not objects and FreeCAD.GuiUp:
perfect then! thanks!

2020-12-01 15:00 UTC, merged