Arch: connections between stair flight and landing
FreeCAD/FreeCAD pull request #4299
Opened 2021-01-21 17:43 UTC by three-ddd

Added some features to allow the user to change the types of connections between the flight of stairs and landing.
This issue is discussed in the forum thread: https://forum.freecadweb.org/viewtopic.php?f=22&t=53018

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, please confirm the following:

- [ ] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [ ] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.19 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=34586).

---

2021-01-21 22:01 UTC, hyarion requested changes
Due to the syntax error, the tests fails.
After fixing the issue, please run `./bin/FreeCAD --run-test 0` and verify that you get no errors.

2021-01-22 18:10 UTC, three-ddd commented
Thanks for your support, hyarion.
Done.

2021-01-22 22:29 UTC, hyarion commented on src/Mod/Arch/ArchStairs.py
> +                stepsI = 20
May I ask why this change has been made?
Why is 20 a better number than 16?

2021-01-22 22:32 UTC, hyarion commented
It now runs and there are no unit test errors ✅ 
My arch knowledge is close to non-existent so someone else needs to take it from here.

2021-01-23 02:48 UTC, paullee0 commented
@three-ddd I have a glance the overall changes without looking at details, looks great !

Note that your changes add the connection details to the Flight of Stairs and remove the 'projection' on the Landing.

Another idea is to add another parameter to the Landing whether to have that triangular connection details on the Landing.  So user can have even more control on each 'component.  Maybe add an issue to the bugtracker ?

Thanks !

2021-01-23 18:42 UTC, paullee0 commented
Tested a simple stairs with 3 flights, 2 landings and works great - [RC Stairs Macro](https://forum.freecadweb.org/viewtopic.php?f=22&t=53018&p=470151#p470151)

2021-01-24 20:02 UTC, three-ddd commented
Hi, paullee thank you for taking the time to check out my work, I'm grateful to you.
As you already know, I  attempted my first PR....but something went wrong!
As you can see GitHub reports that the test is failed.....and I still don't understand why.
Can someone please help me solve this problem? Many thanks.

Note: I developed code directly on GitHub account, so I have not worked locally on my computer.

My simple workflow on Github has been:
- I created a branch called "archstairs_connections_flight_landing", in my personal repo.
- In this new branch, I modified the ArchStairs.py file
- Last, I submitted the pull request

2021-01-25 00:02 UTC, paullee0 commented
> As you already know, I attempted my first PR....but something went wrong!
> As you can see GitHub reports that the test is failed.....and I still don't understand why.

I am also python and Github begginer :D 

It seems you should have solved by following @hyarion's finding and all checks have passed :D

Maybe wait @yorikvanhavre or other core developer to further review and merge.

2021-01-25 12:26 UTC, yorikvanhavre commented
Okay everything seems fine now, and code looks good, I can merge. Do you mind just replying @hyarion 's question, why 20 is better than 15, @three-ddd ?

2021-01-25 20:57 UTC, three-ddd commented
Yorik, thanks for the positive feedback and I really thank you for your awesome work on FC.

@hyarion sorry for the late reply.......I chose 20 as initial value because:

    3000 (preset value of "StairsHeight") / 20 = 150 mm < 180 mm (maximum riser height)

instead:

    3000 / 16 = 187.5 mm > 180 mm (maximum riser height)


![range_riser_height_stairs_colored resize](https://user-images.githubusercontent.com/75747159/105764908-e729c580-5f57-11eb-9749-fcae12c9496b.png)

2021-01-25 21:23 UTC, hyarion commented
> @hyarion sorry for the late reply.......

No worries :)

> I chose 20 as initial value because:
> ```
> 3000 (preset value of "StairsHeight") / 20 = 150 mm < 180 mm (maximum riser height)
> ```
> instead:
> ```
> 3000 / 16 = 187.5 mm > 180 mm (maximum riser height)
> ```

Well explained @three-ddd, thanks! 👍

2021-01-26 15:29 UTC, paullee0 commented
@three-ddd Indeed 20 steps better for default 3000m high staircase.

2021-01-26 20:50 UTC, three-ddd commented
Hi @yorikvanhavre, 
some bugs were found, about:

- "Riser Thickness", when its value  > 0 the connection's result is not geometrically correct.

- when you set property "Structure" to "One Stringer" or "Two Stringers" options, the stair geometry fails.

Reference discussion [here](https://forum.freecadweb.org/viewtopic.php?f=22&t=53018&start=20)


> @three-ddd Indeed 20 steps better for default 3000m high staircase.

Thanks @paullee0!

2021-01-26 20:55 UTC, three-ddd commented
> Well explained @three-ddd, thanks!

you are welcome @hyarion!

2021-02-05 12:26 UTC, yorikvanhavre commented
@three-ddd I think this is good for merge now.. Since this modifies functionality and we are in feature-freeze mode, I'll mark it to postpone to after the 0.19 release. Could you remove the "draft" status when you feel ready?
About the 2 bugs you found, I guess there are many more... The stair tool needs a lot of work still :)

2021-02-05 21:47 UTC, three-ddd commented
Thank Yorik.....you are right the stairs tool needs a lot of work yet ;)

2021-03-30 11:17 UTC, merged

2021-03-30 17:33 UTC, paullee0 commented
Great!  Look forward to more contribution from @three-ddd :D

2021-04-20 18:07 UTC, paullee0 commented
@three-ddd Could you mark your commit is merged ?  :D

2021-04-26 17:03 UTC, three-ddd commented
> Great! Look forward to more contribution by @three-ddd :D

Thanks paullee, I hope I shall not disappoint your expectations! :D


> @three-ddd Could you mark your commit is merged ?  :D

How can I do that?

2021-04-26 17:09 UTC, paullee0 commented
Just edit your 1st post in FreeCAD forum and add e.g. [Merge] in the begining of the topic :)

2021-04-26 17:13 UTC, three-ddd commented
> Just edit your 1st post in FreeCAD forum and add e.g. [Merge] in the begining of the topic :)

Thanks, @paullee0, for your speedy response!

2021-04-26 18:34 UTC, three-ddd commented
> Just edit your 1st post in FreeCAD forum and add e.g. [Merge] in the begining of the topic :)

Hi @paullee0, I tried that, but it did change only title of my first post :(

![first_post](https://user-images.githubusercontent.com/75747159/116133222-bed47300-a6ce-11eb-809f-1ba02576ccc5.jpg)