[Gui] Issue #3923 - Add arbitrary Tree View item ordering
FreeCAD/FreeCAD pull request #4626
Opened 2021-03-16 20:34 UTC by pavltom

This pull request gives the user a possibility to reorder the document tree view items.

For more implementation details please see my contribution to the dedicated forum topic:

[Ticket #3923 - change order in tree view](https://forum.freecadweb.org/viewtopic.php?f=3&t=35316)

2021-03-17 06:03 UTC, adrianinsaval commented
Compiles and runs but there are issues with the implementation I have commented here: https://forum.freecadweb.org/viewtopic.php?f=3&t=35316&p=488236#p488236

2021-03-17 09:38 UTC, ickby commented
The viewprovider tree rank is neitehr readable, writable or observable by document observer from python. As it is a defining attribute for the viewprovider this needs to change. 
Maybe implementing it as hidden property makes it easier and more consistent within freecad?

2021-04-17 13:08 UTC, thebravoman commented
For what it is worth, I've been in the CAD/Engineering world for decade, I installed FreeCAD and the first thing I did is add two parts and tried to reorder the parts in the tree viewer.

Looking forward to this PR

2021-04-24 09:03 UTC, ickby commented
Thanks for the changes, looks fine for me! Two minor things that could be improved: 
1. Use the new functionality for App::Group and App::Part as those are most likely the two candidate objects for the new API
2. Write a test for the functionality to check if reordering works and is prevented correctly if it should not work

2021-06-03 18:13 UTC, pavltom commented
Hi, I have used the possibility to disable children movement for basic document objects like Body (and all OriginGroupExtensions), Origin document object, Part Boolean object, Loft, Sweep (Pipe) and Thickness features both in Part and PartDesign. For the App::DocumentObjectGroup object, movement remains allowed, I do not see any reason why it should be restricted. Nevertheless, I am pretty much sure there are lots of other places, where moving children is not desirable, however I would let apply this to their respective maintainers. 
As for the tests, I have added a TreeView.py test, which tests the functionality both for items allowing and restricting child item movement. I believe this test is sufficient, but for sure it can be expanded to other item types or different scenarios.

2021-09-24 11:50 UTC, berndhahnebach commented
Following a link to the branch on the CI-repository:

https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_5060

The CI-status is available on the latest commit of the branch.
If there is no status available the PR should be rebased on latest master.
Check pipeline branches to see if your PR has been run by the CI.

https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches

2021-10-01 06:02 UTC, freecadci commented
<a href="https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_4626"><img alt="pipeline status" src="https://gitlab.com/berndhahnebach/FreeCAD/badges/PR_4626/pipeline.svg" /></a> for feature branch [PR_4626](https://gitlab.com/berndhahnebach/FreeCAD/-/commits/PR_4626). Pipeline [#380645184 ](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines/380645184) was triggered at [214972f](https://github.com/FreeCAD/FreeCAD/pull/4626/commits/214972ffb5529a9747a32c7f1f61ea9b4a44866b). All CI branch [pipelines](https://gitlab.com/berndhahnebach/FreeCAD/-/pipelines?scope=branches).

2021-10-01 17:27 UTC, chennes requested changes
Nice addition! Thanks especially for adding the test cases. I left a couple tiny comments on the code (which overall looks really solid), and some feedback on the overall behavior.

When I move an expanded group _up_ the list, it stays open, but when I move it _down_, it collapses. This is also true if I move another object "across" the open group: it collapses if the motion is upward, but stays open if the motion is down. I personally prefer the stay-open behavior, but at the least I think it should be the same in all cases.

I also think that the multiple-selection behavior is counter-intuitive. When I have multiple objects selected and ask them to move, I felt like I was asking ALL of them to move, and then only one of them did.

Otherwise it looks to me like this is pretty much ready to merge. Thanks!

2021-10-01 17:27 UTC, chennes commented on src/Gui/CommandView.cpp
> +    sMenuText    = QT_TR_NOOP("Move Up in Group");
```suggestion
    sMenuText    = QT_TR_NOOP("Move up in group");
```

2021-10-01 17:27 UTC, chennes commented on src/Gui/CommandView.cpp
> +    sMenuText    = QT_TR_NOOP("Move Down in Group");
```suggestion
    sMenuText    = QT_TR_NOOP("Move down in group");
```

2021-10-31 00:53 UTC, chennes commented
Thanks for the changes -- I will re-review shortly.

2021-11-11 05:35 UTC, merged

2021-11-19 18:04 UTC, chennes commented
@pavltom It appears this is causing some problems, can you please have a look at https://forum.freecadweb.org/viewtopic.php?f=3&t=63744 ? Thanks.