[TD] Name uniformity for TechDraw_Tree Icons
FreeCAD/FreeCAD pull request #4779
Opened 2021-05-07 16:16 UTC by bitacovir

Many TechDraw icons don't follow name conventions and are not SVG plain format. Help to fix this was required.

This commit replaces a group of SVG files (Tree_*) with plain SVG format and changes their names following FC convention.  Also, it makes the necessary changes on TechDraw.qrc files, and several cpp files.

Forum Discussion: https://forum.freecadweb.org/viewtopic.php?f=34&t=58401

2021-05-07 18:44 UTC, luzpaz approved these changes

2021-05-07 18:50 UTC, luzpaz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreeHatch.svg
> +        <dc:identifier>FreeCAD/src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Tree_Hatch.svg</dc:identifier>
rename

2021-05-07 18:57 UTC, luzpaz requested changes
Pending merge from https://github.com/bitacovir/FreeCAD/pull/1

2021-05-07 18:57 UTC, luzpaz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreePage.svg
> +        <dc:identifier>FreeCAD/src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Tree_Page.svg</dc:identifier>
rename

2021-05-07 18:57 UTC, luzpaz commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreeMulti.svg
> +        <dc:title>TechDraw_Tree_Multi</dc:title>
rename

2021-05-07 20:43 UTC, bitacovir commented on src/Mod/TechDraw/Gui/Resources/icons/TechDraw_TreeMulti.svg
> +        <dc:identifier>FreeCAD/src/Mod/TechDraw/Gui/Resources/icons/TechDraw_Tree_Multi.svg</dc:identifier>
All 11 done :)

2021-05-07 20:44 UTC, bitacovir commented
@luzpaz All svg files checked and updated.

2021-05-08 16:32 UTC, luzpaz approved these changes
LGTM

2021-05-12 13:38 UTC, merged