Base: Adding stiffness units
FreeCAD/FreeCAD pull request #4963
Opened 2021-08-12 10:19 UTC by Helios113

Added stiffness units to FreeCAD and updated lexer

2021-08-12 14:00 UTC, AjinkyaDahale reviewed
The commit message is too vague. Remember that once merged, only the commit message will be visible. So "squashed commits" won't tell as much as "added stiffness units" or something to that accord would.

2021-08-12 15:05 UTC, Helios113 commented
Added new commit message.

2021-08-12 15:18 UTC, berndhahnebach commented
https://github.com/FreeCAD/FreeCAD/pull/4913

2021-08-13 08:20 UTC, phopfgartner commented
In src/Base/Unit.cpp, the line
    if(*this == Unit::Stiffness                   )       return QString::fromLatin1("Power");
looks like it contains a copy paste error.

2021-08-13 10:47 UTC, luzpaz requested changes

2021-08-13 10:47 UTC, luzpaz commented on src/App/FreeCADInit.py
> +App.Units.MegaNewtonPerMeter   = App.Units.Quantity('MN/m')
please stack the `=` in a column to be uniform like the code around it

2021-08-13 10:47 UTC, luzpaz commented on src/Base/Quantity.cpp
> +Quantity Quantity::MegaNewtonPerMeter   (1e6          ,Unit(0,1,-2));
Please line up the first parethesis in each line over each other + the same the `,Unit`

2021-08-13 10:47 UTC, luzpaz commented on src/Base/Unit.cpp
> +    if(*this == Unit::Stiffness                   )       return QString::fromLatin1("Power");
Probably should be `Stiffness` right?

2021-08-13 10:47 UTC, luzpaz commented on src/Base/UnitsSchemaImperial1.cpp
> +    else if (unit == Unit::Stiffness) { //Make better, a
Comment is incomplete

2021-08-13 10:48 UTC, luzpaz commented on src/Base/Unit.cpp
> +    if(*this == Unit::Stiffness                   )       return QString::fromLatin1("Power");
Per https://github.com/FreeCAD/FreeCAD/pull/4963#issuecomment-898278264

2021-08-16 11:45 UTC, Helios113 commented
Changes applied, I hope it squashed correctly.

2021-08-16 13:50 UTC, luzpaz commented
Thanks @Helios113 for the PR and your work on it. Follow up question: there are lots of changes in `src/Base/QuantityLexer.c` was this in the previous PR as well? (I don't recall it but I may be mistaken)

@berndhahnebach @donovaly @phopfgartner please weigh-in at your convenience

2021-08-16 13:59 UTC, Helios113 commented
It was not in originally in the previous commit. It was brought up in #4913, I made the changes and then the rebase messed up the commit history, so this is the first PR where you can see it.

There are a lot of changes there but the whole file was generated with flex. Hence, the changes were automatically applied. As far as I could see, the changes are mostly incrementing numbers and adding the stiffness information.

2021-08-17 20:35 UTC, donovaly commented
> Thanks @Helios113 for the PR and your work on it. Follow up question: there are lots of changes in `src/Base/QuantityLexer.c`

That is correct. This file is auto-generated by flew, see my comment: https://github.com/FreeCAD/FreeCAD/pull/4913#pullrequestreview-724857604

2021-08-17 20:35 UTC, donovaly approved these changes
From my point of view the PR is ready to be merged. I am currently traveling abroad and can therefore not check if everything compiles. If it does, from the code perspective everything is fine and my requested changes/additions were applied correctly.

2021-08-17 22:39 UTC, luzpaz commented
@berndhahnebach please review, thx!

2021-08-18 08:04 UTC, yorikvanhavre commented
Ok looks good to me too. Ahoy!

2021-08-18 08:04 UTC, merged