[TD] avoid memory leaks by using shared_ptr
FreeCAD/FreeCAD pull request #5323
Opened 2022-01-03 16:28 UTC by WandererFan

TD geometry objects are sometimes double deleted.  This change uses shared_ptr instead of raw pointers to manage
deletions.

An expansion of the patch discussed here: [forum topic](https://www.forum.freecadweb.org/viewtopic.php?p=535784#p535784l) to BaseGeometry and derived classes.

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

2022-01-03 16:57 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +    m_geometry = std::make_shared<TechDraw::BaseGeom> (BaseGeom());
The call of BaseGeom() inside the parentheses can be dropped. What it does is create an instance on the stack and afterward it invokes the default copy constructor. So, this should be sufficient: `m_geometry = std::make_shared<TechDraw::BaseGeom> ();`

2022-01-03 16:58 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +    //shared pointer will delete m_geometry when ref count goes to zero.
The commented code should be removed but if you like you can keep the comment.

2022-01-03 17:01 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +        TechDraw::GenericPtr gen = std::make_shared<TechDraw::Generic> (TechDraw::Generic());
Drop the call of TechDraw::Generic()

2022-01-03 17:01 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +        TechDraw::CirclePtr circ = std::make_shared<TechDraw::Circle> (TechDraw::Circle());
Drop the call of TechDraw::Circle()

2022-01-03 17:02 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +        TechDraw::AOCPtr aoc = std::make_shared<TechDraw::AOC> (TechDraw::AOC());
Drop the call of TechDraw::AOC()

2022-01-03 17:02 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +    m_geometry = std::make_shared<TechDraw::BaseGeom> (TechDraw::BaseGeom());
Drop the call of TechDraw::BaseGeom()

2022-01-03 17:03 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +        TechDraw::GenericPtr gen = std::make_shared<TechDraw::Generic> (TechDraw::Generic());
Drop the call of TechDraw::Generic()

2022-01-03 17:03 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +        TechDraw::CirclePtr circ = std::make_shared<TechDraw::Circle> (TechDraw::Circle());
Drop the call of TechDraw::Circle()

2022-01-03 17:54 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +        m_geometry = (TechDraw::BaseGeomPtr) gen;
The C-style cast can be dropped

2022-01-03 17:55 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +        m_geometry = (TechDraw::BaseGeomPtr) circ;
The C-style cast can be dropped.

2022-01-03 17:56 UTC, wwmayer commented on src/Mod/TechDraw/App/Cosmetic.cpp
> +        m_geometry = (TechDraw::BaseGeomPtr) aoc;
The C-style cast can be dropped

2022-01-03 17:58 UTC, wwmayer commented on src/Mod/TechDraw/App/CosmeticEdgePyImp.cpp
> +    getCosmeticEdgePtr()->m_geometry = std::make_shared<TechDraw::Circle> (TechDraw::Circle(getCosmeticEdgePtr()->permaStart, r));
Use `getCosmeticEdgePtr()->m_geometry = std::make_shared<TechDraw::Circle> (getCosmeticEdgePtr()->permaStart, r);`

2022-01-03 17:59 UTC, wwmayer commented on src/Mod/TechDraw/App/CosmeticEdgePyImp.cpp
> +    getCosmeticEdgePtr()->m_geometry = std::make_shared<TechDraw::Circle> (TechDraw::Circle(getCosmeticEdgePtr()->permaStart, oldCircle->radius));
Drop the call of TechDraw::Circle() as above.

2022-01-03 17:59 UTC, wwmayer commented on src/Mod/TechDraw/App/DrawParametricTemplate.cpp
> +//    for(std::vector<TechDraw::BaseGeomPtr>::iterator it = geom.begin(); it != geom.end(); ++it) {
Remove the commented code.

2022-01-03 18:01 UTC, wwmayer commented on src/Mod/TechDraw/App/DrawViewPart.cpp
> +    BaseGeomPtr result = nullptr;
Assigning nullptr is OK but not required.

2022-01-03 18:02 UTC, wwmayer commented on src/Mod/TechDraw/App/DrawViewPartPyImp.cpp
> +    TechDraw::BaseGeomPtr bg = std::make_shared<TechDraw::AOC> (TechDraw::AOC(pnt1, radius, angle1, angle2));
The call of TechDraw::AOC() can be dropped.

2022-01-03 18:03 UTC, wwmayer commented on src/Mod/TechDraw/App/Geometry.cpp
> +        result = std::make_shared<BaseGeom>(BaseGeom());
The call of BaseGeom() can be dropped.

2022-01-03 18:09 UTC, wwmayer commented on src/Mod/TechDraw/App/Geometry.cpp
>      std::unique_ptr<BaseGeom> result;
BaseGeomPtr is declared as std::shared_ptr so result should be a shared_ptr too, although a shared_ptr accepts a unique_ptr.

2022-01-03 18:13 UTC, wwmayer requested changes
Please have a look at all my comments.

2022-01-03 18:26 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5323"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_5323/pipeline.svg"/></a> for feature branch [PR_5323](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5323). Pipeline [440637543](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/440637543) was triggered at [60c41f9](https://github.com/FreeCAD/FreeCAD/pull/5323/commits/60c41f9182bfad172294add7235f8b86a5751809). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-01-03 19:18 UTC, WandererFan commented
How are we handling commit history for changes due to code review?  I would say 1 clean commit with the original changes + review changes squashed together, but I'll go with our standard.

2022-01-04 03:21 UTC, donovaly commented
> How are we handling commit history for changes due to code review?

There are no defined rules. Common is that the user makes the requested change, rebase and force-push this. The history of a PR is not of interest.
Personally I try to have only one commit per PR, except to keep the overview or for technical reasons.

2022-01-04 18:50 UTC, WandererFan commented
> Please have a look at all my comments.

Excellent review!  Thank you very much.

2022-01-04 22:50 UTC, luzpaz commented
Addendum: try to preprend `[TD]` (or whatever workbench you're touching) to the commit summary names. That way we can easily parse the git history

2022-01-07 16:29 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5323"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_5323/pipeline.svg"/></a> for feature branch [PR_5323](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_5323). Pipeline [443596420](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/443596420) was triggered at [ec24725](https://github.com/FreeCAD/FreeCAD/pull/5323/commits/ec2472569fee0f14039651e1fbcc050cc87ae687). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-01-07 18:34 UTC, merged