PartDesign::SubShapeBinder add 2D offsetting
FreeCAD/FreeCAD pull request #6338
Opened 2022-02-10 22:23 UTC by mwganson

Adds 2D offsetting of wires, edges, and face types.

Adds new "Offsetting" group to the green Part Design SubShapeBinders.  In this group:

Offset (float) the amount of 2D offset (in mm).  If Offset = 0.0, then no offsetting is done.  Can be positive or negative (for offsetting inwards).
OffsetJoinType (enumeration).  Values are "Arcs", "Tangent", "Intersection".
OffsetFill (boolean).  If True a face is made between the original wire and the offset.  (see image below)
OffsetOpenResult (boolean).  If False when offsetting an open wire a closed wire is produced.  If True, the open result is allowed.
OffsetIntersection (boolean).  Affects the way inner wires are offset relative to parent wire, inwards or outwards.

![Snip macro screenshot-623c80](https://user-images.githubusercontent.com/39143564/153505917-d720af7d-c97a-42dd-a7c0-1d08ce19c8c9.png)

2022-02-10 22:50 UTC, mwganson commented
https://forum.freecadweb.org/viewtopic.php?f=19&t=66177

2022-02-10 22:51 UTC, mwganson commented
Converted to Draft mode.  I have found a crash while testing.

2022-02-10 23:33 UTC, mwganson commented
Direct link to file that reproduces crash (without need to build the PR).  You must install WireFilter macro and run it once before opening the crash file.  Open it, and then set the WireFilter object "OffsetFill" property to True.

[file](https://forum.freecadweb.org/download/file.php?id=179083)

2022-02-11 09:25 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6338/pipeline.svg"/></a> for feature branch [PR_6338](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338). Pipeline [468687060](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/468687060) was triggered at [fe97374](https://github.com/FreeCAD/FreeCAD/pull/6338/commits/fe97374143020794fcc3a4a9255a2776d14a2309). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-02-20 08:25 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6338/pipeline.svg"/></a> for feature branch [PR_6338](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338). Pipeline [475139146](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/475139146) was triggered at [361075a](https://github.com/FreeCAD/FreeCAD/pull/6338/commits/361075aecca233aacd01e80843f0c287687d711b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-02-21 05:04 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6338/pipeline.svg"/></a> for feature branch [PR_6338](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338). Pipeline [475439142](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/475439142) was triggered at [9c96742](https://github.com/FreeCAD/FreeCAD/pull/6338/commits/9c96742dea8b536a95c527f125bb316383c53b1b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-03-09 17:50 UTC, donovaly commented
Many thanks! For reviewing, can you please give me in the forum a step by step explanation on how e.g. make an offset of a face of a cube?

Since you use BRepOffsetAPI_MakeOffsetFix, can you please check that your feature is not too suffering from this issue: #6538

2022-03-09 17:51 UTC, donovaly requested changes

2022-03-09 17:51 UTC, donovaly commented on src/Mod/Part/App/TopoShape.cpp
> -            builder.Add(result, sh);
Can you please make a separate PR just for this. Just for technical reason to help me with the review.

2022-03-09 18:49 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6338/pipeline.svg"/></a> for feature branch [PR_6338](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338). Pipeline [488398012](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/488398012) was triggered at [c4d4171](https://github.com/FreeCAD/FreeCAD/pull/6338/commits/c4d41712503035b3a981a71e8d9ed418e6e0a1b8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-03-09 19:06 UTC, donovaly commented
Despite your crash fix does not fix the mentioned crash, I would like to commit as a separate PR to distinguish it from the new feature.

2022-03-10 18:59 UTC, mwganson commented
I will submit a different PR for the crash fix.

2022-03-10 19:24 UTC, mwganson commented
Steps to make the offset using the binder.

https://forum.freecadweb.org/viewtopic.php?f=19&t=66177&p=578501#p578501

2022-03-10 19:26 UTC, mwganson commented
The other separated PR is ready to submit, but I am waiting for the build to complete so I can be sure it compiles and to run the unit tests.

2022-03-12 03:47 UTC, donovaly approved these changes
Many thanks for the extra PR

2022-03-12 03:48 UTC, donovaly commented
Thanks for the feature. I tested it and looked at the code, both is fine.

For the future a Task dialog would be useful because with this one would see the changes to the offset immediately.
However this is the FC 0.21 stuff.

I cannot merge because of a merge conflict. Can you therefore please rebase?

2022-03-12 21:50 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6338/pipeline.svg"/></a> for feature branch [PR_6338](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6338). Pipeline [490728509](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/490728509) was triggered at [ef0dcc0](https://github.com/FreeCAD/FreeCAD/pull/6338/commits/ef0dcc02fe017411de43885e4d2f006e05789f1b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-03-12 22:30 UTC, merged