Generator and Test for Keyhole Path
FreeCAD/FreeCAD pull request #6464
Opened 2022-02-27 15:20 UTC by wayofwood

This is adding a T-Slot toolbit to the path workbench and provides the Generator for a Keyhole Toolpath as discussed in the following [Forum post](https://forum.freecadweb.org/viewtopic.php?style=5&f=15&t=65416).

2022-02-27 15:24 UTC, luzpaz requested changes

2022-02-27 15:24 UTC, luzpaz commented on src/Mod/Path/Generators/keyhole_generator.py
> +# *   Copyright (c) 2021 wayofwood <code@wayofwood.com>               *
Fix spacing (also please use single whitespaces instead of tabs)

2022-02-27 15:24 UTC, luzpaz commented on src/Mod/Path/PathTests/TestPathKeyHoleGenerator.py
> +# *   Copyright (c) 2021 wayofwood <code@wayofwood.com>               *
same

2022-02-27 16:37 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6464"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6464/pipeline.svg"/></a> for feature branch [PR_6464](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6464). Pipeline [480389237](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/480389237) was triggered at [814c87b](https://github.com/FreeCAD/FreeCAD/pull/6464/commits/814c87bcb91c91b4a58782592e7959ca0923e46d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-03-13 09:54 UTC, luzpaz commented
@wayofwood I've made a PR to your branch in https://github.com/wayofwood/FreeCAD/pull/1

2022-03-14 06:54 UTC, wayofwood commented
Thanks - really appreciate your help. I am still trying to get my head around all the git workflow ...

2022-03-14 08:07 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6464"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6464/pipeline.svg"/></a> for feature branch [PR_6464](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6464). Pipeline [491259454](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/491259454) was triggered at [bae516e](https://github.com/FreeCAD/FreeCAD/pull/6464/commits/bae516e65929f1abf1ac32bf4eba71f4773879fb). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-03-14 12:55 UTC, luzpaz commented
@donovaly codespell ci is reporting typos of the full codebase (rather than just text of the PR changes) any idea why?

2022-03-14 13:03 UTC, luzpaz commented
> Thanks - really appreciate your help. I am still trying to get my head around all the git workflow ...

@wayofwood I totally get it. Keep practicing it make more sense as you use it more often. https://wiki.freecad.org/Github has a primer on how to git. Key milestone for me was learning about the difference between `git merge` and `git rebase`. If you have git questions drop them in to the forum, someone will help you out for sure.

2022-03-14 15:50 UTC, donovaly commented
> @donovaly codespell ci is reporting typos of the full codebase (rather than just text of the PR changes) any idea why?

I don't know. Sometimes this happens.
However, this particular report must be ignored since "detet" is a desired letter sequence as wandererfan told me recently.

Concerning the CI spellchecker, what could be improved is that it also checks *.hpp, *.hxx and *.cxx files. Can you please report this request to the people who can do this? I don't know who kindly setup the spellchecker, I am just a happy user of it ;-)

2022-03-14 19:48 UTC, luzpaz approved these changes

2022-03-27 08:52 UTC, Floriansimmer commented
@donovaly @luzpaz Just a guessing from my side: Codespell checking is performed on all changed files, and since there is a merge from the master to the branch, the files that have been changed on master since the branch was created are also checked.

*.hpp, *.hxx and *.cxx files should be checked 🤔. The CI only ignores https://github.com/FreeCAD/FreeCAD/blob/7676216a7a9b501c2cfad81fa4ce3c5585898479/.github/workflows/codespell.yml#L30 

To add a word to the ignored missspellings just modify https://github.com/FreeCAD/FreeCAD/blob/master/.github/codespellignore 

see: https://github.com/FreeCAD/FreeCAD/pull/6666

2022-03-27 13:50 UTC, donovaly commented
> *.hpp, *.hxx and *.cxx files should be checked 🤔. 

I know, but I don't know how to activate this.

2022-11-09 00:18 UTC, sliptonic commented
Interest in the PR seems to have fallen off.  Code review items were never addressed.  It will need rebasing now that the Path source has been reorganized.  I'm closing this now but encourage OP to resubmit it in the future.  If you do, please create an issue first.

2022-11-09 00:18 UTC, closed without merging

2022-11-09 00:57 UTC, luzpaz commented
Ping @wayofwood