Techdraw [skip ci] Fix problem with translation.
FreeCAD/FreeCAD pull request #6931
Opened 2022-05-29 07:24 UTC by Kuzma30

Switch from QT_TRANSLATE_NOOP to QtGui.QApplication.translate.
This solves issues 145-147 from https://github.com/FreeCAD/FreeCAD-translations/issues

2022-05-29 07:31 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6931"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6931/pipeline.svg"/></a> for feature branch [PR_6931](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6931). Pipeline [550514301](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/550514301) was triggered at [77f8e54](https://github.com/FreeCAD/FreeCAD/pull/6931/commits/77f8e545ca74d777624f0eb763e5777e7aaba426). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-05-29 11:10 UTC, luzpaz commented
CC @yorikvanhavre does this look correct?

2022-05-29 13:16 UTC, Kuzma30 commented
https://github.com/FreeCAD/FreeCAD-translations/issues/147
Here is problem description.

2022-05-29 16:45 UTC, benj5378 commented on src/Mod/TechDraw/TechDrawTools/CommandShareView.py
> +from PySide import QtCore
Why is `from PySide import QtCore`? Isn't it unused?
```suggestion
```

2022-05-29 16:45 UTC, benj5378 commented on src/Mod/TechDraw/TechDrawTools/CommandMoveView.py
> +from PySide import QtCore
Why is `from PySide import QtCore`? Isn't it unused?
```suggestion
```

2022-05-29 17:19 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6931"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_6931/pipeline.svg"/></a> for feature branch [PR_6931](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_6931). Pipeline [550663471](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/550663471) was triggered at [1e9ed1e](https://github.com/FreeCAD/FreeCAD/pull/6931/commits/1e9ed1e6c99e784f4a2402f12ef4c322400001e4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-05-29 17:44 UTC, Kuzma30 commented
@benj5378 Thanks for review

2022-05-29 22:01 UTC, donovaly commented
@Kuzma30 , please let the CI run over your PRs. There can always be a typo and the CI will find it.

2022-05-29 22:09 UTC, chennes commented on src/Mod/TechDraw/TechDrawTools/CommandMoveView.py
> +                'ToolTip': QtGui.QApplication.translate("MoveView", "Move a View to a new Page", None)}
This change isn't correct: menu text and tooltips should use NOOP to add them to the translation database. The actual translation occurs elsewhere.

2022-05-29 22:20 UTC, chennes requested changes
The changes to the menu text and tooltip are incorrect, and throughout the file I believe the context is wrong for all translations. The name of the command is "TechDraw_MoveView", not just "MoveView".

2022-05-30 15:31 UTC, Kuzma30 commented
@yorikvanhavre @chennes May be I recreate PR? I think only change context (add TechDraw_ suffix) All other thing may be as is.

2022-05-30 18:21 UTC, chennes commented
Yeah, that's probably a good idea.

2022-05-31 04:16 UTC, closed without merging