Remove old msc ver. Freecad 0.20 require 64 bit and windows 7 or higher. For this reason, msc libraries less than 1800 will no longer be used.
FreeCAD/FreeCAD pull request #7036
Opened 2022-06-17 07:55 UTC by mosfet80

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

2022-06-17 08:01 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7036"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7036/pipeline.svg"/></a> for feature branch [PR_7036](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7036). Pipeline [566207706](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/566207706) was triggered at [aba0045](https://github.com/FreeCAD/FreeCAD/pull/7036/commits/aba00455b18084883e1624e39a46c2c73324ed73). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-06-19 13:42 UTC, donovaly commented
Thanks for this PR.

However, despite we don't offer 32bit Windows builds anymore, some users might want to build this on their own. Therefore I would not remove this possibility from the code. Before this is done, a discussion should take place if everybody agrees to this.

Can you therefore please rebase you PR and only commit the MSC changes?

2022-06-19 14:13 UTC, yorikvanhavre commented
I agree with @donovaly ... for me having the code as widely compatible as possible is more important than having clean code. There might be people using the FreeCAD codebase out there in ways we don't imagine (for ex on embedded systems, etc), and itws good to keep things as open and easy to port as possible

2022-06-25 12:59 UTC, donovaly commented
I would merge the PR but it contains now 7 commits and it is hard to see what was actually changed.

@mosfet80 when you update your branch do this:
- pull from master int your branch
- in the log select the merge change and your change and combine them to one commit
- force-push the resulting single commit

If that does not work your you, then rebase your branch on master and force-push.
People in the developer's forum can help you with this because the optimal strategy depends on the Git tools you use.

2022-06-26 20:24 UTC, donovaly commented
@mosfet80 , have you seen my previous comment? Now you have 10 commits in this PR. Please avoid this otherwise we cannot merge the PR easily.

2022-06-26 22:49 UTC, donovaly requested changes
Please only make changes that remove the MSC code. This assures a clean commit history. Further changes can be done in a separate PR.

2022-06-26 22:49 UTC, donovaly commented on src/Base/MemDebug.cpp
> +   logFile = fopen( "MemLog.txt", "w" );
Why this addition?

2022-06-26 22:49 UTC, donovaly commented on src/Mod/Drawing/Gui/TaskOrthoViews.cpp
> -    //this_view->Direction.setValue(Z_dir.X(), Z_dir.Y(), Z_dir.Z());
In principal OK, but has nothing to do with msc.

Please only make changes related to MSC in this PR.

2022-06-26 22:49 UTC, donovaly commented on src/Gui/PreferencePackTemplates/View.cfg
> +          <FCBool Name="ShowAxisCross" Value="0/>
This would introduce a bug

2022-06-26 22:49 UTC, donovaly commented on src/FCConfig.h
> -#   define HAVE_INT8_T
These must stay. You added them later but with wrong indentation

2022-06-26 22:49 UTC, donovaly commented on src/FCConfig.h
> +#  		define FC_OS_WIN32
Indentation seems wrong. In the change above it is correct.

2022-06-26 22:49 UTC, donovaly commented on src/Base/StackWalker.h
> +
not necessary for the PR

2022-06-26 22:49 UTC, donovaly commented on src/Base/StackWalker.cpp
> -
not necessary for the PR

2022-06-26 22:49 UTC, donovaly commented on src/Base/MemDebug.cpp
> -  //_CrtCheckMemory( );
No change in this file is necessary for the PR

2022-06-26 22:49 UTC, donovaly commented on src/Base/Builder3D.cpp
> -  //char lp[20] = "0x";
not necessary for the PR

2022-06-26 22:49 UTC, donovaly commented on src/App/ExpressionParser.tab.c
> +#if !defined _Noreturn && (!defined __STDC_VERSION__ || __STDC_VERSION__ < 201112)
not necessary for the PR

2022-06-27 12:04 UTC, donovaly commented
@mosfet80 , can you please stop committing before you read my posts and reviews?

2022-06-27 22:42 UTC, merged