[PartGui] Add Font and Color Preferences to Measure dimensions
FreeCAD/FreeCAD pull request #7148
Opened 2022-07-08 20:07 UTC by VM4Dim

![out](https://user-images.githubusercontent.com/96398106/178056208-ecf59fbc-d526-4b85-acde-20864c9eb421.png)

2022-07-08 20:16 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7148/pipeline.svg"/></a> for feature branch [PR_7148](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148). Pipeline [583743067](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/583743067) was triggered at [705b810](https://github.com/FreeCAD/FreeCAD/pull/7148/commits/705b8105620f725027b3cb6da6e4cc242be20500). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-08 20:58 UTC, FlachyJoe commented on src/Mod/Part/Gui/DlgSettingsMeasure.h
> +  std::unique_ptr<Ui_DlgSettingsMeasure> ui;
FreeCAD-CI says
_error: 'unique_ptr' in namespace 'std' does not name a template type_

2022-07-09 00:37 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7148/pipeline.svg"/></a> for feature branch [PR_7148](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148). Pipeline [583837731](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/583837731) was triggered at [9c7497a](https://github.com/FreeCAD/FreeCAD/pull/7148/commits/9c7497ad13ed5d74adb4face44b055067ce1ee10). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-09 03:14 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7148/pipeline.svg"/></a> for feature branch [PR_7148](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148). Pipeline [583885582](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/583885582) was triggered at [f79c3f7](https://github.com/FreeCAD/FreeCAD/pull/7148/commits/f79c3f7dd6411ca766a11f233ee3667679c8b20d). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-09 10:24 UTC, luzpaz commented
Triggered Snap build at: https://github.com/FreeCAD/FreeCAD-snap/actions/runs/2640758200

2022-07-09 12:03 UTC, donovaly requested changes
Many thanks! 
Great and very welcome addition.

I only have some basic remarks.
Technically one also has to take care of the preference pack, But I will do this when the PR is merged.

2022-07-09 12:03 UTC, donovaly commented on src/Mod/Part/Gui/TaskDimension.cpp
> +  ParameterGrp::handle group = App::GetApplication().GetUserParameter().GetGroup("BaseApp/Preferences/View");
This is the same code block as above in line 503. Please sort it out to a separate function or a lambda to avoid code duplication

2022-07-09 16:35 UTC, adrianinsaval commented
Considering these tools are actually from the part workbench does it make sense to have the settings in Part Design?

2022-07-09 19:10 UTC, luzpaz commented
Snap available for testing:  
`snap install freecad --channel="latest/edge/test-7148-Part-measure"`

To return to stable or edge respectively:  
`snap refresh freecad --channel=stable`
`snap refresh freecad --channel=latest/edge`

2022-07-09 21:37 UTC, donovaly commented
> does it make sense to have the settings in Part Design?

They are correctly already in part, see also https://wiki.freecadweb.org/Part_Module#Preferences

2022-07-09 22:21 UTC, donovaly commented
> Considering these tools are actually from the part workbench does it make sense to have the settings in Part Design?

Since it appears frequently that it is not clear that the preferences are for both, Part and PD, I make this PR to clarify it: #7154

2022-07-12 14:08 UTC, VM4Dim commented
@donovaly
I don't want to write name. Really, I'm not claiming copyright.
I copied this header from other files for consistency.
You can change it as needed.

2022-07-12 14:19 UTC, luzpaz commented
Question: Will this feature lead to issues regarding missing fonts when sharing models between systems that don't have said font(s) installed?

2022-07-12 14:33 UTC, VM4Dim commented
> Question: Will this feature lead to issues regarding missing fonts when sharing models between systems that don't have said font(s) installed?

No. These preferences are saved in the local config, not in the model file (.fcstd)

2022-07-12 14:42 UTC, luzpaz commented
> No. These preferences are saved in the local config, not in the model file (.fcstd)

What happens if the font in question is not installed on the system. Is there a fall-back font ?

2022-07-12 15:52 UTC, VM4Dim commented
You can try what happens if the font is not installed
 by writing a non-existent font name in:

Tools > Edit parameters
BaseApp/Preferences/View > DimensionsFontName

For me it works.

2022-07-12 16:41 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7148/pipeline.svg"/></a> for feature branch [PR_7148](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148). Pipeline [586198126](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/586198126) was triggered at [c551b3c](https://github.com/FreeCAD/FreeCAD/pull/7148/commits/c551b3c1a16b61c0d0450075570c4c68d41ebe9f). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-13 01:31 UTC, donovaly commented
> I don't want to write name. Really, I'm not claiming copyright.

This is not possible in some countries. For example in Germany you cannot give away your copyright and someone must have the copyright. However, nobody forbids to use a fake name and mail address ;-)

I don't understand what you fear. FreeCAD is free, no company, no military etc.

But OK, we respect of course your will and the license is clear.

2022-07-13 22:15 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7148/pipeline.svg"/></a> for feature branch [PR_7148](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148). Pipeline [587412679](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/587412679) was triggered at [b47c19f](https://github.com/FreeCAD/FreeCAD/pull/7148/commits/b47c19f892359a86467ffcfe626bbdd1087ef1d6). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-16 14:26 UTC, donovaly commented
> Considering these tools are actually from the part workbench does it make sense to have the settings in Part Design?

To make it more clear I changed now the name:
#7154 

In a YouTube video I saw last week the author complained about this wrong name and even called it a bug. Therefore I tend to backport this to FC 0.20.1. Do you agree and is it now more clear to you?

2022-07-16 15:12 UTC, adrianinsaval commented
It's definitively better, I didn't know the "General" tab also applied to Part WB

2022-07-16 16:04 UTC, donovaly commented
> It's definitively better, I didn't know the "General" tab also applied to Part WB

Thanks for testing. Yes, this confuses many users. Therefore I backported it now also to FC 0.20.1.

2022-07-16 16:56 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7148/pipeline.svg"/></a> for feature branch [PR_7148](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148). Pipeline [589532442](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589532442) was triggered at [b17c39c](https://github.com/FreeCAD/FreeCAD/pull/7148/commits/b17c39c4c720f8132553419c67e1c3c3052d6fe8). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-16 22:11 UTC, donovaly commented
I tested your Pr and it works so for, except of these 2 issues:

- the new default font is not the one as in FreeCAD 0.20/0.21
Current master:

![FreeCAD_1ipPLbLVvR](https://user-images.githubusercontent.com/1828501/179373367-9d7e5778-3874-47d9-abf9-3fb457556ee3.png)

with your patch applied:
![FreeCAD_sysL4rntBn](https://user-images.githubusercontent.com/1828501/179373372-8724854c-79f6-4901-a6f8-f4ae58add301.png)

- when I have **bold** and _italic_ checked, I don't get **_bold italic_** font.

2022-07-16 22:11 UTC, donovaly approved these changes

2022-07-18 02:14 UTC, VM4Dim commented
>     * the new default font is not the one as in FreeCAD 0.20/0.21
I add "defaultFont" (at end of list).
>     * when I have **bold** and _italic_ checked, I don't get **_bold italic_** font.
Probably it depends on the specific font.

2022-07-18 02:18 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7148/pipeline.svg"/></a> for feature branch [PR_7148](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148). Pipeline [589970273](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/589970273) was triggered at [26c2af8](https://github.com/FreeCAD/FreeCAD/pull/7148/commits/26c2af89072c402caab6c5a09fe1f3a7b2e47500). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-18 08:27 UTC, donovaly commented on src/Mod/Part/Gui/AppPartGui.cpp
> +    (void)new Gui::PrefPageProducer<PartGui::DlgSettingsMeasure>(QT_TRANSLATE_NOOP("QObject","Part/Part Design") );
Please one line later

2022-07-18 09:03 UTC, donovaly commented
> I add "defaultFont" (at end of list).

Yes I see, but I know that people will complain that suddenly the font will look different despite they did not change anything.
I see now that "Default" did not apply any font, therefore at least on Windows you get a font Windows or Qt chooses for you. It seems this is "Courier New".
With your PR the font "MS Shell Dlg 2" is used.

So maybe we can purposely set as initial font the font "" and the OS will then choose a font and not FC's default font is used. However, I cannot test this right now.

> > * when I have **bold** and _italic_ checked, I don't get **_bold italic_** font.
> > ```
> Probably it depends on the specific font.

So the feature works for you? For me I can select any font but never get bold _and_ italic. I will check this now on another PC.

2022-07-18 09:25 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7148/pipeline.svg"/></a> for feature branch [PR_7148](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7148). Pipeline [590206161](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/590206161) was triggered at [c221a8b](https://github.com/FreeCAD/FreeCAD/pull/7148/commits/c221a8b7ee3e5c7ff4a4e4cb6056196699daebcd). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-18 09:51 UTC, donovaly commented
OK, Bold _and_ Italic does not work for me. However, I think let's merge it now and fix the small things bit by bit. I am pretty sure that there will be feedback in the forum and the feature will be polished anyway.

So merging now. Subsequently I will change the -UI file to match the wording style of the other preferences tab.

2022-07-18 09:52 UTC, merged

2022-07-18 10:34 UTC, VM4Dim commented
Old commits (not *v4) is also merged?
It doubled include in CMakeLists.txt.


Bold & Italic work for me.

2022-07-18 10:44 UTC, donovaly commented
I already made a cleanup:
https://github.com/FreeCAD/FreeCAD/commit/a5eb40a9a

> Bold & Italic work for me.

For me not, also not on another PC. Strange but OK, minor thing.

2022-07-18 18:17 UTC, VM4Dim commented
After fix [Mod/Part]
![out](https://user-images.githubusercontent.com/96398106/179575500-42e32b9c-9398-4e7f-a011-cdcba9fa6bcd.png)

2022-07-18 23:20 UTC, donovaly commented
> [View > Mod/Part] it remained unchanged for Bold & Italic in DlgSettingsMeasure.ui

Thanks, fixed now.

2022-07-18 23:23 UTC, donovaly commented
> After fix [Mod/Part] ![out](https://user-images.githubusercontent.com/96398106/179575500-42e32b9c-9398-4e7f-a011-cdcba9fa6bcd.png)

Sadly not for me:
![FreeCAD_22KDNzgk4x](https://user-images.githubusercontent.com/1828501/179632961-3490db1a-1c13-473b-a7ba-a92b3a44492c.gif)

2022-09-14 18:00 UTC, Roy-043 commented
I experience the same issue as @donovaly: can't combine bold and italic.
```
OS: Windows 8.1 Version 6.3 (Build 9600)
Word size of FreeCAD: 64-bit
Version: 0.21.30345 (Git)
Build type: Release
Branch: master
Hash: f42a47aa0fd8c4f34ef63c185d9f29b9b6e84737
Python 3.8.13, Qt 5.15.4, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: Dutch/Netherlands (nl_NL)
Installed mods: 
```

2022-09-14 18:24 UTC, adrianinsaval commented
is there a difference if you use arial instead of courier new as in VM4Dim's example?

2022-09-15 11:42 UTC, donovaly commented
I tried almost all fonts installed on my Windows, and it works with none of them.

2022-09-15 14:24 UTC, adrianinsaval commented on src/Mod/Part/Gui/TaskDimension.cpp
> +    + (group->GetBool("DimensionsFontStyleItalic", false) ? " :Italic" : "");
perhaps these should just be " Bold" and " Italic"?

2022-09-15 17:18 UTC, VM4Dim commented
Seems it should be: ":Bold Italic"
https://github.com/coin3d/coin/blob/Coin-4.0.0/src/nodes/SoFontStyle.cpp#L194-L205

> switch (this->style.getValue()) {
  case SoFontStyle::NONE:
    break;
  case SoFontStyle::BOLD:
    fontname += ":Bold";
    break;
  case SoFontStyle::ITALIC:
    fontname += ":Italic";
    break;
  case (SoFontStyle::BOLD | SoFontStyle::ITALIC):
    fontname += ":Bold Italic";
    break;

2022-09-16 01:10 UTC, donovaly commented
> Seems it should be: ":Bold Italic"

Thanks!
With this info the fix was simple: https://github.com/FreeCAD/FreeCAD/commit/2d61e15112e9bdf1659660758bb4d1f1f964ad2e

Result:

![FreeCAD_FITQoAyFHp](https://user-images.githubusercontent.com/1828501/190535082-3a5bd03b-87db-42fa-8084-19aec1221e0d.png)

2022-09-19 10:08 UTC, wwmayer commented
@VM4Dim @donovaly 
> I don't want to write name. Really, I'm not claiming copyright.
I copied this header from other files for consistency.
You can change it as needed.

Just for the sake of completeness: https://matija.suklje.name/how-and-why-to-properly-write-copyright-statements-in-your-code#what-if-i-want-to-stay-anonymous

Alternatively, you can use this copyright header: https://github.com/FreeCAD/FreeCAD/blob/master/src/App/Metadata.cpp

2022-09-19 11:02 UTC, donovaly commented
> Alternatively, you can use this copyright header: https://github.com/FreeCAD/FreeCAD/blob/master/src/App/Metadata.cpp

Thanks. As @VM4Dim agreed, we added this header already to the new files:
https://github.com/VM4Dim/FreeCAD/blob/26c2af89072c402caab6c5a09fe1f3a7b2e47500/src/Mod/Part/Gui/DlgSettingsMeasure.cpp
and
https://github.com/VM4Dim/FreeCAD/blob/26c2af89072c402caab6c5a09fe1f3a7b2e47500/src/Mod/Part/Gui/DlgSettingsMeasure.h

Is there anything missing?