[PD Pad/Pocket] Fix bug with midplane usage in TwoLengths mode
FreeCAD/FreeCAD pull request #7216
Opened 2022-07-18 19:20 UTC by adrianinsaval

properly fix issue reported here: https://forum.freecadweb.org/viewtopic.php?f=3&t=70266

also reverted a previous commit that auto unchecked the midplane option in the task panel since it is now unnecessary with the fix and may result annoying if you want to go back to length mode expecting it to remain checked, also it is inconsistent since it only gets unchecked for two lengths but not the other modes were it is not a valid option either. IMO this was more a workaround than an actual fix for the bug as it could still be encountered through the property view or in old files.

2022-07-18 19:21 UTC, adrianinsaval commented
@donovaly

2022-07-18 19:27 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7216"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7216/pipeline.svg"/></a> for feature branch [PR_7216](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7216). Pipeline [590739657](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/590739657) was triggered at [dc80a06](https://github.com/FreeCAD/FreeCAD/pull/7216/commits/dc80a061a7025add9c9a4664a350b036c1c7bfa0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-07-19 01:27 UTC, donovaly requested changes
Thanks. Handling this in App is indeed better. However, you must set midplane to false nevertheless. With your PR I get this when changing to "two dimensions":

![FreeCAD_2OQG4ffhvo](https://user-images.githubusercontent.com/1828501/179644111-7a10c43c-b3e0-44de-9016-e9527b6595fd.png)

So I see that symmetric is true but since two different lengths are used, it cannot be symmetric.

2022-07-19 01:31 UTC, donovaly commented on src/Mod/PartDesign/App/FeatureExtrude.cpp
> -    // disable everything unless we are sure we don't need it
Thanks, I fixed this now in master.

2022-07-19 01:43 UTC, adrianinsaval commented
But by that logic we should set midplane to false for everything except length, IMO there is no advantage in doing that, all them ignore it. In any case you may merge only the fix in App and skip the commit I reverted (but then it would be inconsistent for all the other modes)

2022-07-20 01:12 UTC, donovaly commented
> But by that logic we should set midplane to false for everything except length, IMO there is no advantage in doing that

That was my initial point but you stated tat the logic is also important for the App part. As it is, is shows symmetric while the model is apparently not symmetric.

Merging since I agree that App is not that important.

2022-07-20 01:13 UTC, merged

2022-07-20 01:16 UTC, adrianinsaval commented
The point I tried to make was that in App it should not care about midplane value when doing twolengths so I changed that, I never cared about what value midplane displayed. Thanks for merging! Please backport to 0.20 too.

2022-07-20 01:24 UTC, donovaly commented
> Please backport to 0.20 too.

Done.