Gui: when customizing shortcuts, warn user if command isn't in use with a message box
FreeCAD/FreeCAD pull request #7261
Opened 2022-07-27 10:23 UTC by 0penBrain

User was only warned in the report view which he/she may missed.
Use a warning message box.
Also provide advice about how to solve.

https://forum.freecadweb.org/viewtopic.php?f=8&t=39858

How it looks :
![image](https://user-images.githubusercontent.com/48731257/181224659-efb67e3c-ce76-4d0b-ba64-377e87965db4.png)

2022-07-29 16:00 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7261"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7261/pipeline.svg"/></a> for feature branch [PR_7261](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7261). Pipeline [600453095](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/600453095) was triggered at [abc49f6](https://github.com/FreeCAD/FreeCAD/pull/7261/commits/abc49f6602a81dc0131ce2ef0331ea7b177d6c28). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-09-13 23:32 UTC, chennes commented on src/Gui/DlgKeyboardImp.cpp
> +                             "To be able to do, please make '%2' the active workbench").arg(data.toString(),ui->categoryBox->currentText()),
I suggest "To enable assignment, please..." instead of "To be able to do, please...".

2022-09-13 23:34 UTC, chennes requested changes
I think the language needs a small tweak, but otherwise this is a nice addition, thanks.

2022-09-14 06:51 UTC, 0penBrain commented
> I think the language needs a small tweak, but otherwise this is a nice addition, thanks.

Done. Rebasing at the same time. ;)

2022-09-14 06:58 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7261"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7261/pipeline.svg"/></a> for feature branch [PR_7261](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7261). Pipeline [639555954](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/639555954) was triggered at [77b0f22](https://github.com/FreeCAD/FreeCAD/pull/7261/commits/77b0f223e616f8b8a936e613cbaed47cf8ef46de). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-09-14 20:01 UTC, merged

2022-09-14 20:02 UTC, chennes commented
Thanks!

2022-09-15 11:38 UTC, donovaly commented
Backported for 0.20.2

2022-09-15 12:51 UTC, luzpaz commented
JFYI, i think we should also mention something about autoloading workbenches by appending '...or choose to [autoload](https://wiki.freecad.org/Preferences_Editor#Available_Workbenches) it'

2022-09-15 14:22 UTC, 0penBrain commented
@luzpaz I don't think that changing shortcuts is something you do at every startup, so autoloading just for this seems a bit overkill to me. ;)

2022-09-15 14:30 UTC, luzpaz commented
Point taken.