[TD]HLR and Face Finding to Threads
FreeCAD/FreeCAD pull request #7377
Opened 2022-08-17 22:27 UTC by WandererFan

https://www.forum.freecadweb.org/viewtopic.php?p=611590#p611590

Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ ]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [ ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ ]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ ]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [ ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ ]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [ ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the issue ID number from our [Issues database](https://github.com/FreeCAD/FreeCAD/issues) in case a particular commit solves or is related to an existing issue. Ex: `Draft: fix typos - fixes #4805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---

2022-08-17 23:48 UTC, benj5378 requested changes
Probably the longest review I have ever done. Both in terms of comments and time used. Wow, I really want to go to bed now... And I didn't even do much else than looking on the formatting... reading the actual code through is... anyways, goodnight.

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewDetail.cpp
>          }
What is all this? Could it be moved to a separate function?

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewDetail.cpp
> +            if ((xp.More() != Standard_True)) {
```suggestion
            if (xp.More() != Standard_True) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewDetail.cpp
> +            if ((xp.More() != Standard_True)) {
```suggestion
            if (xp.More() != Standard_True) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
>  }
Code structure/formatting/unnested/simplicity 😍👠💋💪

```suggestion
    if (links.empty())  {
        return TopoDS_Shape();
    }
    return ShapeExtractor::getShapes(links);
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
> +    return TopoDS_Shape();
Isn't this function the same as `DrawViewPart::getSourceShape()`

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
>          }
```suggestion
        } // else if (s.ShapeType() == TopAbs_EDGE) {
              //not supporting edges yet.
//            Base::Console().Message("DVP::add2dShapes - found loose edge - isNull: %d\n", s.IsNull());
//            TopoDS_Shape sTrans = TechDraw::moveShape(s,
//                                                      m_saveCentroid * -1.0);
//            TopoDS_Shape sScale = TechDraw::scaleShape(sTrans,
//                                                       getScale());
//            TopoDS_Shape sMirror = TechDraw::mirrorShape(sScale);
//            TopoDS_Edge edge = TopoDS::Edge(sMirror);
//            BaseGeomPtr bg = projectEdge(edge);

//            geometryObject->addEdge(bg);
            //save connection between source feat and this edge
        // }
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
> +
Code structure/formatting/unnested/simplicity 😍👠💋💪

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
>      }
```suggestion
    if (ScaleType.isValue("Automatic") && !checkFit()) {
        double newScale = autoScale();
        Scale.setValue(newScale);
        Scale.purgeTouched();
        partExec(m_saveShape);
    }

```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
> +    for (; itOuter != nonZero.end(); ++itOuter, iOuter++) {
```suggestion
    for (int iOuter = 0; itOuter != nonZero.end(); ++itOuter, iOuter++) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
> +            double param = -1;      //parametric point on edge where the vertex touches
```suggestion
            constexpr double param = -1;      //parametric point on edge where the vertex touches
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
>          int iInner = 0;
```suggestion
        constexpr int iInner = 0;
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
> +            (!child->isRemoving()) ) {
```suggestion
        if (child->getTypeId().isDerivedFrom(DrawHatch::getClassTypeId()) &&
            !child->isRemoving()) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
> +             (!child->isRemoving()) ) {
```suggestion
        if (child->getTypeId().isDerivedFrom(DrawGeomHatch::getClassTypeId()) &&
             !child->isRemoving()) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
>      return result;
```suggestion
    if (waitingForFaces()) {
        return std::vector<TechDraw::FacePtr>();
    }
    if (!geometryObject) {
        return std::vector<TechDraw::FacePtr>();
    }
    return geometryObject->getFaceGeometry();
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewPart.cpp
> +    return false;
Code structure/formatting/unnested/simplicity 😍👠💋💪

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewSection.cpp
> +    if (Scale.isTouched() ||
Code structure/formatting/unnested/simplicity 😍👠💋💪

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewSection.cpp
> +    } else if ((prop == &FileHatchPattern) && doc) {
```suggestion
    } else if (prop == &FileHatchPattern && doc) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewSection.cpp
> +    } else if ((prop == &FileGeomPattern) && doc) {
```suggestion
    } else if (prop == &FileGeomPattern && doc) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewSection.cpp
> +    for (; sectionExpl.More(); sectionExpl.Next()) {
Comment to myself: to do, move to functions

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewSection.cpp
> +        result = Base::Vector3d(gXDir.X(),
No code structure/formatting/unnested/simplicity? :(

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewSection.cpp
> +    }
```suggestion
    if (PatIncluded.isEmpty())  {
        return;
    }

    std::string fileSpec = PatIncluded.getValue();
    Base::FileInfo fi(fileSpec);
    std::string ext = fi.extension();
    if (!fi.isReadable()) {
        Base::Console().Message("%s can not read hatch file: %s\n", getNameInDocument(), fileSpec.c_str());
        return;
    }

    if (
        ext != "pat" ||
        ext != "PAT" ||
        fileSpec.empty() ||
        NameGeomPattern.isEmpty()
    ) {
        return;
    }

    m_lineSets.clear();
    m_lineSets = DrawGeomHatch::makeLineSets(fileSpec, NameGeomPattern.getValue());
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewSection.cpp
> +    return result;
```suggestion
    return hGrp->GetBool("debugSection",false);
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/App/DrawViewSection.cpp
> +    return result;
```suggestion
    return hGrp->GetInt("CutSurfaceDisplay", 2);   //default to SvgHatch
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/DrawGuiUtil.cpp
> +                QString windowTitle = mvp->windowTitle();
Unused variable?

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGIView.cpp
> +    return nullptr;
Code structure/formatting/unnested/simplicity 😍👠💋💪

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGIView.cpp
> +    return nullptr;
Code structure/formatting/unnested/simplicity 😍👠💋💪

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGIViewSection.cpp
> +    float lineWidth    = sectionVp->LineWidth.getValue();
```suggestion
    float lineWidth = sectionVp->LineWidth.getValue();
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +}
Avoid nesting

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +    return result;
Return directly, no need for variable

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +    return attachView(const_cast<App::DocumentObject*>(obj));
Note to myself: deprecate function aliases

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +    return (qview != nullptr);
```suggestion
    return qview != nullptr;
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +        if (((*itInspect)->type() == dimItemType) && (!(*itInspect)->group())) {
```suggestion
        if ((*itInspect)->type() == dimItemType && !(*itInspect)->group()) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +        if (((*itInspect)->type() == balloonItemType) && (!(*itInspect)->group())) {
```suggestion
        if ((*itInspect)->type() == balloonItemType && !(*itInspect)->group()) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +        if (((*itInspect)->type() == leadItemType) && (!(*itInspect)->group())) {
```suggestion
        if ((*itInspect)->type() == leadItemType && !(*itInspect)->group()) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +        if (((*itInspect)->type() == annoItemType) && (!(*itInspect)->group())) {
```suggestion
        if ((*itInspect)->type() == annoItemType && !(*itInspect)->group()) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +}
Note to myself: catch for loop patterns

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +   }
Note to myself: refactor

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +        if (obj == nullptr) {
```suggestion
        if (!obj) {
```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/QGSPage.cpp
> +                }
Simplify this

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp
>                  }
Avoid nesting

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp
> +    return nullptr;
Code structure/formatting/unnested/simplicity 😍👠💋💪

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/ViewProviderDrawingView.cpp
> +                    if (vpPage->getQGSPage()) {
Note to myslef: refactor

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/ViewProviderPage.cpp
>      }
```suggestion
    if (prop == &(ShowGrid)) {
        setGrid();
    } else if (prop == &(GridSpacing)) {
        setGrid();
    } else if (prop == &Visibility) {
        //Visibility changes are handled in VPDO::onChanged -> show() or hide()
    }

```

2022-08-17 23:48 UTC, benj5378 commented on src/Mod/TechDraw/Gui/ViewProviderPage.cpp
> +        if (found) {
```suggestion
        if (wList.contains(m_mdiView)) {

```

2022-08-18 05:35 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7377"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7377/pipeline.svg"/></a> for feature branch [PR_7377](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7377). Pipeline [616385983](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/616385983) was triggered at [bb8f6df](https://github.com/FreeCAD/FreeCAD/pull/7377/commits/bb8f6df3679da314359a9563e0d1d9f3a51920d5). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-08-18 13:34 UTC, WandererFan commented
I'll look at the format changes in a separate PR.  Need to get this out for more user testing.

2022-08-18 13:34 UTC, merged

2022-08-18 14:10 UTC, luzpaz commented
@WandererFan I just re-triggered the Snap edge which will include this commit. If users want to jump in and test, they can just update their snaps in about ~1 hour from now

2022-08-18 21:26 UTC, adrianinsaval commented
I asked for a beta build of the flatpak (including the fix recently pushed), the weekly appimage, windows and mac builds are likely going to be available next thursday.