Topo Naming Accumulated Fix
FreeCAD/FreeCAD pull request #7514
Opened 2022-09-22 13:53 UTC by realthunder

Forum thread https://forum.freecadweb.org/viewtopic.php?f=44&t=71687&sid=c92e0d2bbd2d0fadc0b6bb42a7128889&start=10#p626675

2022-09-23 12:18 UTC, donovaly requested changes

2022-09-23 12:18 UTC, donovaly commented on src/Mod/Part/App/FeatureExtrusion.cpp
> +    ADD_PROPERTY_TYPE(AutoTaperInnerAngle,(true), "Extrude", App::Prop_None,
This is a new option and should therefore not be part of the toponaming branch.

Please only commit what is absolutely necessary for toponaming. All further features are of course very welcome, but please sort them out to each a separate PR for master.

2022-09-24 13:38 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7514"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7514/pipeline.svg"/></a> for feature branch [PR_7514](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7514). Pipeline [649698444](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/649698444) was triggered at [32c75d1](https://github.com/FreeCAD/FreeCAD/pull/7514/commits/32c75d1ddb218a2d4f8c091819019e7a472c7a7a). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-09-24 14:28 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7514"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7514/pipeline.svg"/></a> for feature branch [PR_7514](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7514). Pipeline [649710732](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/649710732) was triggered at [22c0f02](https://github.com/FreeCAD/FreeCAD/pull/7514/commits/22c0f0253b2b2d5ce08b046f1822db7e898d847b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-09-24 18:03 UTC, donovaly commented
Many thanks!

I would merge, but get this error:
```
Check failure on line 70 in src/Gui/Application.cpp
GitHub Actions / Checks

'GuiInitScript.h' file not found [clang-diagnostic-error]

```
see https://github.com/FreeCAD/FreeCAD/pull/7514/commits/22c0f025

Can you please have a look?

2022-09-25 00:23 UTC, realthunder commented
We can ignore this error, because the file is generated during the build [here](https://github.com/FreeCAD/FreeCAD/blob/cef5e6f4abe33f446354c01187bafecf71922ba0/src/Gui/CMakeLists.txt#L237).

2022-09-25 12:48 UTC, berndhahnebach commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7514"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_7514/pipeline.svg"/></a> for feature branch [PR_7514](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_7514). Pipeline [650059861](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/650059861) was triggered at [d2bef89](https://github.com/FreeCAD/FreeCAD/pull/7514/commits/d2bef8900b2719e191c6dcb8d87a55b29ad27a39). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2022-09-25 18:25 UTC, merged

2022-09-25 18:28 UTC, donovaly commented
many thanks! I merged this now.

Before announcing, can you please review the toponaming branch if it contains some new features that are not necessary for toponaming? Just to be sure we have the most lean code change.