CI various improvements
FreeCAD/FreeCAD pull request #8463
Opened 2023-02-12 21:38 UTC by 0penBrain

This PR brings some improvements to CI.

Structure:
* Cmake configure, build & install steps are factorized in a composite action for both Linux jobs

Performance:
* Logging is improved for configure, build & install steps
  * Line buffered output for stdout & stderr
  * Full log contains both stdout & stderr (previously only stdout) so errors can be looked at contextually

Other:
* Rename Ubuntu build jobs for better comprehension
* Spell checker (lint) will silently fail. Not failing the workflow anymore, but still reporting errors
* In wrapup job, deleting used artifact is allowed to fail (already happened that it failed a job)

2023-02-12 21:49 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8463"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_8463/pipeline.svg"/></a> for feature branch [PR_8463](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8463). Pipeline [775329525](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/775329525) was triggered at [94a36fd](https://github.com/FreeCAD/FreeCAD/pull/8463/commits/94a36fdc549f6ee5f254955bda063cb3d15bc2b1). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2023-02-13 01:42 UTC, luzpaz requested changes

2023-02-13 01:42 UTC, luzpaz commented on .github/workflows/actions/linux/build/action.yml
> +# *   Copyright (c) 2023 0penBrain                               *
Fix whitespace

2023-02-13 01:42 UTC, luzpaz commented on .github/workflows/actions/linux/configure/action.yml
> +# *   Copyright (c) 2023 0penBrain                               *
Fix whitespace

2023-02-13 01:42 UTC, luzpaz commented on .github/workflows/actions/linux/install/action.yml
> +# *   Copyright (c) 2023 0penBrain                               *
Fix whitespace

2023-02-13 10:27 UTC, 0penBrain commented on .github/workflows/actions/linux/build/action.yml
> +# *   Copyright (c) 2023 0penBrain                               *
See #8223

2023-02-13 10:27 UTC, merged