[Bugfix] Gui: fix bug in expression completer tokenizing
FreeCAD/FreeCAD pull request #8565
Opened 2023-02-20 18:11 UTC by 0penBrain

https://forum.freecad.org/viewtopic.php?t=76239

The problem is that in the tuple returned by `tokenizeExpression`, the std::string is converted to QString, but the character position is still stored as computed in the std::string. This breaks when using UTF-8 chars as their representation size isn't same in std::string and QString.
The PR fixes the problem by recomputing the character position in the QString representation.

2023-02-20 18:21 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8565"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_8565/pipeline.svg"/></a> for feature branch [PR_8565](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8565). Pipeline [783494557](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/783494557) was triggered at [338f23a](https://github.com/FreeCAD/FreeCAD/pull/8565/commits/338f23a60a7bab55d5c28096f2885af9c8a13218). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2023-02-22 10:18 UTC, wwmayer requested changes
Your PR fixes the reported problem.

When testing current master (i.e. without your fix) the application even crashes for me. This happens in line 886 because of this incorrect check:
`if (!stringing && prefix.isEmpty() && prefix[prefixEnd-1] == QChar(32))`

So, it would be good to add this change to your PR too:
`if (!stringing && prefix.size() >= prefixEnd && prefix[prefixEnd-1] == QChar(32))`

In order to later find the reasons of a change it would be good to add the forum link as comment into the code.

Another point -- but this would be too much for this PR -- is to refactor the function slotUpdate() and move the whole tokenizing logic to its own class. This class could be added to FreeCADApp and would allow it write some unit tests.

2023-02-22 14:33 UTC, 0penBrain commented
> When testing current master (i.e. without your fix) the application even crashes for me.

Yes, I guess because (as I do), you're using a debug build. In this case Qt has a strong assert about not iterating over the QString size. In Release builds it only fails silently.

> So, it would be good to add this change to your PR too: `if (!stringing && prefix.size() >= prefixEnd && prefix[prefixEnd-1] == QChar(32))`

I hesitated but at the end thought it doesn't add anything useful. Qt already checks that and, for example in this case, it was actually very useful that it wasn't implemented. Made the bug easy to find. :) But if you think it's needed, no problem to add it.

> In order to later find the reasons of a change it would be good to add the forum link as comment into the code.

How about creating an issue in GH (pointing to the forum) and adding a "fixes #XXXX" in the commit message?

2023-02-22 14:55 UTC, wwmayer commented
> In Release builds it only fails silently.

And isn't this undefined behaviour, then? According to the Qt code in release mode it accesses a memory address outside the array and then everything can happen. Most of the time the program will continue but sometimes it really crashes.

> How about creating an issue in GH (pointing to the forum) and adding a "fixes #XXXX" in the commit message?

Either this or add the forum link to the commit message. Do as you like.

2023-02-22 17:38 UTC, 0penBrain commented
> And isn't this undefined behaviour, then? According to the Qt code in release mode it accesses a memory address outside the array and then everything can happen.

Indeed. I had to check the Qt source code too. I thought that in release mode, the `[]` operator would either throw an exception (that it doesn't do for sure) or return an empty `QChar()` if trying to access out of boundaries. But actually it indeed just blindly access the memory. :)

2023-02-22 17:52 UTC, 0penBrain commented
> So, it would be good to add this change to your PR too:
> `if (!stringing && prefix.size() >= prefixEnd && prefix[prefixEnd-1] == QChar(32))`

OK, made the change. This said, the fix in the PR shall already prevent this.
So if we are at having this kind of checks, shouldn't we also check `prefixEnd > 0` ?

2023-02-23 12:47 UTC, wwmayer commented
> So if we are at having this kind of checks, shouldn't we also check prefixEnd > 0 ?

Yes. As I see you did this already the PR can be merged now.

2023-02-23 12:49 UTC, merged

2023-02-23 12:57 UTC, 0penBrain commented
@donovaly to backported ?

2023-02-24 01:25 UTC, donovaly commented
> @donovaly to backported ?

Yes. But first this regression must be fixed: https://github.com/FreeCAD/FreeCAD/pull/7255#issuecomment-1442656426
(I noticed this directly after backporting and this way also broke the stable branch :-( )

2023-02-24 07:20 UTC, 0penBrain commented
> > @donovaly to backported ?
> 
> Yes. But first this regression must be fixed: [#7255 (comment)](https://github.com/FreeCAD/FreeCAD/pull/7255#issuecomment-1442656426)

I propose to backport this + #8612 + #8624
I can do it as a batch when I'll merge the 2 latter ones later in the day.
Is is OK for you ?

2023-02-24 12:17 UTC, wwmayer commented
Yesterday I had a quick look at it and almost copied the entire function to the v0.20 branch. However, there still the same problem can be observed. Since there are made some further fixes recently we should consider copying over the whole class.

2023-02-24 13:05 UTC, donovaly commented
> > > @donovaly to backported ?
> > 
> > 
> > Yes. But first this regression must be fixed: [#7255 (comment)](https://github.com/FreeCAD/FreeCAD/pull/7255#issuecomment-1442656426)
> 
> I propose to backport this + #8612 + #8624 I can do it as a batch when I'll merge the 2 latter ones later in the day. Is is OK for you ?

Sure. Thanks in advance. Don't forget to update the backporting list in the forum. #8624 is already backported

2023-02-27 01:19 UTC, donovaly commented
I backported this now.
Concerning #8612, I could not backport because too many things were changed in master in the meantime.