add cbrt (cube root) to expressions
FreeCAD/FreeCAD pull request #8629
Opened 2023-02-24 14:34 UTC by berberic2

This adds a function cbrt(arg) to the freecad-expressions that computes the cube root of arg. Instead of arg^(1/3) this handles the units of the argument, so that one can compute units from p.e. ml to mm.

  cbrt(27 ml) → 30 mm

instead of

  (27 ml)^(1/3) → 30

see also:

https://forum.freecad.org/viewtopic.php?style=1&p=663161

⚠ I added the enum after sqrt, so renumbering following enums.

2023-02-24 14:46 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8629"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_8629/pipeline.svg"/></a> for feature branch [PR_8629](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8629). Pipeline [788195905](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/788195905) was triggered at [4c10297](https://github.com/FreeCAD/FreeCAD/pull/8629/commits/4c10297ae7f0a8a1a1fc9ef558cf98e240254ad4). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2023-02-24 20:16 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8629"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_8629/pipeline.svg"/></a> for feature branch [PR_8629](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8629). Pipeline [788488047](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/788488047) was triggered at [319bdc3](https://github.com/FreeCAD/FreeCAD/pull/8629/commits/319bdc3de4b06b737bdad4d051d6249bed20afb0). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2023-02-26 04:09 UTC, chennes commented
Thanks for the PR, this seems like a good idea. In my testing, however, I am not getting an error when entering a unit that isn't a power of three. I was testing (in Spreadsheet) `cbrt(27 ml/s)` and simply got 3mm as the answer, with no indication that the seconds were lost.

2023-02-26 08:24 UTC, berberic2 commented
> Thanks for the PR, this seems like a good idea. In my testing, however, I am not getting an error when entering a unit that isn't a power of three. I was testing (in Spreadsheet) `cbrt(27 ml/s)` and simply got 3mm as the answer, with no indication that the seconds were lost.

Yes. Same here.
But this is the exact same behaviour as with `sqrt()` There also the seconds vanish: `sqrt(9mm^2/s) → 3.00 mm`

This might be a bug or intended behaviour, I don’t know, but it is a more general problem.

2023-02-26 14:24 UTC, donovaly requested changes
Looks good and is pretty straight forward by using the sqrt code.

Can you please fix the commit message because cbrt(27) is 3 not 30.

2023-02-26 14:24 UTC, donovaly commented on src/App/Expression.cpp
> +	        _EXPR_THROW("All dimensions must be multiples of 3 to compute the cube root.",expr);
minor: indentation of this line seems too wide, we use a space after a comma

2023-02-26 14:24 UTC, donovaly commented on src/App/Expression.cpp
> +	    output = cbrt(value);
indentation too wide

2023-02-26 14:25 UTC, donovaly commented
> This might be a bug or intended behaviour, I don’t know, but it is a more general problem.

This is in my opinion a general problem. Can you therefore please open a bug report?

2023-02-26 14:35 UTC, berberic2 commented
> Can you please fix the commit message because cbrt(27) is 3 not 30.

Yes, but cbrt(27 ml) = cbrt(27 cm³) = 3 cm = 30 mm

2023-02-26 14:41 UTC, donovaly commented
> (27 ml)^(1/3) → 30

I thought you state that ^(1/3) ignores the unit. I see now that it takes care of the unit, but don't output it. So your commit message is OK then.

2023-02-26 15:05 UTC, berberic2 commented
> > (27 ml)^(1/3) → 30
> 
> I thought you state that ^(1/3) ignores the unit. I see now that it takes care of the unit, but don't output it. So your commit message is OK then.

I think, that the internal representation of `27 ml` is `27000 mm³`, it drops the unit and calculates[ ∛27000 = 30](url).

2023-02-26 15:12 UTC, donovaly commented
So just please fix the minor code formatting I mentioned, then rebase the PR and then it could go in in my opinion.

2023-02-26 15:43 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8629"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_8629/pipeline.svg"/></a> for feature branch [PR_8629](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8629). Pipeline [789300231](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789300231) was triggered at [ae002d8](https://github.com/FreeCAD/FreeCAD/pull/8629/commits/ae002d875e5fc0cf050548dd84ccd93b6fd41e3b). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2023-02-26 16:47 UTC, donovaly approved these changes

2023-02-26 16:49 UTC, merged

2023-02-26 16:50 UTC, donovaly commented
Please also update the Wiki pages that people are aware of the new expression.

2023-02-26 18:39 UTC, wwmayer commented
> I think, that the internal representation of 27 ml is 27000 mm³, it drops the unit and calculates ∛27000 = 30.

There is a bug here: https://github.com/FreeCAD/FreeCAD/blob/master/src/Base/Unit.cpp#L122 Because 1/3 is rounded to 0 all dimensions are lost.

2023-02-26 19:08 UTC, donovaly commented
> > I think, that the internal representation of 27 ml is 27000 mm³, it drops the unit and calculates ∛27000 = 30.
> 
> There is a bug here: https://github.com/FreeCAD/FreeCAD/blob/master/src/Base/Unit.cpp#L122 Because 1/3 is rounded to 0 all dimensions are lost.

Can you please fix this - I won't have time right now.

2023-02-26 19:22 UTC, donovaly commented
> Please also update the Wiki pages that people are aware of the new expression.

I did this now: https://wiki.freecad.org/Expressions#Exponential_and_logarithmic_functions