Improve usage of the term 'platform' in CONTRIBUTING.md
FreeCAD/FreeCAD pull request #8653
Opened 2023-02-25 22:20 UTC by Daniel-Khodabakhsh

This PR improves `CONTRIBUTING.md` by replacing some instances of the term `Platform` with `GitHub` for the following reasons:

* This was unnecessary legalese which made the document harder to comprehend.
* Fixes a few ambiguous usages of the term:
  * In one usage there is ambiguity if there is a platform called "Platform".
  * Ambiguous with other usages of the word when referring to the runtime platform.
* Fixes one incorrect usage of the term, where reference to `"Platform"` was intended to refer to any other platform OTHER THAN `GitHub` or `"the Platform"`.

---

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

2023-02-25 22:30 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8653"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_8653/pipeline.svg"/></a> for feature branch [PR_8653](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8653). Pipeline [789002546](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789002546) was triggered at [e8e56f0](https://github.com/FreeCAD/FreeCAD/pull/8653/commits/e8e56f04839046e570181cf1bd4bbffc8de087ce). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2023-02-25 22:39 UTC, chennes requested changes
Thanks for the PR -- one word change requested (see below).

2023-02-25 22:39 UTC, chennes commented on CONTRIBUTING.md
> +4. FreeCAD uses the GitHub's issue-tracking system to track problems and contributions. For help requests and general discussions, use the project forum.
```suggestion
4. FreeCAD uses GitHub's issue-tracking system to track problems and contributions. For help requests and general discussions, use the project forum. 
```

2023-02-25 22:40 UTC, Daniel-Khodabakhsh commented on CONTRIBUTING.md
> +4. FreeCAD uses the GitHub's issue-tracking system to track problems and contributions. For help requests and general discussions, use the project forum.
Thanks for catching that!

2023-02-25 22:44 UTC, chennes approved these changes

2023-02-25 22:47 UTC, chennes commented
I basically think this is a good idea: I'm holding off on merging immediately to give other Maintainers an opportunity to comment on the PR (since there isn't a GitHub Issue it's not clear that this is an "identified and agreed-on problem", to use the terms from the document).

2023-02-25 22:48 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8653"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_8653/pipeline.svg"/></a> for feature branch [PR_8653](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_8653). Pipeline [789005947](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/789005947) was triggered at [f443f27](https://github.com/FreeCAD/FreeCAD/pull/8653/commits/f443f2746d0750eede3b4ff422c6b478d4fec2ce). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2023-02-27 14:55 UTC, yorikvanhavre commented
I fundamentally agree this should be an easy to understand document, although I'm a bit uneasy to add the name of a commercial product in our guidelines... But I have no better idea :/

2023-02-27 16:32 UTC, chennes commented
@yorikvanhavre fundamentally that was the reason we used the "legalese" in the first place, to try to de-emphasize "GitHub". But it's probably not worth it if that causes confusion for new contributors. I'm going to merge this, and we can continue to refine the document over time if someone comes up with a better solution later on.

2023-02-27 16:33 UTC, merged

2023-02-28 09:48 UTC, yorikvanhavre commented
Agree!