Core: rework WorkbenchGroup & WorkbenchComboBox
FreeCAD/FreeCAD pull request #9534
Opened 2023-05-10 08:53 UTC by PaddleStroke

To solve : https://github.com/FreeCAD/FreeCAD/issues/9479

I came upon what seemed to be unecessarily convoluted code (please tell me if I'm missing something). So I simplified it and solved the mentioned issue. 
Also it now have the advantage of not requiring a restart of the application when the wb are activated / moved.

I may have missed some advanced usecase (such as changing of workbench using python) so if you know of them could you test if they are still ok?

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [x]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

2023-05-10 15:00 UTC, adrianinsaval commented
It's crashing while running the GUI tests, it only shows up for ubuntu because GUI tests are not run on the windows CI
given this line on the errors:
`#19  0x7f278896d419 in Gui::Application::sRemoveWorkbenchHandler(_object*, _object*) from /usr/local/lib/libFreeCADGui.so+0x119`
I think this is the test that is crashing:
https://github.com/FreeCAD/FreeCAD/blob/ecb72b8eadced103cc648990f8ebe251d64c3f43/src/Mod/Test/Workbench.py#L59-L78

it might be causing refreshWorkbenchList to access a null pointer or something like that

2023-05-15 12:50 UTC, wwmayer commented
This code snippet is extracted from the unit test and it crash at the line when it removes the currently active workbench:
```
import __main__
class UnitWorkbench(__main__.Workbench):
    MenuText = "Unittest"
    ToolTip = "Unittest"
    def Initialize(self):
        cmds = ["Test_Test"]
        self.appendToolbar("My Unittest",cmds)
    def GetClassName(self):
        return "Gui::PythonWorkbench"

FreeCADGui.addWorkbench(UnitWorkbench())
wbs=FreeCADGui.listWorkbenches()
FreeCADGui.activateWorkbench("UnitWorkbench")
FreeCADGui.updateGui()
FreeCADGui.activeWorkbench().name()=="UnitWorkbench"
FreeCADGui.removeWorkbench("UnitWorkbench") ### <<<<<<<<<<======== CRASH!
wbs=FreeCADGui.listWorkbenches()
```

Internally removeWorkbench() calls WorkbenchGroup::refreshWorkbenchList() and since the active workbench has been removed `WorkbenchManager::instance()->active()` return a null pointer which isn't checked and thus crashes when accessing the name() method.

2023-05-15 13:32 UTC, wwmayer commented
> I came upon what seemed to be unnecessarily convoluted code (please tell me if I'm missing something).

Things worked a bit differently at Qt3/Qt4 times and required some workarounds to avoid crashes when switching between workbenches.

2023-05-16 08:45 UTC, PaddleStroke commented
> Things worked a bit differently at Qt3/Qt4 times and required some workarounds to avoid crashes when switching between workbenches.

Thanks for the feedback. Then is my code proposal good / didn't I miss some usecases ?
I'm not sure to understand your explanations concerning the test crash so I will need to get back to this in more depth.

2023-05-16 09:07 UTC, wwmayer commented
> Then is my code proposal good

Except for the crash. Look at my comments...

> didn't I miss some usecases

1. Changing the wb from Python updates the combo box. OK
2. Changing the wb from the combo box updates the sub-menu. OK
3. Changing the wb from the sub-menu updates the combo box. OK

> I'm not sure to understand your explanations concerning the test crash so I will need to get back to this in more depth.

The call of removeWorkbench() internally calls WorkbenchGroup::refreshWorkbenchList() which gets the active workbench. But if the removed wb was the active wb then at this point there is no active wb any more. WorkbenchManager::instance()->active() returns a null pointer in this case but further down the null pointer will be de-referenced.

2023-05-16 09:08 UTC, wwmayer requested changes
See comments in source code

2023-05-22 23:36 UTC, sliptonic commented
Is this now fully resolved?  Can it be merged?

2023-06-18 17:16 UTC, freecadci commented
<a href="https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9534"><img alt="pipeline status" src="https://gitlab.com/freecad/FreeCAD-CI/badges/PR_9534/pipeline.svg"/></a> for feature branch [PR_9534](https://gitlab.com/freecad/FreeCAD-CI/-/commits/PR_9534). Pipeline [903667667](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines/903667667) was triggered at [c3c5f49](https://github.com/FreeCAD/FreeCAD/pull/9534/commits/c3c5f491ef62fad70169bfc59f7f717ce9dac959). All CI [branches](https://gitlab.com/freecad/FreeCAD-CI/-/branches/all) and [pipelines](https://gitlab.com/freecad/FreeCAD-CI/-/pipelines?scope=branches).

2023-06-19 15:27 UTC, merged