[Start] Fix Minor Regression on LoadCustom
FreeCAD/FreeCAD pull request #9868
Opened 2023-07-03 14:49 UTC by Syres916

Handle image files using FreeCADGui but all other formats using FreeCAD in order to stop progress bar appearing to hang.

Note: Black formatting applied

Thank you for creating a pull request to contribute to FreeCAD! Place an "X" in between the brackets below to "check off" to confirm that you have satisfied the requirement, or ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10) if there is something you don't understand.

- [ ]  Your Pull Request meets the requirements outlined in section 5 of [CONTRIBUTING.md](https://github.com/FreeCAD/FreeCAD/blob/master/CONTRIBUTING.md) for a Valid PR

Please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [1.0 Changelog Forum Thread](https://forum.freecad.org/viewtopic.php?f=10&t=69438).

---

2023-07-04 09:57 UTC, yorikvanhavre commented
I actually use this for IFC files too... What about inverting the logic, only pass .FCStd through App.loadFile (or even App.open or Gui.open), and all the rest through Gui.loadFile? In any case it is done through a module and not the core...

Also, the same issue probably applies to https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Start/StartPage/LoadMRU.py... Maybe worth doing the same there?

2023-07-07 06:15 UTC, benj5378 requested changes

2023-07-07 06:15 UTC, benj5378 commented on src/Mod/Start/StartPage/LoadCustom.py
> +        or ext.lower() == "xpm"
```suggestion
        ext.lower() in ("bmp", "cur", "gif, ...)
```

2023-07-07 06:15 UTC, benj5378 commented on src/Mod/Start/StartPage/LoadCustom.py
> +        or ext.lower() == "igs"
```suggestion
        ext.lower() in ("bmp", "cur", "gif, ...)
```

2023-07-07 11:40 UTC, merged